// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// AiChatCompletions AI 对话。AI chat completions.
//
// 访问令牌权限: repo-code:r
//
// CNB API: POST /{repo}/-/ai/chat/completions
func (s *AIService) AiChatCompletions(ctx context.Context, repo string, body AiChatCompletionsReq) (*AiChatCompletionsResult, *Response, error) {
	u := escapePath("/%s/-/ai/chat/completions", repo)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out AiChatCompletionsResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}
