// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"encoding/json"
	"net/http"
)

// GetUserActivitiesByDate 获取动态活跃详情。Get user activities.
//
// 访问令牌权限: account-engage:r
//
// CNB API: GET /users/{username}/activities
func (s *ActivitiesService) GetUserActivitiesByDate(ctx context.Context, username string, opts *GetUserActivitiesByDateOptions) (*ActivityDate, *Response, error) {
	u := escapePath("/users/%s/activities", username)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out ActivityDate
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetUserCalendar 获取活跃点日历。Get activity calendar.
//
// 访问令牌权限: account-engage:r
//
// CNB API: GET /users/{username}/calendar
func (s *ActivitiesService) GetUserCalendar(ctx context.Context, username string, opts *GetUserCalendarOptions) (*ActivityCalendar, *Response, error) {
	u := escapePath("/users/%s/calendar", username)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out ActivityCalendar
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetUserRepoActivityDetails 获取仓库动态详情。Get repository activity details.
//
// 访问令牌权限: account-engage:r
//
// CNB API: GET /users/{username}/repo-activities/{activityType}
func (s *ActivitiesService) GetUserRepoActivityDetails(ctx context.Context, username string, activityType string, opts *GetUserRepoActivityDetailsOptions) ([]json.RawMessage, *Response, error) {
	u := escapePath("/users/%s/repo-activities/%s", username, activityType)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []json.RawMessage
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// TopContributors 获取仓库 top 活跃用户。List the top active users.
//
// 访问令牌权限: repo-basic-info:r
//
// CNB API: GET /{repo}/-/top-activity-users
func (s *ActivitiesService) TopContributors(ctx context.Context, repo string, opts *TopContributorsOptions) ([]*UsersResult, *Response, error) {
	u := escapePath("/%s/-/top-activity-users", repo)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*UsersResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
