// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// GetArtifactSecurityOverview 查询制品安全概览。Get artifact security overview.
//
// 访问令牌权限: registry-security:r
//
// CNB API: GET /{slug}/-/sca-artifact-scan/{type}/{name}/-/tag/{tag}/security/overview
func (s *ArtifactSecurityService) GetArtifactSecurityOverview(ctx context.Context, pkgType string, name string, tag string, opts *GetArtifactSecurityOverviewOptions) (*OpenAPIArtifactOverview, *Response, error) {
	u := escapePath("/{slug}/-/sca-artifact-scan/%s/%s/-/tag/%s/security/overview", pkgType, name, tag)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out OpenAPIArtifactOverview
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}
