// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// DeleteAsset 删除 asset 记录。Delete an asset record by ID.
//
// 访问令牌权限: repo-manage:rw
//
// CNB API: DELETE /{repo}/-/assets/{assetID}
func (s *AssetsService) DeleteAsset(ctx context.Context, repo string, assetID int) (*Response, error) {
	u := escapePath("/%s/-/assets/%d", repo, assetID)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// GetFiles 获取 Issue/PR 文件。Get issue/PR files.
//
// 访问令牌权限: repo-code:r
//
// CNB API: GET /{repo}/-/files/{filePath}
func (s *AssetsService) GetFiles(ctx context.Context, repo string, filePath string) (*Response, error) {
	u := escapePath("/%s/-/files/%s", repo, filePath)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// GetImgs 获取 Issue/PR 图片。Get issue/PR images.
//
// 访问令牌权限: repo-code:r
//
// CNB API: GET /{repo}/-/imgs/{imgPath}
func (s *AssetsService) GetImgs(ctx context.Context, repo string, imgPath string) (*Response, error) {
	u := escapePath("/%s/-/imgs/%s", repo, imgPath)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// ListAssets 获取仓库 asset 记录列表。Get repository asset records.
//
// 访问令牌权限: repo-manage:r
//
// CNB API: GET /{slug}/-/list-assets
func (s *AssetsService) ListAssets(ctx context.Context, slug string, opts *ListAssetsOptions) ([]*AssetRecords, *Response, error) {
	u := escapePath("/%s/-/list-assets", slug)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*AssetRecords
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
