// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// GetBadge 获取徽章数据。Get badge data.
//
// 访问令牌权限: repo-commit-status:r
//
// CNB API: GET /{repo}/-/badge/git/{sha}/{badge}
func (s *BadgeService) GetBadge(ctx context.Context, repo string, sha string, badge string, body GetBadgeReq) (*GetBadgeResult, *Response, error) {
	u := escapePath("/%s/-/badge/git/%s/%s", repo, sha, badge)
	req, err := s.client.NewRequest(http.MethodGet, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out GetBadgeResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// ListBadge 获取徽章列表。Get badge list.
//
// 访问令牌权限: repo-commit-status:r
//
// CNB API: GET /{repo}/-/badge/list
func (s *BadgeService) ListBadge(ctx context.Context, repo string, body ListBadgeReq) (*ListBadgeResult, *Response, error) {
	u := escapePath("/%s/-/badge/list", repo)
	req, err := s.client.NewRequest(http.MethodGet, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out ListBadgeResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// UploadBadge 上传徽章数据。Upload badge data.
//
// 访问令牌权限: repo-commit-status:rw
//
// CNB API: POST /{repo}/-/badge/upload
func (s *BadgeService) UploadBadge(ctx context.Context, repo string, body UploadBadgeReq) (*UploadBadgeResult, *Response, error) {
	u := escapePath("/%s/-/badge/upload", repo)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out UploadBadgeResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}
