// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// BuildCrontabSync 同步分支定时任务。Sync branch crontab tasks.
//
// 访问令牌权限: repo-cnb-trigger:rw
//
// CNB API: POST /{repo}/-/build/crontab/sync/{branch}
func (s *BuildService) BuildCrontabSync(ctx context.Context, repo string, branch string) (*BuildCommonResult, *Response, error) {
	u := escapePath("/%s/-/build/crontab/sync/%s", repo, branch)
	req, err := s.client.NewRequest(http.MethodPost, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out BuildCommonResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetBuildLogs 查询流水线构建列表。List pipeline builds.
//
// 访问令牌权限: repo-cnb-history:r
//
// CNB API: GET /{repo}/-/build/logs
func (s *BuildService) GetBuildLogs(ctx context.Context, repo string, opts *GetBuildLogsOptions) (*BuildLogsResult, *Response, error) {
	u := escapePath("/%s/-/build/logs", repo)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out BuildLogsResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetBuildAiAudit 查询流水线 AI 用量汇总。Get pipeline AI usage summary.
//
// 访问令牌权限: repo-cnb-history:r
//
// CNB API: GET /{repo}/-/build/logs/ai-audit/{sn}/{pipelineId}
func (s *BuildService) GetBuildAiAudit(ctx context.Context, repo string, sn string, pipelineId string) (*BuildAiAuditResult, *Response, error) {
	u := escapePath("/%s/-/build/logs/ai-audit/%s/%s", repo, sn, pipelineId)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out BuildAiAuditResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetBuildAiRequestDetail 查询单条 AI 请求详情。Get a single AI request detail.
//
// 访问令牌权限: repo-cnb-history:r
//
// CNB API: GET /{repo}/-/build/logs/ai-request-detail/{sn}/{pipelineId}/{requestId}
func (s *BuildService) GetBuildAiRequestDetail(ctx context.Context, repo string, sn string, pipelineId string, requestId string) (*BuildAiRequestDetailResult, *Response, error) {
	u := escapePath("/%s/-/build/logs/ai-request-detail/%s/%s/%s", repo, sn, pipelineId, requestId)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out BuildAiRequestDetailResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetBuildAiRequest 查询 AI 请求明细。List AI request entries.
//
// 访问令牌权限: repo-cnb-history:r
//
// CNB API: GET /{repo}/-/build/logs/ai-request/{sn}/{pipelineId}/{page}
func (s *BuildService) GetBuildAiRequest(ctx context.Context, repo string, sn string, pipelineId string, page int) (*BuildAiRequestResult, *Response, error) {
	u := escapePath("/%s/-/build/logs/ai-request/%s/%s/%d", repo, sn, pipelineId, page)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out BuildAiRequestResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetBuildStage 查询 Stage 详情。Get pipeline stage detail.
//
// 访问令牌权限: repo-cnb-trigger:r
//
// CNB API: GET /{repo}/-/build/logs/stage/{sn}/{pipelineId}/{stageId}
func (s *BuildService) GetBuildStage(ctx context.Context, repo string, sn string, pipelineId string, stageId string) (*BuildStageResult, *Response, error) {
	u := escapePath("/%s/-/build/logs/stage/%s/%s/%s", repo, sn, pipelineId, stageId)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out BuildStageResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// BuildLogsDelete 删除流水线日志内容。Delete pipeline logs content.
//
// 访问令牌权限: repo-cnb-trigger:rw
//
// CNB API: DELETE /{repo}/-/build/logs/{sn}
func (s *BuildService) BuildLogsDelete(ctx context.Context, repo string, sn string) (*BuildCommonResult, *Response, error) {
	u := escapePath("/%s/-/build/logs/%s", repo, sn)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out BuildCommonResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// BuildRunnerDownloadLog 流水线 Runner 日志下载。Pipeline runner log download.
//
// 访问令牌权限: repo-cnb-trigger:r
//
// CNB API: GET /{repo}/-/build/runner/download/log/{pipelineId}
func (s *BuildService) BuildRunnerDownloadLog(ctx context.Context, repo string, pipelineId string) (*Response, error) {
	u := escapePath("/%s/-/build/runner/download/log/%s", repo, pipelineId)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// StartBuild 开始一个构建。Start a build.
//
// 访问令牌权限: repo-cnb-trigger:rw
//
// CNB API: POST /{repo}/-/build/start
func (s *BuildService) StartBuild(ctx context.Context, repo string, body StartBuildReq) (*BuildResult, *Response, error) {
	u := escapePath("/%s/-/build/start", repo)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out BuildResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetBuildStatus 查询流水线构建状态。Get pipeline build status.
//
// 访问令牌权限: repo-cnb-trigger:r
//
// CNB API: GET /{repo}/-/build/status/{sn}
func (s *BuildService) GetBuildStatus(ctx context.Context, repo string, sn string) (*BuildStatusResult, *Response, error) {
	u := escapePath("/%s/-/build/status/%s", repo, sn)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out BuildStatusResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// StopBuild 停止一个构建。Stop a build.
//
// 访问令牌权限: repo-cnb-trigger:rw
//
// CNB API: POST /{repo}/-/build/stop/{sn}
func (s *BuildService) StopBuild(ctx context.Context, repo string, sn string) (*BuildResult, *Response, error) {
	u := escapePath("/%s/-/build/stop/%s", repo, sn)
	req, err := s.client.NewRequest(http.MethodPost, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out BuildResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}
