// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// GetQuota 获取组织月度额度。Get organization monthly quotas.
//
// 访问令牌权限: group-resource:r
//
// CNB API: GET /{slug}/-/charge/quota
func (s *ChargeService) GetQuota(ctx context.Context, slug string) (*VolumeQuotaResp, *Response, error) {
	u := escapePath("/%s/-/charge/quota", slug)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out VolumeQuotaResp
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetReposVolume 获取组织仓库用量。Get organization repository usage.
//
// 访问令牌权限: group-resource:r
//
// CNB API: GET /{slug}/-/charge/repos-volume
func (s *ChargeService) GetReposVolume(ctx context.Context, slug string, opts *GetReposVolumeOptions) ([]*RepoVolume, *Response, error) {
	u := escapePath("/%s/-/charge/repos-volume", slug)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*RepoVolume
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// GetSpecialAmount 查看特权额度。View privilege quotas.
//
// 访问令牌权限: group-resource:r
//
// CNB API: GET /{slug}/-/charge/special-amount
func (s *ChargeService) GetSpecialAmount(ctx context.Context, slug string) (*SpecialAmount, *Response, error) {
	u := escapePath("/%s/-/charge/special-amount", slug)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out SpecialAmount
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetVolume 获取组织资源用量。Get organization resource usage.
//
// 访问令牌权限: group-resource:r
//
// CNB API: GET /{slug}/-/charge/volume
func (s *ChargeService) GetVolume(ctx context.Context, slug string, opts *GetVolumeOptions) (*VolumeUsedResp, *Response, error) {
	u := escapePath("/%s/-/charge/volume", slug)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out VolumeUsedResp
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}
