// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"net/http"
	"net/url"
)

// Client 是 CNB OpenAPI (https://api.cnb.cool) 客户端.
type Client struct {
	client  *http.Client
	BaseURL *url.URL
	token   string

	// UserAgent 为空时使用默认值.
	UserAgent string
	// Accept 为空时使用默认值 application/json.
	Accept string

	AI               *AIService
	Activities       *ActivitiesService
	ArtifactSecurity *ArtifactSecurityService
	Assets           *AssetsService
	Badge            *BadgeService
	Build            *BuildService
	Charge           *ChargeService
	Events           *EventService
	Followers        *FollowersService
	Git              *GitService
	GitSettings      *GitSettingsService
	Issues           *IssuesService
	KnowledgeBase    *KnowledgeBaseService
	Members          *MembersService
	Missions         *MissionsService
	NpcObservability *NpcObservabilityService
	Organizations    *OrganizationsService
	Pulls            *PullsService
	Rank             *RankService
	Registries       *RegistriesService
	Releases         *ReleasesService
	RepoCodeIssue    *RepoCodeIssueService
	RepoContributor  *RepoContributorService
	Labels           *RepoLabelsService
	Repositories     *RepositoriesService
	Search           *SearchService
	Security         *SecurityService
	Starring         *StarringService
	Users            *UsersService
	Workspace        *WorkspaceService
	MissionResources *MissionResourcesService
}

// AIService 封装 AI 分类的 CNB API.
type AIService struct {
	client *Client
}

// ActivitiesService 封装 Activities 分类的 CNB API.
type ActivitiesService struct {
	client *Client
}

// ArtifactSecurityService 封装 ArtifactSecurity 分类的 CNB API.
type ArtifactSecurityService struct {
	client *Client
}

// AssetsService 封装 Assets 分类的 CNB API.
type AssetsService struct {
	client *Client
}

// BadgeService 封装 Badge 分类的 CNB API.
type BadgeService struct {
	client *Client
}

// BuildService 封装 Build 分类的 CNB API.
type BuildService struct {
	client *Client
}

// ChargeService 封装 Charge 分类的 CNB API.
type ChargeService struct {
	client *Client
}

// EventService 封装 Event 分类的 CNB API.
type EventService struct {
	client *Client
}

// FollowersService 封装 Followers 分类的 CNB API.
type FollowersService struct {
	client *Client
}

// GitService 封装 Git 分类的 CNB API.
type GitService struct {
	client *Client
}

// GitSettingsService 封装 GitSettings 分类的 CNB API.
type GitSettingsService struct {
	client *Client
}

// IssuesService 封装 Issues 分类的 CNB API.
type IssuesService struct {
	client *Client
}

// KnowledgeBaseService 封装 KnowledgeBase 分类的 CNB API.
type KnowledgeBaseService struct {
	client *Client
}

// MembersService 封装 Members 分类的 CNB API.
type MembersService struct {
	client *Client
}

// MissionsService 封装 Missions 分类的 CNB API.
type MissionsService struct {
	client *Client
}

// NpcObservabilityService 封装 NpcObservability 分类的 CNB API.
type NpcObservabilityService struct {
	client *Client
}

// OrganizationsService 封装 Organizations 分类的 CNB API.
type OrganizationsService struct {
	client *Client
}

// PullsService 封装 Pulls 分类的 CNB API.
type PullsService struct {
	client *Client
}

// RankService 封装 Rank 分类的 CNB API.
type RankService struct {
	client *Client
}

// RegistriesService 封装 Registries 分类的 CNB API.
type RegistriesService struct {
	client *Client
}

// ReleasesService 封装 Releases 分类的 CNB API.
type ReleasesService struct {
	client *Client
}

// RepoCodeIssueService 封装 RepoCodeIssue 分类的 CNB API.
type RepoCodeIssueService struct {
	client *Client
}

// RepoContributorService 封装 RepoContributor 分类的 CNB API.
type RepoContributorService struct {
	client *Client
}

// RepoLabelsService 封装 RepoLabels 分类的 CNB API.
type RepoLabelsService struct {
	client *Client
}

// RepositoriesService 封装 Repositories 分类的 CNB API.
type RepositoriesService struct {
	client *Client
}

// SearchService 封装 Search 分类的 CNB API.
type SearchService struct {
	client *Client
}

// SecurityService 封装 Security 分类的 CNB API.
type SecurityService struct {
	client *Client
}

// StarringService 封装 Starring 分类的 CNB API.
type StarringService struct {
	client *Client
}

// UsersService 封装 Users 分类的 CNB API.
type UsersService struct {
	client *Client
}

// WorkspaceService 封装 Workspace 分类的 CNB API.
type WorkspaceService struct {
	client *Client
}

// MissionResourcesService 封装 mission-resources 分类的 CNB API.
type MissionResourcesService struct {
	client *Client
}

// initServices 实例化所有 Service.
func (c *Client) initServices() {
	c.AI = &AIService{client: c}
	c.Activities = &ActivitiesService{client: c}
	c.ArtifactSecurity = &ArtifactSecurityService{client: c}
	c.Assets = &AssetsService{client: c}
	c.Badge = &BadgeService{client: c}
	c.Build = &BuildService{client: c}
	c.Charge = &ChargeService{client: c}
	c.Events = &EventService{client: c}
	c.Followers = &FollowersService{client: c}
	c.Git = &GitService{client: c}
	c.GitSettings = &GitSettingsService{client: c}
	c.Issues = &IssuesService{client: c}
	c.KnowledgeBase = &KnowledgeBaseService{client: c}
	c.Members = &MembersService{client: c}
	c.Missions = &MissionsService{client: c}
	c.NpcObservability = &NpcObservabilityService{client: c}
	c.Organizations = &OrganizationsService{client: c}
	c.Pulls = &PullsService{client: c}
	c.Rank = &RankService{client: c}
	c.Registries = &RegistriesService{client: c}
	c.Releases = &ReleasesService{client: c}
	c.RepoCodeIssue = &RepoCodeIssueService{client: c}
	c.RepoContributor = &RepoContributorService{client: c}
	c.Labels = &RepoLabelsService{client: c}
	c.Repositories = &RepositoriesService{client: c}
	c.Search = &SearchService{client: c}
	c.Security = &SecurityService{client: c}
	c.Starring = &StarringService{client: c}
	c.Users = &UsersService{client: c}
	c.Workspace = &WorkspaceService{client: c}
	c.MissionResources = &MissionResourcesService{client: c}
}
