// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

type AccessRole string

const (
	// Anonymous Anonymous 匿名
	Anonymous AccessRole = "Unknown"
	// Guest Guest 访客
	Guest AccessRole = "Guest"
	// REPORTER REPORTER 助手
	REPORTER AccessRole = "Reporter"
	// DEVELOPER DEVELOPER 开发
	DEVELOPER AccessRole = "Developer"
	// MASTER MASTER 管理
	MASTER AccessRole = "Master"
	// OWNER OWNER 负责人
	OWNER AccessRole = "Owner"
)

type RepoStatus int

const (
	// RepoStatusOK RepoStatusOK 仓库正常
	RepoStatusOK RepoStatus = 0
	// RepoStatusArchived RepoStatusArchived 仓库已归档
	RepoStatusArchived RepoStatus = 1
	// RepoStatusForking RepoStatusForking 仓库正在 fork中
	RepoStatusForking RepoStatus = 2
)

type SlugType int

const (
	// SlugTypeGroup SlugTypeGroup 分组
	SlugTypeGroup SlugType = 0
	// SlugTypeRepo SlugTypeRepo 仓库
	SlugTypeRepo SlugType = 1
	// SlugTypeMission SlugTypeMission 任务集
	SlugTypeMission SlugType = 2
	// SlugTypeRegistry SlugTypeRegistry 包
	SlugTypeRegistry SlugType = 3
	// SlugTypeUnknown SlugTypeUnknown unknown
	SlugTypeUnknown SlugType = 4
)

type UserType int

const (
	// WeChatUser WeChatUser 微信用户
	WeChatUser UserType = 0
	// OauthUser OauthUser oauth 授权用户
	OauthUser UserType = 1
	// TestUser TestUser 测试用户
	TestUser UserType = 2
	// RobotUser RobotUser 助手用户
	RobotUser UserType = 3
	// IoaUser IoaUser ioa 用户
	IoaUser UserType = 4
)

type Visibility string

const (
	// VisibilityPrivate VisibilityPrivate 私有仓库 - 仓库的访问必须显式授予每个用户
	VisibilityPrivate Visibility = "Private"
	// VisibilityPublic VisibilityPublic 公共仓库 - 可以不经任何身份验证克隆该项目
	VisibilityPublic Visibility = "Public"
	// VisibilitySecret VisibilitySecret 加密仓库 - 仓库特定角色身份才能读取解密
	VisibilitySecret Visibility = "Secret"
)

type AssetRecordType string

const (
	// AssetSlugImg AssetSlugImg issue/pr 图片
	AssetSlugImg AssetRecordType = "slug_img"
	// AssetSlugFile AssetSlugFile issue/pr 附件
	AssetSlugFile AssetRecordType = "slug_file"
	// AssetRepoRelease AssetRepoRelease release 附件
	AssetRepoRelease AssetRecordType = "repo_release"
	// AssetRepoCommit AssetRepoCommit commit 附件
	AssetRepoCommit AssetRecordType = "repo_commit"
	// AssetIssueImg AssetIssueImg issue 图片
	AssetIssueImg AssetRecordType = "issue_img"
	// AssetIssueFile AssetIssueFile issue 附件
	AssetIssueFile AssetRecordType = "issue_file"
	// AssetPullImg AssetPullImg pr 图片
	AssetPullImg AssetRecordType = "pull_img"
	// AssetPullFile AssetPullFile pr 附件
	AssetPullFile AssetRecordType = "pull_file"
	// AssetUnknown AssetUnknown ...
	AssetUnknown AssetRecordType = "unknown"
)

type InteractionType string

const (
	// InteractionTypeRadio InteractionTypeRadio ...
	InteractionTypeRadio InteractionType = "radio"
	// InteractionTypeCheckbox InteractionTypeCheckbox ...
	InteractionTypeCheckbox InteractionType = "checkbox"
	// InteractionTypeTimeSelector InteractionTypeTimeSelector ...
	InteractionTypeTimeSelector InteractionType = "time_selector"
)

type MissionViewSortOrder string

const (
	MissionViewSortOrderAsc  MissionViewSortOrder = "asc"
	MissionViewSortOrderDesc MissionViewSortOrder = "desc"
)

type MissionViewType string

const (
	MissionViewTypeTable MissionViewType = "table"
	MissionViewTypeBoard MissionViewType = "board"
	MissionViewTypeGantt MissionViewType = "gantt"
)

type OperatorType string

const (
	// OperatorTypeOldEqual OperatorTypeOldEqual 兼容旧版本数据类型定义
	OperatorTypeOldEqual OperatorType = "equal"
	// OperatorTypeEqual OperatorTypeEqual ...
	OperatorTypeEqual OperatorType = "equals"
	// OperatorTypeNotEqual OperatorTypeNotEqual ...
	OperatorTypeNotEqual OperatorType = "not_equals"
	// OperatorTypeContains OperatorTypeContains ...
	OperatorTypeContains OperatorType = "contains"
	// OperationTypeContainsAll OperationTypeContainsAll ...
	OperationTypeContainsAll OperatorType = "contains_all"
	// OperatorTypeNotContains OperatorTypeNotContains ...
	OperatorTypeNotContains OperatorType = "not_contains"
	// OperatorTypeEmpty OperatorTypeEmpty ...
	OperatorTypeEmpty OperatorType = "empty"
	// OperatorTypeNotEmpty OperatorTypeNotEmpty ...
	OperatorTypeNotEmpty OperatorType = "not_empty"
	// OperatorTypeBefore OperatorTypeBefore ...
	OperatorTypeBefore OperatorType = "before"
	// OperatorTypeAfter OperatorTypeAfter ...
	OperatorTypeAfter OperatorType = "after"
	// OperatorTypeDateRange OperatorTypeDateRange 兼容旧版本数据类型定义
	OperatorTypeDateRange OperatorType = "time_selector"
)

type PackageType string

const (
	// PackageTypeArtifactory PackageTypeArtifactory 仓库下的制品
	PackageTypeArtifactory PackageType = "all"
	// PackageTypeDocker PackageTypeDocker 容器制品，由 container 兼容
	PackageTypeDocker PackageType = "docker"
	// PackageTypeHelm PackageTypeHelm helm chart 制品，由 chart 兼容
	PackageTypeHelm PackageType = "helm"
	// PackageTypeDockerModel PackageTypeDockerModel docker model 制品
	PackageTypeDockerModel PackageType = "docker-model"
	// PackageTypeDockerModelAlias PackageTypeDockerModelAlias docker model 制品别名
	PackageTypeDockerModelAlias PackageType = "dockermodel"
	// PackageTypeNpm PackageTypeNpm npm 制品
	PackageTypeNpm PackageType = "npm"
	// PackageTypeMaven PackageTypeMaven maven 制品
	PackageTypeMaven PackageType = "maven"
	// PackageTypeOhpm PackageTypeOhpm ohpm 制品
	PackageTypeOhpm PackageType = "ohpm"
	// PackageTypePypi PackageTypePypi pypi 制品
	PackageTypePypi PackageType = "pypi"
	// PackageTypeComposer PackageTypeComposer composer 制品
	PackageTypeComposer PackageType = "composer"
	// PackageTypeNuget PackageTypeNuget nuget 制品
	PackageTypeNuget PackageType = "nuget"
	// PackageTypeConan PackageTypeConan conan 制品
	PackageTypeConan PackageType = "conan"
	// PackageTypeCargo PackageTypeCargo cargo 制品
	PackageTypeCargo PackageType = "cargo"
	// PackageTypeGeneric PackageTypeGeneric 通用制品
	PackageTypeGeneric PackageType = "generic"
)

// Repo 仓库特性标记，内容为枚举的组合，英文逗号分割 Repository feature flags. Content is a combination of enum values, separated by commas.
type Repo string

const (
	// Unknown Unknown 未知
	Unknown Repo = "Unknown"
	// KnowledgeBase KnowledgeBase 知识库
	KnowledgeBase Repo = "KnowledgeBase"
	// NPC NPC NPC
	NPC Repo = "NPC"
	// Skills Skills 技能
	Skills Repo = "Skills"
	// Wiki Wiki Wiki
	Wiki Repo = "Wiki"
)

type ChannelTypeTarget string

const (
	ChannelTypeInvite    ChannelTypeTarget = "invite"
	ChannelTypeDirectAdd ChannelTypeTarget = "direct_add"
	ChannelTypeTransfer  ChannelTypeTarget = "transfer"
	ChannelTypeAdminAdd  ChannelTypeTarget = "admin_add"
)

// SettingValue 配置值，内容为枚举的组合，英文逗号分割 Configuration value. Content is a combination of enum values, separated by commas.
type SettingValue string

const (
	// DisableOrganizationReadme DisableOrganizationReadme 是否关闭组织介绍页, 以组织设置为准
	DisableOrganizationReadme SettingValue = "disable_organization_readme"
	// CloudNativeDevOnly CloudNativeDevOnly 仅可使用云原生开发, 以组织设置为准
	CloudNativeDevOnly SettingValue = "cloud_native_dev_only"
	// UseRootGroupBranchProtectionOnly UseRootGroupBranchProtectionOnly 支持重写分支保护规则，打开时，如果保护分支规则存在差异，可以覆盖根组织的规则
	UseRootGroupBranchProtectionOnly SettingValue = "user_root_group_branch_protection_only"
	// ForbidRedefineBranchProtection ForbidRedefineBranchProtection 打开后，禁止仓库修改保护分支规则，以根组织设置为准
	ForbidRedefineBranchProtection SettingValue = "forbid_redefine_branch_protection"
	// EnableTAPDAccess EnableTAPDAccess 打开后，允许 TAPD 访问组织下的资源, 以组织设置为准
	EnableTAPDAccess SettingValue = "enable_tapd_access"
	// EnableShowPrivateMissionWaterMark EnableShowPrivateMissionWaterMark 打开后，私有任务集会显示水印
	EnableShowPrivateMissionWaterMark SettingValue = "enable_show_private_mission_water_mark"
	// PreventOrganizationCreation PreventOrganizationCreation 禁止创建组织
	PreventOrganizationCreation SettingValue = "prevent_organization_creation"
	// PreventRepositoryCreation PreventRepositoryCreation 禁止创建仓库
	PreventRepositoryCreation SettingValue = "prevent_repository_creation"
	// PreventMissionCreation PreventMissionCreation 禁止创建任务集
	PreventMissionCreation SettingValue = "prevent_mission_creation"
	// PreventRegistryCreation PreventRegistryCreation 禁止创建制品库
	PreventRegistryCreation SettingValue = "prevent_registry_creation"
	// DisableInvitation DisableInvitation 禁止邀请成员
	DisableInvitation SettingValue = "disable_invitation"
	// PreventVisibilityModification PreventVisibilityModification 禁止修改资源可见性
	PreventVisibilityModification SettingValue = "prevent_visibility_modification"
	// PreventResourceDeletion PreventResourceDeletion 禁止删除资源
	PreventResourceDeletion SettingValue = "prevent_resource_deletion"
	// PreventRepositoryArchival PreventRepositoryArchival 禁止归档仓库
	PreventRepositoryArchival SettingValue = "prevent_repository_archival"
	// PreventOrganizationTransfer PreventOrganizationTransfer 禁止转移组织
	PreventOrganizationTransfer SettingValue = "prevent_organization_transfer"
	// PreventRepositoryTransfer PreventRepositoryTransfer 禁止转移仓库
	PreventRepositoryTransfer SettingValue = "prevent_repository_transfer"
	// PreventMissionTransfer PreventMissionTransfer 禁止转移任务集
	PreventMissionTransfer SettingValue = "prevent_mission_transfer"
	// PreventRegistryTransfer PreventRegistryTransfer 禁止转移制品库
	PreventRegistryTransfer SettingValue = "prevent_registry_transfer"
	// UseGroupGitQuota UseGroupGitQuota 是否使用组织的仓库配额
	UseGroupGitQuota SettingValue = "use_group_git_quota"
	// UseGroupGitObjectLimit UseGroupGitObjectLimit 是否使用组织的仓库对象限制
	UseGroupGitObjectLimit SettingValue = "use_group_git_object_limit"
	// EnableAddMemberOnlyRoot enableAddMemberOnlyRoot 开启后, 仅根组织管理员和负责人可添加成员加入根组织下所有子组织和仓库
	EnableAddMemberOnlyRoot SettingValue = "enable_add_member_only_root"
	// UseRootGroupGitPushLimit UseRootGroupGitPushLimit 开启根组织推送管控选项
	UseRootGroupGitPushLimit SettingValue = "use_root_group_git_push_limit"
	// EnableAddMember enableAddMember 开启后, 允许子组织管理员和负责人添加成员到其负责的组织/仓库/制品库/任务集
	EnableAddMember SettingValue = "enable_add_member"
	// EnableChangeMemberRoleOnlyRoot enableChangeMemberRoleOnlyRoot 开启后, 仅根组织管理员和负责人可修改成员角色
	EnableChangeMemberRoleOnlyRoot SettingValue = "enable_change_member_role_only_root"
	// EnableOtherGroupNPCAddComment enableOtherGroupNPCAddComment 开启后, 允许其他根组织的npc在根组织内增加评论
	EnableOtherGroupNPCAddComment SettingValue = "enable_other_group_npc_add_comment"
	// DisableInviteAuthControl disableInviteAuthControl 关闭邀请认证管控
	DisableInviteAuthControl SettingValue = "disable_invite_auth_control"
	// OnlyRepoMemberCanMentionNPC onlyRepoMemberCanMentionNPC 开启后, 外部用户无法@NPC, 仅组织成员（含外部协作者）可@
	OnlyRepoMemberCanMentionNPC SettingValue = "only_repo_member_can_mention_npc"
	// AllowNpcCrossRepo allowNpcCrossRepo 开启后，NPC 不再局限于当前仓库，可以在根组织下的所有仓库之间自由协作，自动处理跨仓任务。
	AllowNpcCrossRepo SettingValue = "allow_npc_cross_repo"
)
