// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// GetEvents 获取仓库动态内容。Get repository events content.
//
// CNB API: GET /events/{repo}/-/{date}
func (s *EventService) GetEvents(ctx context.Context, repo string, date string) (*Response, error) {
	u := escapePath("/events/%s/-/%s", repo, date)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}
