// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// GetFollowersByUserID 获取粉丝列表。Get followers list.
//
// 访问令牌权限: account-engage:r
//
// CNB API: GET /users/{username}/followers
func (s *FollowersService) GetFollowersByUserID(ctx context.Context, username string, opts *GetFollowersByUserIDOptions) ([]*UserFollowResult, *Response, error) {
	u := escapePath("/users/%s/followers", username)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*UserFollowResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// GetFollowingByUserID 获取关注人列表。Get following list.
//
// 访问令牌权限: account-engage:r
//
// CNB API: GET /users/{username}/following
func (s *FollowersService) GetFollowingByUserID(ctx context.Context, username string, opts *GetFollowingByUserIDOptions) ([]*UserFollowResult, *Response, error) {
	u := escapePath("/users/%s/following", username)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*UserFollowResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
