// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// GetCommitAssets 下载 Commit 附件。Download commit attachments.
//
// 访问令牌权限: repo-code:r
//
// CNB API: GET /{repo}/-/commit-assets/download/{commit_id}/{filename}
func (s *GitService) GetCommitAssets(ctx context.Context, repo string, commitId string, filename string, opts *GetCommitAssetsOptions) (*Response, error) {
	u := escapePath("/%s/-/commit-assets/download/%s/%s", repo, commitId, filename)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// GetArchiveCommitChangedFiles 下载提交变更文件。Download changed files.
//
// 访问令牌权限: repo-code:r
//
// CNB API: GET /{repo}/-/git/archive-commit-changed-files/{sha1}
func (s *GitService) GetArchiveCommitChangedFiles(ctx context.Context, repo string, sha1 string) (*Response, error) {
	u := escapePath("/%s/-/git/archive-commit-changed-files/%s", repo, sha1)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// GetArchiveCompareChangedFiles 下载比较变更文件。Download compared changed files.
//
// 访问令牌权限: repo-code:r
//
// CNB API: GET /{repo}/-/git/archive-compare-changed-files/{base_head}
func (s *GitService) GetArchiveCompareChangedFiles(ctx context.Context, repo string, baseHead string) (*Response, error) {
	u := escapePath("/%s/-/git/archive-compare-changed-files/%s", repo, baseHead)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// GetArchive 下载仓库归档。Download repository archive.
//
// 访问令牌权限: repo-code:r
//
// CNB API: GET /{repo}/-/git/archive/{ref_with_path}
func (s *GitService) GetArchive(ctx context.Context, repo string, refWithPath string) (*Response, error) {
	u := escapePath("/%s/-/git/archive/%s", repo, refWithPath)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// CreateBlob 创建 Blob 对象。Create blob object.
//
// 访问令牌权限: repo-code:rw
//
// CNB API: POST /{repo}/-/git/blobs
func (s *GitService) CreateBlob(ctx context.Context, repo string, body PostBlobForm) (*Blob, *Response, error) {
	u := escapePath("/%s/-/git/blobs", repo)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out Blob
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// CreateBranchLock 锁定分支。Lock branch.
//
// 访问令牌权限: repo-code:rw
//
// CNB API: POST /{repo}/-/git/branch-locks/{branch}
func (s *GitService) CreateBranchLock(ctx context.Context, repo string, branch string) (*Response, error) {
	u := escapePath("/%s/-/git/branch-locks/%s", repo, branch)
	req, err := s.client.NewRequest(http.MethodPost, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// DeleteBranchLock 解锁分支。Unlock branch.
//
// 访问令牌权限: repo-code:rw
//
// CNB API: DELETE /{repo}/-/git/branch-locks/{branch}
func (s *GitService) DeleteBranchLock(ctx context.Context, repo string, branch string) (*Response, error) {
	u := escapePath("/%s/-/git/branch-locks/%s", repo, branch)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// ListBranches 查询分支列表。List branches.
//
// 访问令牌权限: repo-code:r
//
// CNB API: GET /{repo}/-/git/branches
func (s *GitService) ListBranches(ctx context.Context, repo string, opts *ListBranchesOptions) ([]*Branch, *Response, error) {
	u := escapePath("/%s/-/git/branches", repo)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*Branch
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// CreateBranch 创建分支。Create branch.
//
// 访问令牌权限: repo-code:rw
//
// CNB API: POST /{repo}/-/git/branches
func (s *GitService) CreateBranch(ctx context.Context, repo string, body CreateBranchForm) (*Response, error) {
	u := escapePath("/%s/-/git/branches", repo)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// GetBranch 获取分支。Get branch.
//
// 访问令牌权限: repo-code:r
//
// CNB API: GET /{repo}/-/git/branches/{branch}
func (s *GitService) GetBranch(ctx context.Context, repo string, branch string) (*BranchDetail, *Response, error) {
	u := escapePath("/%s/-/git/branches/%s", repo, branch)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out BranchDetail
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// DeleteBranch 删除分支。Delete branch.
//
// 访问令牌权限: repo-code:rw
//
// CNB API: DELETE /{repo}/-/git/branches/{branch}
func (s *GitService) DeleteBranch(ctx context.Context, repo string, branch string) (*Response, error) {
	u := escapePath("/%s/-/git/branches/%s", repo, branch)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// GetCommitAnnotationsInBatch 批量查询提交元数据。Batch get commit annotations.
//
// 访问令牌权限: repo-code:r
//
// CNB API: POST /{repo}/-/git/commit-annotations-in-batch
func (s *GitService) GetCommitAnnotationsInBatch(ctx context.Context, repo string, body GetCommitAnnotationsInBatchForm) ([]*CommitAnnotationInBatch, *Response, error) {
	u := escapePath("/%s/-/git/commit-annotations-in-batch", repo)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out []*CommitAnnotationInBatch
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// GetCommitAnnotations 查询提交元数据。Get commit annotations.
//
// 访问令牌权限: repo-code:r
//
// CNB API: GET /{repo}/-/git/commit-annotations/{sha}
func (s *GitService) GetCommitAnnotations(ctx context.Context, repo string, sha string) ([]*CommitAnnotation, *Response, error) {
	u := escapePath("/%s/-/git/commit-annotations/%s", repo, sha)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*CommitAnnotation
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// PutCommitAnnotations 设置提交元数据。Set commit annotations.
//
// 访问令牌权限: repo-code:rw
//
// CNB API: PUT /{repo}/-/git/commit-annotations/{sha}
func (s *GitService) PutCommitAnnotations(ctx context.Context, repo string, sha string, body PutCommitAnnotationsForm) (*Response, error) {
	u := escapePath("/%s/-/git/commit-annotations/%s", repo, sha)
	req, err := s.client.NewRequest(http.MethodPut, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// DeleteCommitAnnotation 删除提交元数据。Delete commit annotations.
//
// 访问令牌权限: repo-code:rw
//
// CNB API: DELETE /{repo}/-/git/commit-annotations/{sha}/{key}
func (s *GitService) DeleteCommitAnnotation(ctx context.Context, repo string, sha string, key string) (*Response, error) {
	u := escapePath("/%s/-/git/commit-annotations/%s/%s", repo, sha, key)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// GetCommitAssetsBySha 查询提交附件列表。List commit assets.
//
// 访问令牌权限: repo-code:r
//
// CNB API: GET /{repo}/-/git/commit-assets/{sha1}
func (s *GitService) GetCommitAssetsBySha(ctx context.Context, repo string, sha1 string) ([]*CommitAsset, *Response, error) {
	u := escapePath("/%s/-/git/commit-assets/%s", repo, sha1)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*CommitAsset
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// PostCommitAssetUploadConfirmation 确认提交附件上传。Confirm commit asset upload.
//
// 访问令牌权限: repo-code:rw
//
// CNB API: POST /{repo}/-/git/commit-assets/{sha1}/asset-upload-confirmation/{upload_token}/{asset_path}
func (s *GitService) PostCommitAssetUploadConfirmation(ctx context.Context, repo string, sha1 string, uploadToken string, assetPath string, opts *PostCommitAssetUploadConfirmationOptions) (*Response, error) {
	u := escapePath("/%s/-/git/commit-assets/%s/asset-upload-confirmation/%s/%s", repo, sha1, uploadToken, assetPath)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodPost, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// PostCommitAssetUploadURL 获取提交附件上传地址。Get commit asset upload URL.
//
// 访问令牌权限: repo-code:rw
//
// CNB API: POST /{repo}/-/git/commit-assets/{sha1}/asset-upload-url
func (s *GitService) PostCommitAssetUploadURL(ctx context.Context, repo string, sha1 string, body PostCommitAssetUploadURLForm) (*CommitAssetUploadURL, *Response, error) {
	u := escapePath("/%s/-/git/commit-assets/%s/asset-upload-url", repo, sha1)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out CommitAssetUploadURL
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// DeleteCommitAsset 删除提交附件。Delete commit asset.
//
// 访问令牌权限: repo-code:rw
//
// CNB API: DELETE /{repo}/-/git/commit-assets/{sha1}/{asset_id}
func (s *GitService) DeleteCommitAsset(ctx context.Context, repo string, sha1 string, assetId string) (*Response, error) {
	u := escapePath("/%s/-/git/commit-assets/%s/%s", repo, sha1, assetId)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// GetCommitStatuses 查询提交状态检查。Get commit statuses.
//
// 访问令牌权限: repo-code:r
//
// CNB API: GET /{repo}/-/git/commit-statuses/{commitish}
func (s *GitService) GetCommitStatuses(ctx context.Context, repo string, commitish string) ([]*CommitStatus, *Response, error) {
	u := escapePath("/%s/-/git/commit-statuses/%s", repo, commitish)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*CommitStatus
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// ListCommits 查询提交列表。List commits.
//
// 访问令牌权限: repo-code:r
//
// CNB API: GET /{repo}/-/git/commits
func (s *GitService) ListCommits(ctx context.Context, repo string, opts *ListCommitsOptions) ([]*Commit, *Response, error) {
	u := escapePath("/%s/-/git/commits", repo)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*Commit
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// GetCommit 获取提交。Get commit.
//
// 访问令牌权限: repo-code:r
//
// CNB API: GET /{repo}/-/git/commits/{ref}
func (s *GitService) GetCommit(ctx context.Context, repo string, ref string) (*Commit, *Response, error) {
	u := escapePath("/%s/-/git/commits/%s", repo, ref)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out Commit
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetCompareCommits 比较提交差异。Compare commits.
//
// 访问令牌权限: repo-code:r
//
// CNB API: GET /{repo}/-/git/compare/{base_head}
func (s *GitService) GetCompareCommits(ctx context.Context, repo string, baseHead string) (*CompareResponse, *Response, error) {
	u := escapePath("/%s/-/git/compare/%s", repo, baseHead)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out CompareResponse
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetContentWithoutPath 查询仓库根目录内容。Get repository root contents.
//
// 访问令牌权限: repo-code:r
//
// CNB API: GET /{repo}/-/git/contents
func (s *GitService) GetContentWithoutPath(ctx context.Context, repo string, opts *GetContentWithoutPathOptions) (*Content, *Response, error) {
	u := escapePath("/%s/-/git/contents", repo)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out Content
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetContent 查询仓库文件内容。Get repository file content.
//
// 访问令牌权限: repo-code:r
//
// CNB API: GET /{repo}/-/git/contents/{file_path}
func (s *GitService) GetContent(ctx context.Context, repo string, filePath string, opts *GetContentOptions) (*Content, *Response, error) {
	u := escapePath("/%s/-/git/contents/%s", repo, filePath)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out Content
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetHead 获取默认分支。Get default branch.
//
// 访问令牌权限: repo-code:r
//
// CNB API: GET /{repo}/-/git/head
func (s *GitService) GetHead(ctx context.Context, repo string) (*HeadRef, *Response, error) {
	u := escapePath("/%s/-/git/head", repo)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out HeadRef
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetRaw 获取文件原始内容。Get raw file content.
//
// 访问令牌权限: repo-code:r
//
// CNB API: GET /{repo}/-/git/raw/{ref_with_path}
func (s *GitService) GetRaw(ctx context.Context, repo string, refWithPath string, opts *GetRawOptions) (*string, *Response, error) {
	u := escapePath("/%s/-/git/raw/%s", repo, refWithPath)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out string
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// DeleteTagAnnotation 删除标签元数据。Delete tag annotations.
//
// 访问令牌权限: repo-release:rw
//
// CNB API: DELETE /{repo}/-/git/tag-annotations/{tag_with_key}
func (s *GitService) DeleteTagAnnotation(ctx context.Context, repo string, tagWithKey string) (*Response, error) {
	u := escapePath("/%s/-/git/tag-annotations/%s", repo, tagWithKey)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// GetTagAnnotations 查询标签元数据。Get tag annotations.
//
// 访问令牌权限: repo-release:r
//
// CNB API: GET /{repo}/-/git/tag-annotations/{tag}
func (s *GitService) GetTagAnnotations(ctx context.Context, repo string, tag string) ([]*TagAnnotation, *Response, error) {
	u := escapePath("/%s/-/git/tag-annotations/%s", repo, tag)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*TagAnnotation
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// PutTagAnnotations 设置标签元数据。Set tag annotations.
//
// 访问令牌权限: repo-release:rw
//
// CNB API: PUT /{repo}/-/git/tag-annotations/{tag}
func (s *GitService) PutTagAnnotations(ctx context.Context, repo string, tag string, body PutTagAnnotationsForm) (*Response, error) {
	u := escapePath("/%s/-/git/tag-annotations/%s", repo, tag)
	req, err := s.client.NewRequest(http.MethodPut, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// ListTags 查询标签列表。List tags.
//
// 访问令牌权限: repo-release:r
//
// CNB API: GET /{repo}/-/git/tags
func (s *GitService) ListTags(ctx context.Context, repo string, opts *ListTagsOptions) ([]*Tag, *Response, error) {
	u := escapePath("/%s/-/git/tags", repo)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*Tag
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// CreateTag 创建标签。Create tag.
//
// 访问令牌权限: repo-release:rw
//
// CNB API: POST /{repo}/-/git/tags
func (s *GitService) CreateTag(ctx context.Context, repo string, body PostTagFrom) (*Tag, *Response, error) {
	u := escapePath("/%s/-/git/tags", repo)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out Tag
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetTag 获取标签。Get tag.
//
// 访问令牌权限: repo-release:r
//
// CNB API: GET /{repo}/-/git/tags/{tag}
func (s *GitService) GetTag(ctx context.Context, repo string, tag string) (*Tag, *Response, error) {
	u := escapePath("/%s/-/git/tags/%s", repo, tag)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out Tag
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// DeleteTag 删除标签。Delete tag.
//
// 访问令牌权限: repo-release:rw
//
// CNB API: DELETE /{repo}/-/git/tags/{tag}
func (s *GitService) DeleteTag(ctx context.Context, repo string, tag string) (*Response, error) {
	u := escapePath("/%s/-/git/tags/%s", repo, tag)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// GetPresignedLFSDownloadLink 获取 LFS 文件下载链接。Get LFS file download URL.
//
// 访问令牌权限: repo-code:r
//
// CNB API: GET /{slug}/-/lfs/{oid}
func (s *GitService) GetPresignedLFSDownloadLink(ctx context.Context, slug string, oid string, opts *GetPresignedLFSDownloadLinkOptions) (*Response, error) {
	u := escapePath("/%s/-/lfs/%s", slug, oid)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}
