// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// ListBranchProtections 查询保护分支规则列表。List branch protection rules.
//
// 访问令牌权限: repo-manage:r
//
// CNB API: GET /{repo}/-/settings/branch-protections
func (s *GitSettingsService) ListBranchProtections(ctx context.Context, repo string) ([]*BranchProtection, *Response, error) {
	u := escapePath("/%s/-/settings/branch-protections", repo)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*BranchProtection
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// PostBranchProtection 创建保护分支规则。Create branch protection rule.
//
// 访问令牌权限: repo-manage:rw
//
// CNB API: POST /{repo}/-/settings/branch-protections
func (s *GitSettingsService) PostBranchProtection(ctx context.Context, repo string, body BranchProtection) (*Response, error) {
	u := escapePath("/%s/-/settings/branch-protections", repo)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// GetBranchProtection 获取保护分支规则。Get branch protection rule.
//
// 访问令牌权限: repo-manage:r
//
// CNB API: GET /{repo}/-/settings/branch-protections/{id}
func (s *GitSettingsService) GetBranchProtection(ctx context.Context, repo string, id string) (*BranchProtection, *Response, error) {
	u := escapePath("/%s/-/settings/branch-protections/%s", repo, id)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out BranchProtection
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// DeleteBranchProtection 删除保护分支规则。Delete branch protection rule.
//
// 访问令牌权限: repo-manage:rw
//
// CNB API: DELETE /{repo}/-/settings/branch-protections/{id}
func (s *GitSettingsService) DeleteBranchProtection(ctx context.Context, repo string, id string) (*Response, error) {
	u := escapePath("/%s/-/settings/branch-protections/%s", repo, id)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// PatchBranchProtection 更新保护分支规则。Update branch protection rule.
//
// 访问令牌权限: repo-manage:rw
//
// CNB API: PATCH /{repo}/-/settings/branch-protections/{id}
func (s *GitSettingsService) PatchBranchProtection(ctx context.Context, repo string, id string, body BranchProtection) (*Response, error) {
	u := escapePath("/%s/-/settings/branch-protections/%s", repo, id)
	req, err := s.client.NewRequest(http.MethodPatch, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// GetPipelineSettings 查询云原生构建设置。Get cloud native build settings.
//
// 访问令牌权限: repo-manage:r
//
// CNB API: GET /{repo}/-/settings/cloud-native-build
func (s *GitSettingsService) GetPipelineSettings(ctx context.Context, repo string) (*PipelineSettings, *Response, error) {
	u := escapePath("/%s/-/settings/cloud-native-build", repo)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out PipelineSettings
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// PutPipelineSettings 更新云原生构建设置。Update cloud native build settings.
//
// 访问令牌权限: repo-manage:rw
//
// CNB API: PUT /{repo}/-/settings/cloud-native-build
func (s *GitSettingsService) PutPipelineSettings(ctx context.Context, repo string, body PipelineSettings) (*Response, error) {
	u := escapePath("/%s/-/settings/cloud-native-build", repo)
	req, err := s.client.NewRequest(http.MethodPut, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// GetPullRequestSettings 查询合并请求设置。Get pull request settings.
//
// 访问令牌权限: repo-manage:r
//
// CNB API: GET /{repo}/-/settings/pull-request
func (s *GitSettingsService) GetPullRequestSettings(ctx context.Context, repo string) (*PullRequestSettings, *Response, error) {
	u := escapePath("/%s/-/settings/pull-request", repo)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out PullRequestSettings
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// PutPullRequestSettings 更新合并请求设置。Update pull request settings.
//
// 访问令牌权限: repo-manage:rw
//
// CNB API: PUT /{repo}/-/settings/pull-request
func (s *GitSettingsService) PutPullRequestSettings(ctx context.Context, repo string, body PullRequestSettings) (*Response, error) {
	u := escapePath("/%s/-/settings/pull-request", repo)
	req, err := s.client.NewRequest(http.MethodPut, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// GetPushLimitSettings 查询推送管控设置。Get push control settings.
//
// 访问令牌权限: repo-manage:r
//
// CNB API: GET /{repo}/-/settings/push-limit
func (s *GitSettingsService) GetPushLimitSettings(ctx context.Context, repo string) (*PushLimitSettings, *Response, error) {
	u := escapePath("/%s/-/settings/push-limit", repo)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out PushLimitSettings
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// PutPushLimitSettings 设置推送管控。Set push control.
//
// 访问令牌权限: repo-manage:rw
//
// CNB API: PUT /{repo}/-/settings/push-limit
func (s *GitSettingsService) PutPushLimitSettings(ctx context.Context, repo string, body PushLimitSettings) (*Response, error) {
	u := escapePath("/%s/-/settings/push-limit", repo)
	req, err := s.client.NewRequest(http.MethodPut, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}
