// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// ListUserIssues 查询我的 Issue 列表。List my issues.
//
// 访问令牌权限: repo-issue:r
//
// CNB API: GET /user/issues
func (s *IssuesService) ListUserIssues(ctx context.Context, opts *ListUserIssuesOptions) ([]*UserIssue, *Response, error) {
	u := escapePath("/user/issues")
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*UserIssue
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// GetIssueFiles 获取 Issue 文件。Get issue files.
//
// 访问令牌权限: repo-issue:r
//
// CNB API: GET /{repo}/-/files/issues/{file_path}
func (s *IssuesService) GetIssueFiles(ctx context.Context, repo string, filePath string) (*Response, error) {
	u := escapePath("/%s/-/files/issues/%s", repo, filePath)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// GetIssueImgs 获取 Issue 图片。Get issue images.
//
// 访问令牌权限: repo-issue:r
//
// CNB API: GET /{repo}/-/imgs/issues/{img_path}
func (s *IssuesService) GetIssueImgs(ctx context.Context, repo string, imgPath string) (*Response, error) {
	u := escapePath("/%s/-/imgs/issues/%s", repo, imgPath)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// ListIssues 查询仓库 Issue 列表。List repository issues.
//
// 访问令牌权限: repo-issue:r
//
// CNB API: GET /{repo}/-/issues
func (s *IssuesService) ListIssues(ctx context.Context, repo string, opts *ListIssuesOptions) ([]*Issue, *Response, error) {
	u := escapePath("/%s/-/issues", repo)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*Issue
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// CreateIssue 创建 Issue。Create issue.
//
// 访问令牌权限: repo-issue:rw
//
// CNB API: POST /{repo}/-/issues
func (s *IssuesService) CreateIssue(ctx context.Context, repo string, body PostIssueForm) (*IssueDetail, *Response, error) {
	u := escapePath("/%s/-/issues", repo)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out IssueDetail
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// PostAssetGroup 创建 Issue 附件组。Create issue asset group.
//
// 访问令牌权限: repo-issue:rw
//
// CNB API: POST /{repo}/-/issues/asset-groups
func (s *IssuesService) PostAssetGroup(ctx context.Context, repo string, body PostAssetGroupForm) (*AssetGroup, *Response, error) {
	u := escapePath("/%s/-/issues/asset-groups", repo)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out AssetGroup
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// PostIssueFileAssetUploadURL 创建附件组文件上传链接。Create asset group file upload URL.
//
// 访问令牌权限: repo-issue:rw
//
// CNB API: POST /{repo}/-/issues/asset-groups/{asset_group_id}/file-asset-upload-url
func (s *IssuesService) PostIssueFileAssetUploadURL(ctx context.Context, repo string, assetGroupId string, body PostIssueAssetUploadURLForm) (*IssueAssetUploadURL, *Response, error) {
	u := escapePath("/%s/-/issues/asset-groups/%s/file-asset-upload-url", repo, assetGroupId)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out IssueAssetUploadURL
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// PostIssueImageAssetUploadURL 创建附件组图片上传链接。Create asset group image upload URL.
//
// 访问令牌权限: repo-issue:rw
//
// CNB API: POST /{repo}/-/issues/asset-groups/{asset_group_id}/image-asset-upload-url
func (s *IssuesService) PostIssueImageAssetUploadURL(ctx context.Context, repo string, assetGroupId string, body PostIssueAssetUploadURLForm) (*IssueAssetUploadURL, *Response, error) {
	u := escapePath("/%s/-/issues/asset-groups/%s/image-asset-upload-url", repo, assetGroupId)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out IssueAssetUploadURL
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetIssue 获取 Issue。Get issue.
//
// 访问令牌权限: repo-issue:r
//
// CNB API: GET /{repo}/-/issues/{number}
func (s *IssuesService) GetIssue(ctx context.Context, repo string, number int) (*IssueDetail, *Response, error) {
	u := escapePath("/%s/-/issues/%d", repo, number)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out IssueDetail
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// UpdateIssue 更新 Issue。Update issue.
//
// 访问令牌权限: repo-issue:rw
//
// CNB API: PATCH /{repo}/-/issues/{number}
func (s *IssuesService) UpdateIssue(ctx context.Context, repo string, number int, body PatchIssueForm) (*IssueDetail, *Response, error) {
	u := escapePath("/%s/-/issues/%d", repo, number)
	req, err := s.client.NewRequest(http.MethodPatch, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out IssueDetail
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// ListIssueActivities 查询 Issue 动态。List issue activities.
//
// 访问令牌权限: repo-issue:r
//
// CNB API: GET /{repo}/-/issues/{number}/activities
func (s *IssuesService) ListIssueActivities(ctx context.Context, repo string, number int, opts *ListIssueActivitiesOptions) ([]*IssueActivity, *Response, error) {
	u := escapePath("/%s/-/issues/%d/activities", repo, number)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*IssueActivity
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// ListIssueActivitiesLatest 查询 Issue 最新动态。Get latest issue activity.
//
// 访问令牌权限: repo-issue:r
//
// CNB API: GET /{repo}/-/issues/{number}/activities/latest/{id}
func (s *IssuesService) ListIssueActivitiesLatest(ctx context.Context, repo string, number int, id int) ([]*IssueActivity, *Response, error) {
	u := escapePath("/%s/-/issues/%d/activities/latest/%d", repo, number, id)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*IssueActivity
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// ListIssueAssignees 查询 Issue 处理人。List issue assignees.
//
// 访问令牌权限: repo-issue:r
//
// CNB API: GET /{repo}/-/issues/{number}/assignees
func (s *IssuesService) ListIssueAssignees(ctx context.Context, repo string, number string) ([]*UserInfo, *Response, error) {
	u := escapePath("/%s/-/issues/%s/assignees", repo, number)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*UserInfo
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// PostIssueAssignees 添加 Issue 处理人。Add issue assignees.
//
// 访问令牌权限: repo-issue:rw
//
// CNB API: POST /{repo}/-/issues/{number}/assignees
func (s *IssuesService) PostIssueAssignees(ctx context.Context, repo string, number string, body PostIssueAssigneesForm) (*IssueDetail, *Response, error) {
	u := escapePath("/%s/-/issues/%s/assignees", repo, number)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out IssueDetail
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// DeleteIssueAssignees 移除 Issue 处理人。Remove issue assignee.
//
// 访问令牌权限: repo-issue:rw
//
// CNB API: DELETE /{repo}/-/issues/{number}/assignees
func (s *IssuesService) DeleteIssueAssignees(ctx context.Context, repo string, number string, body DeleteIssueAssigneesForm) (*IssueDetail, *Response, error) {
	u := escapePath("/%s/-/issues/%s/assignees", repo, number)
	req, err := s.client.NewRequest(http.MethodDelete, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out IssueDetail
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// PatchIssueAssignees 更新 Issue 处理人。Update issue assignees.
//
// 访问令牌权限: repo-issue:rw
//
// CNB API: PATCH /{repo}/-/issues/{number}/assignees
func (s *IssuesService) PatchIssueAssignees(ctx context.Context, repo string, number string, body PatchIssueAssigneesForm) (*IssueDetail, *Response, error) {
	u := escapePath("/%s/-/issues/%s/assignees", repo, number)
	req, err := s.client.NewRequest(http.MethodPatch, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out IssueDetail
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// CanUserBeAssignedToIssue 检查用户可分配性。Check user assignability.
//
// 访问令牌权限: repo-issue:r
//
// CNB API: GET /{repo}/-/issues/{number}/assignees/{assignee}
func (s *IssuesService) CanUserBeAssignedToIssue(ctx context.Context, repo string, number string, assignee string) (*Response, error) {
	u := escapePath("/%s/-/issues/%s/assignees/%s", repo, number, assignee)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// PostIssueCommentFileAssetUploadURL 创建 Issue 评论文件上传链接。Create issue comment file upload URL.
//
// 访问令牌权限: repo-notes:rw
//
// CNB API: POST /{repo}/-/issues/{number}/comment-file-asset-upload-url
func (s *IssuesService) PostIssueCommentFileAssetUploadURL(ctx context.Context, repo string, number int, body PostIssueAssetUploadURLForm) (*IssueAssetUploadURL, *Response, error) {
	u := escapePath("/%s/-/issues/%d/comment-file-asset-upload-url", repo, number)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out IssueAssetUploadURL
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// PostIssueCommentImageAssetUploadURL Issue 评论图片上传链接。Create comment image upload URL.
//
// 访问令牌权限: repo-notes:rw
//
// CNB API: POST /{repo}/-/issues/{number}/comment-image-asset-upload-url
func (s *IssuesService) PostIssueCommentImageAssetUploadURL(ctx context.Context, repo string, number int, body PostIssueAssetUploadURLForm) (*IssueAssetUploadURL, *Response, error) {
	u := escapePath("/%s/-/issues/%d/comment-image-asset-upload-url", repo, number)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out IssueAssetUploadURL
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// ListIssueComments 查询 Issue 评论。List issue comments.
//
// 访问令牌权限: repo-notes:r
//
// CNB API: GET /{repo}/-/issues/{number}/comments
func (s *IssuesService) ListIssueComments(ctx context.Context, repo string, number int, opts *ListIssueCommentsOptions) ([]*IssueComment, *Response, error) {
	u := escapePath("/%s/-/issues/%d/comments", repo, number)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*IssueComment
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// PostIssueComment 创建 Issue 评论。Create issue comment.
//
// 访问令牌权限: repo-notes:rw
//
// CNB API: POST /{repo}/-/issues/{number}/comments
func (s *IssuesService) PostIssueComment(ctx context.Context, repo string, number int, body PostIssueCommentForm) (*IssueComment, *Response, error) {
	u := escapePath("/%s/-/issues/%d/comments", repo, number)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out IssueComment
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetIssueComment 查询 Issue 评论。List issue comments.
//
// 访问令牌权限: repo-notes:r
//
// CNB API: GET /{repo}/-/issues/{number}/comments/{comment_id}
func (s *IssuesService) GetIssueComment(ctx context.Context, repo string, number int, commentId int) (*IssueComment, *Response, error) {
	u := escapePath("/%s/-/issues/%d/comments/%d", repo, number, commentId)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out IssueComment
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// PatchIssueComment 更新 Issue 评论。Update issue comment.
//
// 访问令牌权限: repo-notes:rw
//
// CNB API: PATCH /{repo}/-/issues/{number}/comments/{comment_id}
func (s *IssuesService) PatchIssueComment(ctx context.Context, repo string, number int, commentId int, body PatchIssueCommentForm) (*IssueComment, *Response, error) {
	u := escapePath("/%s/-/issues/%d/comments/%d", repo, number, commentId)
	req, err := s.client.NewRequest(http.MethodPatch, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out IssueComment
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// ListIssueLabels 查询 Issue 标签。List issue labels.
//
// 访问令牌权限: repo-issue:r
//
// CNB API: GET /{repo}/-/issues/{number}/labels
func (s *IssuesService) ListIssueLabels(ctx context.Context, repo string, number int, opts *ListIssueLabelsOptions) ([]*Label, *Response, error) {
	u := escapePath("/%s/-/issues/%d/labels", repo, number)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*Label
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// PutIssueLabels 设置 Issue 标签。Set issue labels.
//
// 访问令牌权限: repo-issue:rw
//
// CNB API: PUT /{repo}/-/issues/{number}/labels
func (s *IssuesService) PutIssueLabels(ctx context.Context, repo string, number int, body PutIssueLabelsForm) (*Label, *Response, error) {
	u := escapePath("/%s/-/issues/%d/labels", repo, number)
	req, err := s.client.NewRequest(http.MethodPut, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out Label
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// PostIssueLabels 添加 Issue 标签。Add issue labels.
//
// 访问令牌权限: repo-issue:rw
//
// CNB API: POST /{repo}/-/issues/{number}/labels
func (s *IssuesService) PostIssueLabels(ctx context.Context, repo string, number int, body PostIssueLabelsForm) (*Label, *Response, error) {
	u := escapePath("/%s/-/issues/%d/labels", repo, number)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out Label
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// DeleteIssueLabels 删除 Issue 标签。Delete issue labels.
//
// 访问令牌权限: repo-issue:rw
//
// CNB API: DELETE /{repo}/-/issues/{number}/labels
func (s *IssuesService) DeleteIssueLabels(ctx context.Context, repo string, number int) (*Response, error) {
	u := escapePath("/%s/-/issues/%d/labels", repo, number)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// DeleteIssueLabel 移除 Issue 标签。Remove issue label.
//
// 访问令牌权限: repo-issue:rw
//
// CNB API: DELETE /{repo}/-/issues/{number}/labels/{name}
func (s *IssuesService) DeleteIssueLabel(ctx context.Context, repo string, number int, name string) (*Label, *Response, error) {
	u := escapePath("/%s/-/issues/%d/labels/%s", repo, number, name)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out Label
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetIssueProperties 获取 Issue 自定义属性。Get issue custom properties.
//
// 访问令牌权限: repo-issue:r
//
// CNB API: GET /{repo}/-/issues/{number}/property
func (s *IssuesService) GetIssueProperties(ctx context.Context, repo string, number int) ([]*IssueProperty, *Response, error) {
	u := escapePath("/%s/-/issues/%d/property", repo, number)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*IssueProperty
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// UpdateIssueProperties 更新 Issue 属性。Update issue properties.
//
// 访问令牌权限: repo-issue:rw
//
// CNB API: PATCH /{repo}/-/issues/{number}/property
func (s *IssuesService) UpdateIssueProperties(ctx context.Context, repo string, number int, body IssuePropertiesForm) (*IssuePropertyUpdateResult, *Response, error) {
	u := escapePath("/%s/-/issues/%d/property", repo, number)
	req, err := s.client.NewRequest(http.MethodPatch, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out IssuePropertyUpdateResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// ListRepoVisibleProperties 查询仓库可见自定义属性。Get repository visible custom properties.
//
// 访问令牌权限: repo-issue:r
//
// CNB API: GET /{repo}/-/property
func (s *IssuesService) ListRepoVisibleProperties(ctx context.Context, repo string) ([]*RepoProperty, *Response, error) {
	u := escapePath("/%s/-/property", repo)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*RepoProperty
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// ListRepoInvisibleProperties 查询仓库隐藏自定义属性。Get hidden custom properties.
//
// 访问令牌权限: repo-issue:r
//
// CNB API: GET /{repo}/-/property/invisible
func (s *IssuesService) ListRepoInvisibleProperties(ctx context.Context, repo string, opts *ListRepoInvisiblePropertiesOptions) ([]*RepoProperty, *Response, error) {
	u := escapePath("/%s/-/property/invisible", repo)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*RepoProperty
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
