// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// SearchNpc 搜索 NPC 角色。Search NPC characters.
//
// 访问令牌权限: repo-basic-info:r, repo-code:r
//
// CNB API: GET /search/npc
func (s *KnowledgeBaseService) SearchNpc(ctx context.Context, opts *SearchNpcOptions) ([]*SearchNpcRes, *Response, error) {
	u := escapePath("/search/npc")
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*SearchNpcRes
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// GetKnowledgeBaseInfo 获取知识库信息。Get knowledge base info.
//
// 访问令牌权限: repo-code:r
//
// CNB API: GET /{repo}/-/knowledge/base
func (s *KnowledgeBaseService) GetKnowledgeBaseInfo(ctx context.Context, repo string) (*KnowledgeBaseInfoRes, *Response, error) {
	u := escapePath("/%s/-/knowledge/base", repo)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out KnowledgeBaseInfoRes
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// DeleteKnowledgeBase 删除知识库。Delete knowledge base.
//
// 访问令牌权限: repo-code:rw
//
// CNB API: DELETE /{repo}/-/knowledge/base
func (s *KnowledgeBaseService) DeleteKnowledgeBase(ctx context.Context, repo string) (*Response, error) {
	u := escapePath("/%s/-/knowledge/base", repo)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// QueryKnowledgeBaseGet 查询知识库。Query knowledge base.
//
// 访问令牌权限: repo-code:r
//
// CNB API: GET /{repo}/-/knowledge/base/query
func (s *KnowledgeBaseService) QueryKnowledgeBaseGet(ctx context.Context, repo string, opts *QueryKnowledgeBaseGetOptions) ([]*QueryKnowledgeBaseRes, *Response, error) {
	u := escapePath("/%s/-/knowledge/base/query", repo)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*QueryKnowledgeBaseRes
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// QueryKnowledgeBase 查询知识库（已废弃）。Query knowledge base (deprecated).
//
// 访问令牌权限: repo-code:r
//
// CNB API: POST /{repo}/-/knowledge/base/query
func (s *KnowledgeBaseService) QueryKnowledgeBase(ctx context.Context, repo string, body QueryKnowledgeBaseReq) ([]*QueryKnowledgeBaseRes, *Response, error) {
	u := escapePath("/%s/-/knowledge/base/query", repo)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out []*QueryKnowledgeBaseRes
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// GetModels 获取 Embedding 模型。List embedding models.
//
// 访问令牌权限: repo-code:r
//
// CNB API: GET /{repo}/-/knowledge/embedding/models
func (s *KnowledgeBaseService) GetModels(ctx context.Context, repo string) ([]*EmbeddingModel, *Response, error) {
	u := escapePath("/%s/-/knowledge/embedding/models", repo)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*EmbeddingModel
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
