// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// ListInheritMembersOfGroup 获取继承成员。List inherited members.
//
// 访问令牌权限: group-manage:r
//
// CNB API: GET /{group}/-/inherit-members
func (s *MembersService) ListInheritMembersOfGroup(ctx context.Context, group string, opts *ListInheritMembersOfGroupOptions) ([]*ListInheritMembers, *Response, error) {
	u := escapePath("/%s/-/inherit-members", group)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*ListInheritMembers
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// ListMembersOfGroup 获取组织直接成员列表。List organization direct members.
//
// 访问令牌权限: group-manage:r
//
// CNB API: GET /{group}/-/members
func (s *MembersService) ListMembersOfGroup(ctx context.Context, group string, opts *ListMembersOfGroupOptions) ([]*UsersWithAccessLevelInSlug, *Response, error) {
	u := escapePath("/%s/-/members", group)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*UsersWithAccessLevelInSlug
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// GetMemberAccessLevelOfGroup 获取访问成员权限。Get access member permissions.
//
// 访问令牌权限: group-manage:r
//
// CNB API: GET /{group}/-/members/access-level
func (s *MembersService) GetMemberAccessLevelOfGroup(ctx context.Context, group string, opts *GetMemberAccessLevelOfGroupOptions) (*MemberAccessLevelInSlugUnion, *Response, error) {
	u := escapePath("/%s/-/members/access-level", group)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out MemberAccessLevelInSlugUnion
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// UpdateMembersOfGroup 更新组织成员权限。Update member permission.
//
// 访问令牌权限: group-manage:rw
//
// CNB API: PUT /{group}/-/members/{username}
func (s *MembersService) UpdateMembersOfGroup(ctx context.Context, group string, username string, body UpdateMembersRequest) (*Response, error) {
	u := escapePath("/%s/-/members/%s", group, username)
	req, err := s.client.NewRequest(http.MethodPut, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// AddMembersOfGroup 添加成员。Add members.
//
// 访问令牌权限: group-manage:rw
//
// CNB API: POST /{group}/-/members/{username}
func (s *MembersService) AddMembersOfGroup(ctx context.Context, group string, username string, body UpdateMembersRequest) (*Response, error) {
	u := escapePath("/%s/-/members/%s", group, username)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// DeleteMembersOfGroup 移除组织直接成员。Remove organization direct member.
//
// 访问令牌权限: group-manage:rw
//
// CNB API: DELETE /{group}/-/members/{username}
func (s *MembersService) DeleteMembersOfGroup(ctx context.Context, group string, username string) (*Response, error) {
	u := escapePath("/%s/-/members/%s", group, username)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// ListMemberAccessLevelOfGroup 获取成员权限。Get member permissions.
//
// 访问令牌权限: group-manage:r
//
// CNB API: GET /{group}/-/members/{username}/access-level
func (s *MembersService) ListMemberAccessLevelOfGroup(ctx context.Context, group string, username string) ([]*MemberAccessLevel, *Response, error) {
	u := escapePath("/%s/-/members/%s/access-level", group, username)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*MemberAccessLevel
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// AddMembersOfMission 添加成员。Add members.
//
// 访问令牌权限: mission-manage:rw
//
// CNB API: POST /{mission}/-/members/{username}
func (s *MembersService) AddMembersOfMission(ctx context.Context, mission string, username string, body UpdateMembersRequest) (*Response, error) {
	u := escapePath("/%s/-/members/%s", mission, username)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// AddMembersOfRegistry 添加成员。Add members.
//
// 访问令牌权限: registry-manage:rw
//
// CNB API: POST /{registry}/-/members/{username}
func (s *MembersService) AddMembersOfRegistry(ctx context.Context, registry string, username string, body UpdateMembersRequest) (*Response, error) {
	u := escapePath("/%s/-/members/%s", registry, username)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// ListInheritMembersOfRepo 获取继承成员。List inherited members.
//
// 访问令牌权限: repo-manage:r
//
// CNB API: GET /{repo}/-/inherit-members
func (s *MembersService) ListInheritMembersOfRepo(ctx context.Context, repo string, opts *ListInheritMembersOfRepoOptions) ([]*ListInheritMembers, *Response, error) {
	u := escapePath("/%s/-/inherit-members", repo)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*ListInheritMembers
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// ListMembersOfRepo 获取仓库直接成员列表。List repository direct members.
//
// 访问令牌权限: repo-manage:r
//
// CNB API: GET /{repo}/-/members
func (s *MembersService) ListMembersOfRepo(ctx context.Context, repo string, opts *ListMembersOfRepoOptions) ([]*UsersWithAccessLevelInSlug, *Response, error) {
	u := escapePath("/%s/-/members", repo)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*UsersWithAccessLevelInSlug
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// GetMemberAccessLevelOfRepo 获取成员访问权限。Get member access level.
//
// 访问令牌权限: repo-manage:r
//
// CNB API: GET /{repo}/-/members/access-level
func (s *MembersService) GetMemberAccessLevelOfRepo(ctx context.Context, repo string, opts *GetMemberAccessLevelOfRepoOptions) (*MemberAccessLevelInSlugUnion, *Response, error) {
	u := escapePath("/%s/-/members/access-level", repo)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out MemberAccessLevelInSlugUnion
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// UpdateMembersOfRepo 更新仓库成员权限。Update repository member permission.
//
// 访问令牌权限: repo-manage:rw
//
// CNB API: PUT /{repo}/-/members/{username}
func (s *MembersService) UpdateMembersOfRepo(ctx context.Context, repo string, username string, body UpdateMembersRequest) (*Response, error) {
	u := escapePath("/%s/-/members/%s", repo, username)
	req, err := s.client.NewRequest(http.MethodPut, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// AddMembersOfRepo 添加成员。Add members.
//
// 访问令牌权限: repo-manage:rw
//
// CNB API: POST /{repo}/-/members/{username}
func (s *MembersService) AddMembersOfRepo(ctx context.Context, repo string, username string, body UpdateMembersRequest) (*Response, error) {
	u := escapePath("/%s/-/members/%s", repo, username)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// DeleteMembersOfRepo 删除仓库成员。Remove repo member.
//
// 访问令牌权限: repo-manage:rw
//
// CNB API: DELETE /{repo}/-/members/{username}
func (s *MembersService) DeleteMembersOfRepo(ctx context.Context, repo string, username string) (*Response, error) {
	u := escapePath("/%s/-/members/%s", repo, username)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// ListMemberAccessLevelOfRepo 获取仓库成员权限。Get repository member permission.
//
// 访问令牌权限: repo-manage:r
//
// CNB API: GET /{repo}/-/members/{username}/access-level
func (s *MembersService) ListMemberAccessLevelOfRepo(ctx context.Context, repo string, username string) ([]*MemberAccessLevel, *Response, error) {
	u := escapePath("/%s/-/members/%s/access-level", repo, username)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*MemberAccessLevel
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// ListAllMembers 获取仓库有效成员列表。List repository active members.
//
// 访问令牌权限: repo-manage:r
//
// CNB API: GET /{slug}/-/list-members
func (s *MembersService) ListAllMembers(ctx context.Context, slug string, opts *ListAllMembersOptions) ([]*UsersWithAccessLevelInSlug, *Response, error) {
	u := escapePath("/%s/-/list-members", slug)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*UsersWithAccessLevelInSlug
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// ListOutsideCollaborators 获取外部贡献者。List external contributors.
//
// 访问令牌权限: repo-manage:r
//
// CNB API: GET /{slug}/-/outside-collaborators
func (s *MembersService) ListOutsideCollaborators(ctx context.Context, slug string, opts *ListOutsideCollaboratorsOptions) ([]*OutsideCollaboratorInRepo, *Response, error) {
	u := escapePath("/%s/-/outside-collaborators", slug)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*OutsideCollaboratorInRepo
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// UpdateOutsideCollaborators 更新外部贡献者权限。Update contributor permission.
//
// 访问令牌权限: repo-manage:rw
//
// CNB API: PUT /{slug}/-/outside-collaborators/{username}
func (s *MembersService) UpdateOutsideCollaborators(ctx context.Context, slug string, username string, opts *UpdateOutsideCollaboratorsOptions) (*Response, error) {
	u := escapePath("/%s/-/outside-collaborators/%s", slug, username)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodPut, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// DeleteOutsideCollaborators 删除外部贡献者。Remove external contributors.
//
// 访问令牌权限: repo-manage:rw
//
// CNB API: DELETE /{slug}/-/outside-collaborators/{username}
func (s *MembersService) DeleteOutsideCollaborators(ctx context.Context, slug string, username string) (*Response, error) {
	u := escapePath("/%s/-/outside-collaborators/%s", slug, username)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}
