// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// DeleteMission 删除指定任务集。Delete the specified mission.
//
// 访问令牌权限: mission-delete:rw
//
// CNB API: DELETE /{mission}
func (s *MissionsService) DeleteMission(ctx context.Context, mission string) (*Response, error) {
	u := escapePath("/%s", mission)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// GetMissionViewConfig 查询任务集视图配置信息。Get mission view config.
//
// 访问令牌权限: mission-manage:r
//
// CNB API: GET /{mission}/-/mission/view
func (s *MissionsService) GetMissionViewConfig(ctx context.Context, mission string, opts *GetMissionViewConfigOptions) (*MissionViewConfig, *Response, error) {
	u := escapePath("/%s/-/mission/view", mission)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out MissionViewConfig
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// PostMissionViewConfig 设置任务集视图配置信息。Set mission view config.
//
// 访问令牌权限: mission-manage:rw
//
// CNB API: POST /{mission}/-/mission/view
func (s *MissionsService) PostMissionViewConfig(ctx context.Context, mission string, body MissionViewConfig) (*Response, error) {
	u := escapePath("/%s/-/mission/view", mission)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// GetMissionViewList 获取任务集视图列表。Get view list of a mission.
//
// 访问令牌权限: mission-manage:r
//
// CNB API: GET /{mission}/-/mission/view-list
func (s *MissionsService) GetMissionViewList(ctx context.Context, mission string) ([]*MissionView, *Response, error) {
	u := escapePath("/%s/-/mission/view-list", mission)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*MissionView
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// PutMissionViewList 更新任务集视图。Update mission view.
//
// 访问令牌权限: mission-manage:rw
//
// CNB API: PUT /{mission}/-/mission/view-list
func (s *MissionsService) PutMissionViewList(ctx context.Context, mission string, body MissionView) (*Response, error) {
	u := escapePath("/%s/-/mission/view-list", mission)
	req, err := s.client.NewRequest(http.MethodPut, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// PostMissionViewList 排序任务集视图。Sort mission view list.
//
// 访问令牌权限: mission-manage:rw
//
// CNB API: POST /{mission}/-/mission/view-list
func (s *MissionsService) PostMissionViewList(ctx context.Context, mission string, body MissionPostViewReq) (*Response, error) {
	u := escapePath("/%s/-/mission/view-list", mission)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// GetGroupSubMissions 查询我的任务集。List my missions.
//
// 访问令牌权限: group-resource:r
//
// CNB API: GET /{slug}/-/missions
func (s *MissionsService) GetGroupSubMissions(ctx context.Context, slug string, opts *GetGroupSubMissionsOptions) ([]*Missions4User, *Response, error) {
	u := escapePath("/%s/-/missions", slug)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*Missions4User
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// CreateMission 创建任务集。Create a mission.
//
// 访问令牌权限: group-resource:rw
//
// CNB API: POST /{slug}/-/missions
func (s *MissionsService) CreateMission(ctx context.Context, slug string, body CreateMissionReq) (*Response, error) {
	u := escapePath("/%s/-/missions", slug)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}
