// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// ListMissionFieldsOpenAPI 获取任务集属性。Get mission fields.
//
// 访问令牌权限: mission-manage:r
//
// CNB API: GET /{mission}/-/mission-resource/fields
func (s *MissionResourcesService) ListMissionFieldsOpenAPI(ctx context.Context, mission string, opts *ListMissionFieldsOpenAPIOptions) ([]*MissionField, *Response, error) {
	u := escapePath("/%s/-/mission-resource/fields", mission)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*MissionField
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// ListMissionResourcesOpenAPI 查询任务集资源列表。Query mission resources.
//
// 访问令牌权限: mission-manage:r
//
// CNB API: POST /{mission}/-/mission-resource/resources
func (s *MissionResourcesService) ListMissionResourcesOpenAPI(ctx context.Context, mission string, opts *ListMissionResourcesOpenAPIOptions, body MissionFilterFrom) (*MissionResources, *Response, error) {
	u := escapePath("/%s/-/mission-resource/resources", mission)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out MissionResources
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}
