// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

type RepoDisplayModule struct {
	// Activity 仓库动态。Repository activity.
	Activity bool `json:"activity"`
	// Contributors 仓库贡献者。Repository contributors.
	Contributors bool `json:"contributors"`
	// Release 仓库版本。Repository releases.
	Release bool `json:"release"`
}
