// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

type CommitAssetUploadURL struct {
	// ExpiresInSec URL过期时间，单位为秒。URL expiration time in seconds.
	ExpiresInSec int `json:"expires_in_sec"`
	// UploadUrl 附件上传URL。Attachment upload URL.
	UploadUrl string `json:"upload_url"`
	// VerifyUrl 附件上传确认URL。Attachment upload confirmation URL.
	VerifyUrl string `json:"verify_url"`
}

type CreateBranchForm struct {
	// Name 新分支的名称。New branch name.
	Name *string `json:"name,omitempty"`
	// StartPoint 新分支的起始点。格式：`分支名称`,`提交哈希`,`标签名称`。New branch starting point. Format: `branch_name`,`commit_hash`,`tag_name`.
	StartPoint *string `json:"start_point,omitempty"`
}

type HeadRef struct {
	// Name 分支名称。Branch name.
	Name string `json:"name"`
	// Protected 分支是否是保护分支。Whether the branch is protected.
	Protected bool `json:"protected"`
}

type IssuePropertiesForm struct {
	// Properties Issue自定义属性列表。
	Properties []PropertyForm `json:"properties,omitempty"`
}

type PatchReleaseForm struct {
	// Body 版本描述。Release description.
	Body *string `json:"body,omitempty"`
	// Draft 是否为草稿版本。Whether this is a draft release.
	Draft *bool `json:"draft,omitempty"`
	// MakeLatest 是否设置为最新版本。可选值：`true`,`false`,`legacy`
	MakeLatest *string `json:"make_latest,omitempty"`
	// Name 版本标题。Release title.
	Name *string `json:"name,omitempty"`
	// Prerelease 是否为预发布版本。Whether this is a pre-release.
	Prerelease *bool `json:"prerelease,omitempty"`
}

type PostCommitAssetUploadURLForm struct {
	// AssetName 附件名称。Attachment name.
	AssetName *string `json:"asset_name,omitempty"`
	// Size 附件大小，单位为字节。 Attachment size, in bytes.
	Size *int `json:"size,omitempty"`
	// Ttl 附件存在时间，单位为天。Attachment retention time in days.
	Ttl *int `json:"ttl,omitempty"`
}

type PostReleaseAssetUploadURLForm struct {
	// AssetName 附件名称。Attachment name.
	AssetName *string `json:"asset_name,omitempty"`
	// Overwrite 是否覆盖同名附件。Whether to overwrite attachments with the same name.
	Overwrite *bool `json:"overwrite,omitempty"`
	// Size 附件大小，单位为字节。Attachment size in bytes.
	Size *int `json:"size,omitempty"`
	// Ttl 附件存在时间，单位为天。Attachment retention time in days.
	Ttl *int `json:"ttl,omitempty"`
}

type PostReleaseForm struct {
	// Body 版本描述。Release description.
	Body *string `json:"body,omitempty"`
	// Draft 是否为草稿版本。Whether this is a draft release.
	Draft *bool `json:"draft,omitempty"`
	// MakeLatest 是否设置为最新版本。可选值：`true`,`false`,`legacy`
	MakeLatest *string `json:"make_latest,omitempty"`
	// Name 版本标题。Release title.
	Name *string `json:"name,omitempty"`
	// Prerelease 是否为预发布版本。Whether this is a pre-release.
	Prerelease *bool `json:"prerelease,omitempty"`
	// TagName 标签名称。Tag name.
	TagName *string `json:"tag_name,omitempty"`
	// TargetCommitish 目标提交哈希或分支名称。Target commit hash or branch name.
	TargetCommitish *string `json:"target_commitish,omitempty"`
}

type PropertyForm struct {
	// Key Issue自定义属性键名。Custom property key.
	Key *string `json:"key,omitempty"`
	// Value Issue自定义属性值。Custom property value.
	Value *string `json:"value,omitempty"`
}

type PutCommitAnnotation struct {
	// Key 元数据键名。Metadata key.
	Key *string `json:"key,omitempty"`
	// Value 元数据值。Metadata value.
	Value *string `json:"value,omitempty"`
}

type PutCommitAnnotationsForm struct {
	// Annotations 提交元数据列表。Commit metadata list.
	Annotations []PutCommitAnnotation `json:"annotations,omitempty"`
}

type PutTagAnnotation struct {
	// Key 标签元数据的键名。Tag metadata key.
	Key *string `json:"key,omitempty"`
	// Value 标签元数据的值。Tag metadata value.
	Value *string `json:"value,omitempty"`
}

type PutTagAnnotationsForm struct {
	// Annotations 设置tag元数据列表信息。
	Annotations []PutTagAnnotation `json:"annotations,omitempty"`
}

type ReleaseAssetUploadURL struct {
	// ExpiresInSec URL过期时间，单位为秒。URL expiration time in seconds.
	ExpiresInSec int `json:"expires_in_sec"`
	// UploadUrl 附件上传URL。Attachment upload URL.
	UploadUrl string `json:"upload_url"`
	// VerifyUrl 附件上传确认验证URL。Attachment upload confirmation verification URL.
	VerifyUrl string `json:"verify_url"`
}
