// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import "encoding/json"

type AssetGroup struct {
	AssetGroupId    string                `json:"asset_group_id"`
	FileUploadUrls  []IssueAssetUploadURL `json:"file_upload_urls"`
	ImageUploadUrls []IssueAssetUploadURL `json:"image_upload_urls"`
}

type Author struct {
	// Email 用户邮箱。User email.
	Email string `json:"email"`
	// UserName 用户名。Username.
	UserName string `json:"user_name"`
}

type Blob struct {
	// Sha 提交的哈希值。Commit hash.
	Sha string `json:"sha"`
}

type Branch struct {
	// Commit 分支指向的最新提交信息。Latest commit information for the branch.
	Commit map[string]any `json:"commit"`
	// Locked 分支是否被锁定。Whether the branch is locked.
	Locked bool `json:"locked"`
	// Name 分支名称。Branch name.
	Name string `json:"name"`
	// Protected 分支是否是保护分支。Whether the branch is protected.
	Protected bool `json:"protected"`
}

type BranchDetail struct {
	// Commit 分支指向的最新提交信息。Latest commit of the branch.
	Commit Commit `json:"commit"`
	// Locked 分支是否被锁定。Whether the branch is locked.
	Locked bool `json:"locked"`
	// Name 分支名称。Branch name.
	Name string `json:"name"`
	// Protected 分支是否是保护分支。Whether the branch is protected.
	Protected bool `json:"protected"`
}

type BranchProtection struct {
	// AllowCreation 是否允许所有人创建保护分支。Whether all users can create protected branches.
	AllowCreation *bool `json:"allow_creation,omitempty"`
	// AllowDeletions 是否允许所有人删除保护分支。Whether all users can delete protected branches.
	AllowDeletions *bool `json:"allow_deletions,omitempty"`
	// AllowForcePushes 是否允许所有人强制推送。Whether all users can force push.
	AllowForcePushes *bool `json:"allow_force_pushes,omitempty"`
	// AllowMasterCreation 是否仅允许仓库管理员及负责人创建保护分支。Only admins/owners can create protected branches.
	AllowMasterCreation *bool `json:"allow_master_creation,omitempty"`
	// AllowMasterDeletions 是否仅允许仓库管理员及负责人删除保护分支。Only admins/owners can delete protected branches.
	AllowMasterDeletions *bool `json:"allow_master_deletions,omitempty"`
	// AllowMasterForcePushes 是否仅允许仓库管理员及负责人强制推送。Whether only repo admins and owners can force push.
	AllowMasterForcePushes *bool `json:"allow_master_force_pushes,omitempty"`
	// AllowMasterManualMerge 是否允许仓库管理员及负责人手动合并到目标分支。Admins/owners can manually merge to target branch.
	AllowMasterManualMerge *bool `json:"allow_master_manual_merge,omitempty"`
	// AllowMasterPushes 是否仅允许仓库管理员及负责人推送代码到保护分支中。Only admins/owners can push to protected branches.
	AllowMasterPushes *bool `json:"allow_master_pushes,omitempty"`
	// AllowPushes 是否允许所有人推送代码到保护分支中。Whether all users can push to protected branches.
	AllowPushes                      *bool `json:"allow_pushes,omitempty"`
	ForbidApprovePullCreatedByOwnNpc *bool `json:"forbid_approve_pull_created_by_own_npc,omitempty"`
	// Id 保护分支规则唯一标识符。Protected branch rule unique identifier.
	Id *string `json:"id,omitempty"`
	// RequiredApprovedReviewCount 需要的代码评审者数量。格式：`评审者数量 ∈ [1,5]`。Required reviewers count. `∈ [1,5]`.
	RequiredApprovedReviewCount *int `json:"required_approved_review_count,omitempty"`
	// RequiredApprovedReviewRatio 需要的评审通过率。格式：`通过率 ∈ [1, 100]`。Required approval rate. `∈ [1, 100]`.
	RequiredApprovedReviewRatio *int `json:"required_approved_review_ratio,omitempty"`
	// RequiredLinearHistory 是否仅允许线性提交。Whether only linear commits are allowed.
	RequiredLinearHistory *bool `json:"required_linear_history,omitempty"`
	// RequiredMasterApprove 是否需至少一个仓库管理员批准。Whether at least one repo admin approval is required.
	RequiredMasterApprove *bool `json:"required_master_approve,omitempty"`
	// RequiredMustAutoMerge 是否仅允许自动合并。Whether only auto-merge is allowed.
	RequiredMustAutoMerge *bool `json:"required_must_auto_merge,omitempty"`
	// RequiredMustPushViaPullRequest 是否必须通过合并请求推送代码到此规则匹配分支中。Push must be via merge requests.
	RequiredMustPushViaPullRequest *bool `json:"required_must_push_via_pull_request,omitempty"`
	// RequiredPullRequestReviews 保护分支的合并请求是否需要代码评审。Code review required for merge requests.
	RequiredPullRequestReviews *bool `json:"required_pull_request_reviews,omitempty"`
	// RequiredStatusChecks 是否需要通过状态检查。Whether status checks are required.
	RequiredStatusChecks *bool `json:"required_status_checks,omitempty"`
	// Rule 保护分支规则名称，支持通配符。Protected branch rule name. Supports wildcards.
	Rule *string `json:"rule,omitempty"`
}

type CodeIssueDetail struct {
	// AuthorEmail 责任人邮箱（git 原始信息）。Responsible person email (raw git info).
	AuthorEmail string `json:"author_email"`
	// AuthorName 责任人姓名（git 原始信息）。Responsible person name (raw git info).
	AuthorName string `json:"author_name"`
	// CreatedAt 问题创建时间。Issue created at.
	CreatedAt string `json:"created_at"`
	// Description 问题描述。Issue description.
	Description string `json:"description"`
	// DisplayName 规则展示名称。Rule display name.
	DisplayName string `json:"display_name"`
	// ExtraMsg 额外信息。Additional information.
	ExtraMsg string `json:"extra_msg"`
	// FilePath 包含问题的文件路径。File path containing the issue.
	FilePath string `json:"file_path"`
	// Id 问题ID。Issue ID.
	Id string `json:"id"`
	// IgnoredAt 忽略时间。Ignored at.
	IgnoredAt string `json:"ignored_at"`
	// Introduce 问题介绍。Issue introduction.
	Introduce string `json:"introduce"`
	// LineNo 行号。 Line number.
	LineNo int `json:"line_no"`
	// OccurVersion 引入问题的commit。
	OccurVersion string `json:"occur_version"`
	// ReopenAt 重新开启时间。Reopened at.
	ReopenAt string `json:"reopen_at"`
	// RepoId 仓库ID。Repository ID.
	RepoId string `json:"repo_id"`
	// Revision 问题所在的commit。
	Revision string `json:"revision"`
	// RiskLevel 严重级别。Severity level.
	RiskLevel string `json:"risk_level"`
	// Rule 问题规则。Issue rule.
	Rule string `json:"rule"`
	// RuleTitle 规则名称。Rule name.
	RuleTitle string `json:"rule_title"`
	// State 问题状态（open/ignored）。
	State string `json:"state"`
	// Tool 扫描工具。Scanning tool.
	Tool string `json:"tool"`
}

type CodeIssueListData struct {
	// List 问题列表。Issue list.
	List []CodeIssueRecord `json:"list"`
}

type CodeIssueRecord struct {
	// AuthorEmail 责任人邮箱（git 原始信息）。Responsible person email (raw git info).
	AuthorEmail string `json:"author_email"`
	// AuthorName 责任人姓名（git 原始信息）。Responsible person name (raw git info).
	AuthorName string `json:"author_name"`
	// CreatedAt 问题创建时间。Issue created at.
	CreatedAt string `json:"created_at"`
	// DisplayName 规则展示名称。Rule display name.
	DisplayName string `json:"display_name"`
	// FilePath 包含问题的文件路径。File path containing the issue.
	FilePath string `json:"file_path"`
	// Id 问题ID。Issue ID.
	Id string `json:"id"`
	// LineNo 行号。 Line number.
	LineNo int `json:"line_no"`
	// OccurVersion 引入问题的commit。
	OccurVersion string `json:"occur_version"`
	// RepoId 仓库ID。Repository ID.
	RepoId string `json:"repo_id"`
	// Revision 问题所在的commit。
	Revision string `json:"revision"`
	// RiskLevel 严重级别。Severity level.
	RiskLevel string `json:"risk_level"`
	// Rule 问题规则。Issue rule.
	Rule string `json:"rule"`
	// RuleTitle 规则名称。Rule name.
	RuleTitle string `json:"rule_title"`
	// Tool 扫描工具。Scanning tool.
	Tool string `json:"tool"`
}

type Commit struct {
	// Author 提交的作者信息。Commit author info.
	Author UserInfo `json:"author"`
	// Commit 提交的详细信息。Commit detailed information.
	Commit CommitObject `json:"commit"`
	// Committer 提交的提交者信息。Commit committer information.
	Committer UserInfo `json:"committer"`
	// Parents 父提交列表。Parent commit list.
	Parents []CommitParent `json:"parents"`
	// Sha 提交的哈希值。Commit hash.
	Sha string `json:"sha"`
}

type CommitAsset struct {
	// Author 提交附件作者信息。Commit attachment author info.
	Author UserInfo `json:"author"`
	// ContentType 附件内容类型。Attachment content type.
	ContentType string `json:"content_type"`
	// CreatedAt 附件创建时间。Attachment created at.
	CreatedAt string `json:"created_at"`
	// DownloadCount 下载次数。Download count.
	DownloadCount int `json:"download_count"`
	// HashAlgo 附件哈希算法。Attachment hash algorithm.
	HashAlgo string `json:"hash_algo"`
	// HashValue 附件哈希值。Attachment hash.
	HashValue string `json:"hash_value"`
	// Id 附件唯一标识符。Attachment unique identifier.
	Id string `json:"id"`
	// Name 附件名称。Attachment name.
	Name string `json:"name"`
	// Path 附件路径。Attachment path.
	Path string `json:"path"`
	// SizeInByte 附件大小（字节）。Attachment size (bytes).
	SizeInByte int `json:"size_in_byte"`
	// UpdatedAt 附件更新时间。Attachment updated at.
	UpdatedAt string `json:"updated_at"`
}

type CommitDiffFilePatch struct {
	// Additions 新增行数。Number of added lines.
	Additions int `json:"additions"`
	// Deletions 删除行数。Number of deleted lines.
	Deletions int `json:"deletions"`
	// Mode 文件权限模式。File permission mode.
	Mode string `json:"mode"`
	// Name 文件名。File name.
	Name string `json:"name"`
	// Patch Git差异补丁内容。Git diff patch content.
	Patch string `json:"patch"`
	// Path 文件路径。File path.
	Path string `json:"path"`
	// PreviousFilename 重命名前的原文件名。Original file name before rename.
	PreviousFilename string `json:"previous_filename"`
	// PreviousMode 重命名前的文件权限模式。File permission mode before rename.
	PreviousMode string `json:"previous_mode"`
	// Status 文件变更状态。枚举值：`added`,`modified`,`deleted`,`renamed`,`copied`
	Status string `json:"status"`
}

type CommitObject struct {
	// Author 提交的作者签名信息。Commit author signature.
	Author Signature `json:"author"`
	// CommentCount 提交的评论数量。Commit comment count.
	CommentCount int `json:"comment_count"`
	// Committer 提交的提交者签名信息。Commit committer signature.
	Committer Signature `json:"committer"`
	// Message 提交的消息内容。Commit message.
	Message string `json:"message"`
	// Tree 提交对应的树对象信息。Tree object corresponding to the commit.
	Tree CommitObjectTree `json:"tree"`
	// Verification 提交的验证信息。Commit verification information.
	Verification CommitObjectVerification `json:"verification"`
}

type CommitObjectTree struct {
	// Sha 树对象的哈希值。Tree object hash.
	Sha string `json:"sha"`
}

type CommitObjectVerification struct {
	// Payload 验证负载数据。Verification payload data.
	Payload string `json:"payload"`
	// Reason 验证结果的原因。Verification result reason.
	Reason string `json:"reason"`
	// Signature 签名信息。Signature information.
	Signature string `json:"signature"`
	// Verified 提交是否已验证。Whether the commit is verified.
	Verified bool `json:"verified"`
	// VerifiedAt 验证时间。Verification time.
	VerifiedAt string `json:"verified_at"`
}

type CommitParent struct {
	// Sha 父提交的哈希值。Parent commit hash.
	Sha string `json:"sha"`
}

type CommitStatuses struct {
	// Sha 提交的哈希值。Commit hash.
	Sha string `json:"sha"`
	// State 整体提交状态。Overall commit status.
	State string `json:"state"`
	// Statuses 具体的提交状态检查列表。Specific commit status check list.
	Statuses []GitInternalAppVcsServiceBffApiCommitStatus `json:"statuses"`
}

type CompareResponse struct {
	// BaseCommit 基准对比提交。Base comparison commit.
	BaseCommit Commit `json:"base_commit"`
	// Commits 提交列表。Commit list.
	Commits []Commit `json:"commits"`
	// Files 文件差异列表。File diff list.
	Files []CommitDiffFilePatch `json:"files"`
	// HeadCommit 源分支最新提交。 Source branch latest commit.
	HeadCommit Commit `json:"head_commit"`
	// MergeBaseCommit 共同祖先提交。Common ancestor commit.
	MergeBaseCommit Commit `json:"merge_base_commit"`
	// TotalCommits 总提交数。Total commit count.
	TotalCommits int `json:"total_commits"`
}

type Content struct {
	// Content 当内容为text时的实际内容（base64编码）。
	Content string `json:"content"`
	// Encoding 内容编码方式，仅当内容类型为blob时有效。枚举值：`base64`
	Encoding string `json:"encoding"`
	// Entries 子项列表，当内容类型为tree时返回，否则为空。
	Entries []TreeEntry `json:"entries"`
	// LfsDownloadUrl LFS对象的下载URL，仅当内容类型为lfs时有效。LFS download URL.
	LfsDownloadUrl string `json:"lfs_download_url"`
	// LfsOid LFS对象的唯一标识符，仅当内容类型为lfs时有效。LFS unique ID.
	LfsOid string `json:"lfs_oid"`
	// LfsSize LFS对象的大小（字节），仅当内容类型为lfs时有效。LFS size (bytes).
	LfsSize int `json:"lfs_size"`
	// Name 内容名称（文件名或目录名）。Content name (file or directory name).
	Name string `json:"name"`
	// Path 内容在仓库中的完整路径。Full path of the content in the repository.
	Path string `json:"path"`
	// Sha Git对象的哈希值。Git object hash.
	Sha string `json:"sha"`
	// Size 内容大小（字节）。Content size (bytes).
	Size int `json:"size"`
	// Type 内容类型。枚举值：`tree`、`blob`、`lfs`、`empty`
	Type string `json:"type"`
}

type ContributorTrend struct {
	// Author 贡献者信息。Contributor information.
	Author Author `json:"author"`
	// CommitCount 贡献者的总提交数。 Total commits by the contributor.
	CommitCount int `json:"commit_count"`
	// Weeks 贡献者以周为单位的提交趋势数据。 Contributor weekly commit trend data.
	Weeks []Week `json:"weeks"`
}

type DeleteIssueAssigneesForm struct {
	// Assignees Issue处理人用户名列表，最大限制为8。示例：`["zhangsan", "lisi"]`
	Assignees []string `json:"assignees,omitempty"`
}

type DeletePullAssigneesForm struct {
	// Assignees 合并请求的处理人用户列表。Merge request assignee user list.
	Assignees []string `json:"assignees,omitempty"`
}

type DeletePullReviewersForm struct {
	// Reviewers 合并请求的评审人用户列表，最多支持8个。Merge request reviewer user list (max 8).
	Reviewers []string `json:"reviewers,omitempty"`
}

type DiffLine struct {
	// Content 实际内容文本。Actual content text.
	Content string `json:"content"`
	// LeftLineNumber 左侧（原版本）的行号。Left (original) line number.
	LeftLineNumber int `json:"left_line_number"`
	// Prefix 差异行的前缀符号。Diff line prefix symbol.
	Prefix string `json:"prefix"`
	// RightLineNumber 右侧（新版本）的行号。Right (new version) line number.
	RightLineNumber int `json:"right_line_number"`
	// Type 枚举值：`context`,`addition`,`deletion`,`context_eofnl`,`add_eofnl`,`del_eofnl`,`file_header`,`hunk_header`,`binary`
	Type string `json:"type"`
}

type GPGEmail struct {
	// Email 邮箱。Email address.
	Email string `json:"email"`
	// Verified 是否已验证。Whether verified.
	Verified bool `json:"verified"`
}

type GPGPublicKey struct {
	// CreatedAt 主密钥添加时间。Primary key addition time.
	CreatedAt string `json:"created_at"`
	// Emails 邮箱。Email addresses.
	Emails []GPGEmail `json:"emails"`
	// ExpiredAt 主密钥过期时间。Primary key expiration time.
	ExpiredAt string `json:"expired_at"`
	// Id 主密钥ID。Primary key ID.
	Id string `json:"id"`
	// KeyId 公钥 KeyID
	KeyId string `json:"key_id"`
	// Name 标题。Title.
	Name string `json:"name"`
	// RawKey PGP公钥文本
	RawKey string `json:"raw_key"`
	// Subkeys 子密钥。Subkey.
	Subkeys []GPGSubkey `json:"subkeys"`
}

type GPGSubkey struct {
	// CreatedAt 子密钥添加时间。Subkey addition time.
	CreatedAt string `json:"created_at"`
	// ExpiredAt 子密钥过期时间。Subkey expiration time.
	ExpiredAt string `json:"expired_at"`
	// Id 子密钥ID。Subkey ID.
	Id string `json:"id"`
	// KeyId 子密钥 KeyID
	KeyId string `json:"key_id"`
	// PrimaryKeyId 主密钥 ID。Primary key ID.
	PrimaryKeyId string `json:"primary_key_id"`
}

type Issue struct {
	// Assignees Issue处理人列表，最多支持8个处理人。
	Assignees []UserInfo `json:"assignees"`
	// Author Issue创建者信息。
	Author UserInfo `json:"author"`
	// ClosedAt Issue关闭时间。Issue closed time.
	ClosedAt string `json:"closed_at"`
	// CommentCount Issue评论数量。
	CommentCount int `json:"comment_count"`
	// CreatedAt Issue创建时间。
	CreatedAt string `json:"created_at"`
	// EndedAt Issue结束日期。
	EndedAt string `json:"ended_at"`
	// Invisible Issue是否为私密 issue。Whether the issue is private.
	Invisible bool `json:"invisible"`
	// Labels Issue标签列表，最多支持10个标签。
	Labels []Label `json:"labels"`
	// LastActedAt Issue最后活动时间。
	LastActedAt string `json:"last_acted_at"`
	// Number Issue的唯一标识编号。
	Number string `json:"number"`
	// Priority Issue优先级。枚举值：`-2P`,`-1P`,`P0`,`P1`,`P2`,`P3`
	Priority string `json:"priority"`
	// StartedAt Issue开始日期。
	StartedAt string `json:"started_at"`
	// State Issue状态。枚举值：`open`,`closed`
	State string `json:"state"`
	// StateReason 状态变更原因。枚举值：`open`,`completed`,`not_planned`,`reopened`
	StateReason string `json:"state_reason"`
	// Title Issue标题，长度限制2-255字符。
	Title string `json:"title"`
	// UpdatedAt Issue最后更新时间。
	UpdatedAt string `json:"updated_at"`
}

type IssueActivity struct {
	// Actor 动态发起人。Activity initiator.
	Actor UserInfo `json:"actor"`
	// ActorAccessRole 动态发起人的仓库访问角色。Activity initiator repo access role.
	ActorAccessRole string `json:"actor_access_role"`
	// CreatedAt 创建时间。Created at.
	CreatedAt string `json:"created_at"`
	// Id 动态唯一标识。Activity unique identifier.
	Id string `json:"id"`
	// Payload 动态详细内容。Activity detailed content.
	Payload json.RawMessage `json:"payload"`
	// SubmittedAt 提交时间。Commit time.
	SubmittedAt string `json:"submitted_at"`
	// Type 动态类型。Activity type.
	Type string `json:"type"`
}

type IssueAssetUploadURL struct {
	// AssetLink 资源链接。添加到 body 中提交。
	AssetLink string `json:"asset_link"`
	// DownloadUrl 资源下载链接。
	DownloadUrl string `json:"download_url"`
	// Name 文件名。File name.
	Name string `json:"name"`
	// Path 资源路径。Resource path.
	Path string `json:"path"`
	// UploadUrl 上传地址。使用 HTTP Put 请求流试发送数据。Upload URL. Send data via HTTP PUT streaming.
	UploadUrl string `json:"upload_url"`
}

type IssueComment struct {
	// Author 发表评论的用户信息。Comment author user information.
	Author UserInfo `json:"author"`
	// Body 评论的内容。Comment content.
	Body string `json:"body"`
	// CreatedAt 评论的创建时间。Comment created at.
	CreatedAt string `json:"created_at"`
	// Id 评论的唯一标识符。Comment unique identifier.
	Id string `json:"id"`
	// Reactions Reaction 数量列表。
	Reactions []GitInternalAppVcsServiceBffApiSceneReaction `json:"reactions"`
	// Statuses 该评论关联的状态，按分类分组（如 `npc`）。Statuses attached to the comment, grouped by category (e.g. `npc`).
	Statuses StatusesMap `json:"statuses"`
	// UpdatedAt 评论的更新时间。Comment updated at.
	UpdatedAt string `json:"updated_at"`
}

type IssueDetail struct {
	// Assignees Issue处理人列表，最多支持8个处理人。
	Assignees []UserInfo `json:"assignees"`
	// Author Issue创建者信息。
	Author UserInfo `json:"author"`
	// Body Issue内容正文。
	Body string `json:"body"`
	// ClosedAt Issue关闭时间。Issue closed time.
	ClosedAt string `json:"closed_at"`
	// CommentCount Issue评论数量。
	CommentCount int `json:"comment_count"`
	// CreatedAt Issue创建时间。
	CreatedAt string `json:"created_at"`
	// EndedAt Issue结束日期。
	EndedAt string `json:"ended_at"`
	// Invisible Issue是否为私密 issue。Whether the issue is private.
	Invisible bool `json:"invisible"`
	// Labels Issue标签列表，最多支持10个标签（含创建者和贴标者信息）。
	Labels []LabelInfo `json:"labels"`
	// LastActedAt Issue最后活动时间。
	LastActedAt string `json:"last_acted_at"`
	// Number Issue的唯一标识编号。
	Number string `json:"number"`
	// Priority Issue优先级。枚举值：`-2P`,`-1P`,`P0`,`P1`,`P2`,`P3`
	Priority string `json:"priority"`
	// Properties Issue自定义属性列表。
	Properties []IssueProperty `json:"properties"`
	// StartedAt Issue开始日期。
	StartedAt string `json:"started_at"`
	// State Issue状态。枚举值：`open`,`closed`
	State string `json:"state"`
	// StateReason 状态变更原因。枚举值：`open`,`completed`,`not_planned`,`reopened`
	StateReason string `json:"state_reason"`
	// Statuses Statuses 该 Issue 关联的状态，按分类分组（如 `npc`）。Statuses attached to the issue, grouped by category (e.g. `npc`).
	Statuses StatusesMap `json:"statuses"`
	// Title Issue标题，长度限制2-255字符。
	Title string `json:"title"`
	// UpdatedAt Issue最后更新时间。
	UpdatedAt string `json:"updated_at"`
}

type IssueProperty struct {
	// Key 自定义属性键名。Custom property key.
	Key string `json:"key"`
	// Name 自定义属性显示名称。Custom property display name.
	Name string `json:"name"`
	// Type 自定义属性类型。枚举值：`string`,`date`,`number`
	Type string `json:"type"`
	// Value 自定义属性值。Custom property value.
	Value string `json:"value"`
}

type IssuePropertyUpdateResult struct {
	// FailedCount 更新失败的属性数量。Number of properties that failed to update.
	FailedCount int `json:"failed_count"`
	// FailedKeys 更新失败的属性key列表，仅当存在失败时返回
	FailedKeys []string `json:"failed_keys"`
	// SuccessCount 更新成功的属性数量。Number of properties that updated successfully.
	SuccessCount int `json:"success_count"`
}

type Label struct {
	// Color 标签颜色。Tag color.
	Color string `json:"color"`
	// Description 标签描述。Tag description.
	Description string `json:"description"`
	// Id 标签ID。Tag ID.
	Id string `json:"id"`
	// Name 标签名称。Tag name.
	Name string `json:"name"`
}

type LabelInfo struct {
	// AppliedBy 贴标者信息。Tagger information.
	AppliedBy UserInfo `json:"applied_by"`
	// Color 标签颜色。Tag color.
	Color string `json:"color"`
	// Creator 标签创建者信息。Tag creator information.
	Creator UserInfo `json:"creator"`
	// Description 标签描述。Tag description.
	Description string `json:"description"`
	// Id 标签ID。Tag ID.
	Id string `json:"id"`
	// Name 标签名称。Tag name.
	Name string `json:"name"`
}

type MergePullRequest struct {
	// CommitMessage 合并提交的详细描述信息。Merge commit detailed description.
	CommitMessage *string `json:"commit_message,omitempty"`
	// CommitTitle 合并提交的标题。Merge commit title.
	CommitTitle *string `json:"commit_title,omitempty"`
	// Force 是否强制合并。Whether to force merge, only allowed for repository owner or admin.
	Force *bool `json:"force,omitempty"`
	// MergeStyle 合并提交方式。可选值：`merge`,`squash`,`rebase`
	MergeStyle *string `json:"merge_style,omitempty"`
}

type MergePullResponse struct {
	// Merged 是否成功合并。Whether merged successfully.
	Merged bool `json:"merged"`
	// Message 合并操作的响应消息。Merge operation response message.
	Message string `json:"message"`
	// Sha 合并提交的哈希值。Merge commit hash.
	Sha string `json:"sha"`
}

type Meta struct {
	// GenBranch 生成数据的分支名称。Branch name where data was generated.
	GenBranch string `json:"gen_branch"`
	// GenHash 生成数据的提交哈希。Commit hash where data was generated.
	GenHash string `json:"gen_hash"`
	// UpdatedAt 数据更新时间戳。Data update timestamp.
	UpdatedAt string `json:"updated_at"`
}

type PatchIssueAssigneesForm struct {
	// Assignees Issue处理人用户名列表，最大限制为8。示例：`["zhangsan", "lisi"]`
	Assignees []string `json:"assignees,omitempty"`
}

type PatchIssueCommentForm struct {
	// Body Issue评论内容。
	Body *string `json:"body,omitempty"`
}

type PatchIssueForm struct {
	// Body Issue内容。
	Body *string `json:"body,omitempty"`
	// EndDate Issue结束日期。示例：`2026-12-30`
	EndDate *string `json:"end_date,omitempty"`
	// Invisible 是否为私密 issue。Whether the issue is private.
	Invisible *bool `json:"invisible,omitempty"`
	// Priority Issue优先级。可选值：`-2P`,`-1P`,`P0`,`P1`,`P2`,`P3`
	Priority *string `json:"priority,omitempty"`
	// StartDate Issue开始日期。示例：`2026-01-01`
	StartDate *string `json:"start_date,omitempty"`
	// State Issue状态。可选值：`open`,`closed`
	State *string `json:"state,omitempty"`
	// StateReason ISSUE状态变更原因。可选值：`completed`,`not_planned`,`reopened`
	StateReason *string `json:"state_reason,omitempty"`
	// Title Issue标题。
	Title *string `json:"title,omitempty"`
}

type PatchLabelForm struct {
	// Color 标签颜色。示例值: `ff0000`,`00ff00`,`0000ff`,`ffffff`。
	Color *string `json:"color,omitempty"`
	// Description 标签描述信息。Tag description.
	Description *string `json:"description,omitempty"`
	// NewName 标签名称。Tag name.
	NewName *string `json:"new_name,omitempty"`
}

type PatchPullCommentForm struct {
	// Body 评论内容。Comment content.
	Body *string `json:"body,omitempty"`
}

type PatchPullRequest struct {
	// Body 合并请求的更新内容。Merge request updated description.
	Body *string `json:"body,omitempty"`
	// State 合并请求的更新状态。可选值：`open`,`closed`
	State *string `json:"state,omitempty"`
	// Title 合并请求的更新标题。Merge request updated title.
	Title *string `json:"title,omitempty"`
}

type PipelineSettings struct {
	// AutoTrigger 是否允许仓库按照.cnb.yml配置自动触发云原生构建。
	AutoTrigger *bool `json:"auto_trigger,omitempty"`
	// AutoTriggerByNpc 是否允许NPC自动触发云原生构建。
	AutoTriggerByNpc *bool `json:"auto_trigger_by_npc,omitempty"`
	// CronAutoTrigger 是否允许仓库按照.cnb.yml配置自动触发定时任务。
	CronAutoTrigger *bool `json:"cron_auto_trigger,omitempty"`
	// ForkedRepoAutoTrigger 是否允许本仓Fork出来的仓库按照.cnb.yml配置自动触发云原生构建。
	ForkedRepoAutoTrigger *bool `json:"forked_repo_auto_trigger,omitempty"`
}

type PostAssetGroupForm struct {
	FileAssets  []PostIssueAssetUploadURLForm `json:"file_assets,omitempty"`
	ImageAssets []PostIssueAssetUploadURLForm `json:"image_assets,omitempty"`
}

type PostBlobForm struct {
	// Content Blob的内容。Blob content.
	Content *string `json:"content,omitempty"`
	// Encoding 内容的编码格式。可选值：`utf-8`,`base64`。Content encoding format. Options: `utf-8`, `base64`.
	Encoding *string `json:"encoding,omitempty"`
}

type PostIssueAssetUploadURLForm struct {
	// ContentType 文件类型。File type.
	ContentType *string `json:"content_type,omitempty"`
	// Name 文件名。必填。File name (required).
	Name *string `json:"name,omitempty"`
	// Size 文件大小，单位：字节。必须大于 0。File size in bytes. Must be greater than 0.
	Size *int `json:"size,omitempty"`
}

type PostIssueAssigneesForm struct {
	// Assignees Issue处理人用户名列表，最大限制为8。示例：`["zhangsan", "lisi"]`
	Assignees []string `json:"assignees,omitempty"`
}

type PostIssueCommentForm struct {
	// Body Issue评论内容。
	Body     *string `json:"body,omitempty"`
	WorkMode *bool   `json:"work_mode,omitempty"`
}

type PostIssueForm struct {
	// Assignees Issue处理人列表，最大限制为8。示例：`["处理人1","处理人2"]`
	Assignees []string `json:"assignees,omitempty"`
	// Body Issue内容。
	Body *string `json:"body,omitempty"`
	// EndDate Issue结束日期。示例：`2026-12-30`
	EndDate *string `json:"end_date,omitempty"`
	// Invisible 是否为私密 issue。Whether the issue is private.
	Invisible *bool `json:"invisible,omitempty"`
	// Labels Issue标签列表，最大限制为10。示例：`["标签1","标签2"]`
	Labels []string `json:"labels,omitempty"`
	// Priority Issue优先级。可选值：`-2P`,`-1P`,`P0`,`P1`,`P2`,`P3`
	Priority *string `json:"priority,omitempty"`
	// StartDate Issue开始日期。示例：`2026-01-01`
	StartDate *string `json:"start_date,omitempty"`
	// Title Issue标题。
	Title *string `json:"title,omitempty"`
	// WorkMode 是否开启工作模式。Whether work mode is enabled.
	WorkMode *bool `json:"work_mode,omitempty"`
}

type PostIssueLabelsForm struct {
	// Labels Issue标签列表，最大限制为10。示例：`["标签1","标签2"]`
	Labels []string `json:"labels,omitempty"`
}

type PostLabelForm struct {
	// Color 标签颜色。示例值: `ff0000`,`00ff00`,`0000ff`,`ffffff`。
	Color *string `json:"color,omitempty"`
	// Description 标签描述信息。Tag description.
	Description *string `json:"description,omitempty"`
	// Name 标签名称。Tag name.
	Name *string `json:"name,omitempty"`
}

type PostPullAssigneesForm struct {
	// Assignees 合并请求的处理人用户列表，最多支持8个。Merge request assignee user list (max 8).
	Assignees []string `json:"assignees,omitempty"`
}

type PostPullLabelsForm struct {
	// Labels 合并请求的标签列表。Merge request tag list.
	Labels []string `json:"labels,omitempty"`
}

type PostPullRequestReviewReplyForm struct {
	// Body 回复的评论内容。Reply comment content.
	Body *string `json:"body,omitempty"`
	// ReplyToCommentId 父评论ID。Parent comment ID.
	ReplyToCommentId *string `json:"reply_to_comment_id,omitempty"`
	// WorkMode 工作模式标志。Work mode flag.
	WorkMode *bool `json:"work_mode,omitempty"`
}

type PostPullReviewersForm struct {
	// Reviewers 合并请求的评审人用户列表，最多支持8个。Merge request reviewer user list (max 8).
	Reviewers []string `json:"reviewers,omitempty"`
}

type PostTagFrom struct {
	// Message 标签的描述信息。Tag description.
	Message *string `json:"message,omitempty"`
	// Name 标签名称。Tag name.
	Name *string `json:"name,omitempty"`
	// Target 标签指向的目标对象。格式：`分支名称`,`标签名称`,`提交哈希`。Tag target object. Format: `branch_name`,`tag_name`,`commit_hash`.
	Target *string `json:"target,omitempty"`
}

type Pull struct {
	// Author 作者信息。Author information.
	Author UserInfo `json:"author"`
	// Base 目标分支信息。 Target branch info.
	Base PullRef `json:"base"`
	// BlockedOn 阻塞原因。枚举值：`no_merge_base`,`internal_error`,`code_conflict`,`status_check`,`waiting_review`
	BlockedOn string `json:"blocked_on"`
	// Body 合并请求内容。Merge request content.
	Body string `json:"body"`
	// Head 源分支信息。 Source branch info.
	Head PullRef `json:"head"`
	// IsForceMerged 是否强制合并。Whether the pull request was force-merged, bypassing branch protection rules.
	IsForceMerged bool `json:"is_force_merged"`
	// IsMerged 是否已经合并。Whether the pull request has been merged.
	IsMerged bool `json:"is_merged"`
	// IsWip 是否为WIP状态，WIP状态表示合并请求是否是草稿阶段。
	IsWip bool `json:"is_wip"`
	// Labels 关联的标签列表（含创建者和贴标者信息）。Associated tag list (including creator and tagger info).
	Labels []LabelInfo `json:"labels"`
	// MergeableState 可合并状态。枚举值：`checking`,`mergeable`,`merging`,`merged`,`conflict`,`no-merge-base`
	MergeableState string `json:"mergeable_state"`
	// MergedBy 合并者信息。Merger information.
	MergedBy UserInfo `json:"merged_by"`
	// Number 合并请求唯一标识符编号。Merge request unique identifier number.
	Number string `json:"number"`
	// Reviewers 评审人列表，包含评审状态信息。Reviewer list with review status.
	Reviewers []PullReviewer `json:"reviewers"`
	// State 合并请求状态。枚举值：`open`,`closed`,`merged`
	State string `json:"state"`
	// Statuses Statuses 该合并请求关联的状态，按分类分组（如 `npc`）。Statuses attached to the pull request, grouped by category (e.g. `npc`).
	Statuses StatusesMap `json:"statuses"`
	// Title 合并请求标题。Merge request title.
	Title string `json:"title"`
}

type PullCommentCreationForm struct {
	// Body 评论内容。Comment content.
	Body *string `json:"body,omitempty"`
	// WorkMode 工作模式标志。Work mode flag.
	WorkMode *bool `json:"work_mode,omitempty"`
}

type PullCreationForm struct {
	// Base 目标分支名称。 Target branch name.
	Base *string `json:"base,omitempty"`
	// Body 合并请求内容。Merge request content.
	Body *string `json:"body,omitempty"`
	// Head 源分支名称。 Source branch name.
	Head *string `json:"head,omitempty"`
	// HeadRepo 源分支所在的仓库标识。示例值：`owner/repo`
	HeadRepo *string `json:"head_repo,omitempty"`
	// Title 合并请求标题。Merge request title.
	Title *string `json:"title,omitempty"`
}

type PullFile struct {
	// Additions 新增行数。Number of added lines.
	Additions int `json:"additions"`
	// BlobUrl 文件的Blob对象访问地址。File blob object access URL.
	BlobUrl string `json:"blob_url"`
	// ContentsUrl 文件内容访问地址。File content access URL.
	ContentsUrl string `json:"contents_url"`
	// Deletions 删除行数。Number of deleted lines.
	Deletions int `json:"deletions"`
	// Filename 文件名称。File name.
	Filename string `json:"filename"`
	// Patch 文件的差异补丁内容。File diff patch content.
	Patch string `json:"patch"`
	// RawUrl 文件的原始内容访问地址。File raw content access URL.
	RawUrl string `json:"raw_url"`
	// Sha 文件的提交哈希值。File commit hash.
	Sha string `json:"sha"`
	// Status 文件更改状态。枚举值：`add`,`modify`,`delete`,`rename`,`copy`
	Status string `json:"status"`
}

type PullRef struct {
	// Ref 分支引用名称。示例值：`refs/heads/main`
	Ref string `json:"ref"`
	// Repo 关联的仓库信息。Associated repository info.
	Repo ApiRepo `json:"repo"`
	// Sha 提交哈希值。Commit hash.
	Sha string `json:"sha"`
}

type PullRefInfo struct {
	// Ref 分支引用名称。Branch reference name.
	Ref string `json:"ref"`
	// Repo 关联的仓库信息。Associated repository info.
	Repo RepoInfo `json:"repo"`
	// Sha 提交哈希值。Commit hash.
	Sha string `json:"sha"`
}

type PullRequest struct {
	// Assignees 处理人列表。Assignee list.
	Assignees []UserInfo `json:"assignees"`
	// Author 作者信息。Author information.
	Author UserInfo `json:"author"`
	// Base 目标分支信息。 Target branch info.
	Base PullRef `json:"base"`
	// BlockedOn 阻塞原因。枚举值：`no_merge_base`,`internal_error`,`code_conflict`,`status_check`,`waiting_review`
	BlockedOn string `json:"blocked_on"`
	// Body 合并请求内容。Merge request content.
	Body string `json:"body"`
	// CommentCount 评论数量。Comment count.
	CommentCount int `json:"comment_count"`
	// CreatedAt 创建时间。Created at.
	CreatedAt string `json:"created_at"`
	// Head 源分支信息。 Source branch info.
	Head PullRef `json:"head"`
	// IsForceMerged 是否强制合并。Whether the pull request was force-merged, bypassing branch protection rules.
	IsForceMerged bool `json:"is_force_merged"`
	// IsMerged 是否已经合并。Whether the pull request has been merged.
	IsMerged bool `json:"is_merged"`
	// IsWip 是否为WIP状态，WIP状态表示合并请求是否是草稿阶段。
	IsWip bool `json:"is_wip"`
	// Labels 标签列表。Tag list.
	Labels []Label `json:"labels"`
	// LastActedAt 最后更新时间。 Last updated at.
	LastActedAt string `json:"last_acted_at"`
	// MergeableState 可合并状态。枚举值：`checking`,`mergeable`,`merging`,`merged`,`conflict`,`no-merge-base`
	MergeableState string `json:"mergeable_state"`
	// MergedBy 合并者信息。Merger information.
	MergedBy UserInfo `json:"merged_by"`
	// Number Pulls唯一标识编号。
	Number string `json:"number"`
	// Repo 仓库信息。Repository information.
	Repo ApiRepo `json:"repo"`
	// ReviewCount 评审数量。Review count.
	ReviewCount int `json:"review_count"`
	// State 合并请求状态。枚举值：`open`,`closed`,`merged`
	State string `json:"state"`
	// Title 合并请求标题。Merge request title.
	Title string `json:"title"`
	// UpdatedAt 更新时间。Updated at.
	UpdatedAt string `json:"updated_at"`
}

type PullRequestComment struct {
	// Author 评论作者信息。Comment author info.
	Author UserInfo `json:"author"`
	// Body 评论内容。Comment content.
	Body string `json:"body"`
	// CreatedAt 创建时间。Created at.
	CreatedAt string `json:"created_at"`
	// Id 合并请求评论的唯一标识符。Merge request comment unique identifier.
	Id string `json:"id"`
	// Reactions Reaction 数量列表。
	Reactions []SceneReaction `json:"reactions"`
	// Statuses 该评论关联的状态，按分类分组（如 `npc`）。Statuses attached to the comment, grouped by category (e.g. `npc`).
	Statuses StatusesMap `json:"statuses"`
	// UpdatedAt 最后更新时间。 Last updated at.
	UpdatedAt string `json:"updated_at"`
}

type PullRequestInfo struct {
	// Assignees 处理人列表。Assignee list.
	Assignees []UserInfo `json:"assignees"`
	// Author 作者信息。Author information.
	Author UserInfo `json:"author"`
	// Base 目标分支信息。 Target branch info.
	Base PullRefInfo `json:"base"`
	// BlockedOn 阻塞原因。枚举值：`no_merge_base`,`internal_error`,`code_conflict`,`status_check`,`waiting_review`
	BlockedOn string `json:"blocked_on"`
	// CreatedAt 创建时间。Created at.
	CreatedAt string `json:"created_at"`
	// Head 源分支信息。 Source branch info.
	Head PullRefInfo `json:"head"`
	// Labels 标签列表。Tag list.
	Labels []Label `json:"labels"`
	// LastActedAt 最后更新时间。 Last updated at.
	LastActedAt string `json:"last_acted_at"`
	// MergeableState 可合并状态。枚举值：`checking`,`mergeable`,`merging`,`merged`,`conflict`,`no-merge-base`
	MergeableState string `json:"mergeable_state"`
	// MergedBy 合并者信息。Merger information.
	MergedBy UserInfo `json:"merged_by"`
	// Number Pull唯一标识编号。
	Number string `json:"number"`
	// Repo 仓库信息。Repository information.
	Repo RepoInfo `json:"repo"`
	// Reviewers 评审者列表。Reviewer list.
	Reviewers []UserInfo `json:"reviewers"`
	// State Pull状态。枚举值：`open`,`closed`,`merged`
	State string `json:"state"`
	// Title 标题。Title.
	Title string `json:"title"`
	// UpdatedAt 更新时间。Updated at.
	UpdatedAt string `json:"updated_at"`
}

type PullRequestSettings struct {
	// AllowMergeCommitMerge 是否允许直接提交合并。Whether direct commit merge is allowed.
	AllowMergeCommitMerge *bool `json:"allow_merge_commit_merge,omitempty"`
	// AllowRebaseMerge 是否允许变基合并。 Whether rebase merge is allowed.
	AllowRebaseMerge *bool `json:"allow_rebase_merge,omitempty"`
	// AllowSquashMerge 是否允许压缩合并。 Whether squash merge is allowed.
	AllowSquashMerge *bool `json:"allow_squash_merge,omitempty"`
	// MasterAutoAsReviewer 是否允许自动添加仓库管理员为评审者。Whether to automatically add repo admins as reviewers.
	MasterAutoAsReviewer *bool `json:"master_auto_as_reviewer,omitempty"`
	// MergeCommitMessageStyle 直接提交合并操作时默认生成的提交信息内容。可选值：`default`,`pull_request_title`,`pull_request_title_with_body`
	MergeCommitMessageStyle *string `json:"merge_commit_message_style,omitempty"`
	// SquashCommitMessageStyle 压缩合并操作时默认生成的提交信息内容。可选值：`default`,`pull_request_title`,`pull_request_title_with_body`
	SquashCommitMessageStyle *string `json:"squash_commit_message_style,omitempty"`
}

type PullReview struct {
	// Author Review的作者信息。
	Author UserInfo `json:"author"`
	// Body Review的详细内容。
	Body string `json:"body"`
	// CreatedAt Review的创建时间。
	CreatedAt string `json:"created_at"`
	// Id Review的唯一标识符。
	Id string `json:"id"`
	// State Review的状态。枚举值：`approved`、`changes_requested`、`commented`、`dismissed`、`pending`等。
	State string `json:"state"`
	// Statuses Statuses 该 Review 关联的状态，按分类分组（如 `npc`）。Statuses attached to the review, grouped by category (e.g. `npc`).
	Statuses StatusesMap `json:"statuses"`
	// UpdatedAt Review的最后更新时间。
	UpdatedAt string `json:"updated_at"`
}

type PullReviewComment struct {
	// Author 评论的作者信息。Comment author info.
	Author UserInfo `json:"author"`
	// Body 评论的具体内容。Comment specific content.
	Body string `json:"body"`
	// CommitHash 评论所基于的提交哈希值。Commit hash the comment is based on.
	CommitHash string `json:"commit_hash"`
	// CreatedAt 评论的创建时间。Comment created at.
	CreatedAt string `json:"created_at"`
	// DiffHunk 评论关联的差异块信息。Diff block associated with the comment.
	DiffHunk []DiffLine `json:"diff_hunk"`
	// EndLine 评论结束行号，subject_type=line时有效。
	EndLine int `json:"end_line"`
	// EndSide 评论结束位置的代码版本侧。枚举值：`left`,`right`
	EndSide string `json:"end_side"`
	// Id 评论的唯一标识符。Comment unique identifier.
	Id string `json:"id"`
	// Path 评论所在文件的路径。示例值：`src/main.go`
	Path string `json:"path"`
	// Reactions Reaction 数量列表。
	Reactions []SceneReaction `json:"reactions"`
	// ReplyToCommentId 回复的父评论ID，如果是回复评论则不为空。Parent comment ID. Non-empty if this is a reply.
	ReplyToCommentId string `json:"reply_to_comment_id"`
	// ReviewId 所属Review的唯一标识符。
	ReviewId string `json:"review_id"`
	// ReviewState Review的状态。枚举值：`approved`,`changes_requested`,`commented`,`dismissed`,`pending`
	ReviewState string `json:"review_state"`
	// StartLine 评论起始行号，subject_type=line时有效。
	StartLine int `json:"start_line"`
	// StartSide 评论起始位置的代码版本侧。枚举值：`left`,`right`
	StartSide string `json:"start_side"`
	// Statuses Statuses 该评审评论关联的状态，按分类分组（如 `npc`）。Statuses attached to the review comment, grouped by category (e.g. `npc`).
	Statuses StatusesMap `json:"statuses"`
	// SubjectType 评论对象类型。枚举值：`line`,`file`
	SubjectType string `json:"subject_type"`
	// UpdatedAt 评论的最后更新时间。Comment last updated at.
	UpdatedAt string `json:"updated_at"`
}

type PullReviewCommentCreationForm struct {
	// Body 评论内容。Comment content.
	Body string `json:"body"`
	// EndLine 结束行号，subject_type=line时必填。
	EndLine int `json:"end_line"`
	// EndSide 评论结束位置的代码版本侧，subject_type=line时必填。可选值：`left`,`right`
	EndSide string `json:"end_side"`
	// Path 文件路径。示例值：`src/main.go`
	Path string `json:"path"`
	// StartLine 起始行号，subject_type=line时必填。
	StartLine int `json:"start_line"`
	// StartSide 评论起始位置的代码版本侧，subject_type=line时必填。可选值：`left`,`right`
	StartSide string `json:"start_side"`
	// SubjectType 评论对象类型，当subject_type为file时无需指定行号和侧别字段。可选值：`line`,`file`
	SubjectType string `json:"subject_type"`
}

type PullReviewCreationForm struct {
	// Body Review的评审意见内容。
	Body *string `json:"body,omitempty"`
	// Comments 评审中的具体评论列表。Specific review comment list.
	Comments []PullReviewCommentCreationForm `json:"comments,omitempty"`
	// Event Review事件类型.如：`approve`,`comment`,`request_changes`,`pending`
	Event *string `json:"event,omitempty"`
	// WorkMode 工作模式标志。Work mode flag.
	WorkMode *bool `json:"work_mode,omitempty"`
}

type PullReviewer struct {
	// ReviewState 评审状态。枚举值：`pending`,`commented`,`approved`,`changes_requested`,`dismissed`。
	ReviewState string `json:"review_state"`
	// User 评审人信息。Reviewer information.
	User UserInfo `json:"user"`
}

type PushLimitSettings struct {
	// AllowSinglePushNumber 允许单次推送最多允许更新分支和标签的个数数量。Maximum number of branch and tag updates per single push.
	AllowSinglePushNumber *int `json:"allow_single_push_number,omitempty"`
	// CheckSinglePushNumber 是否开启单次更新分支和标签的个数限制。Whether to limit the number of branch and tag updates per single push.
	CheckSinglePushNumber *bool `json:"check_single_push_number,omitempty"`
	// CommitMustBeSignatured 强制要求提交必须有签名。Require commits to be signed.
	CommitMustBeSignatured *bool `json:"commit_must_be_signatured,omitempty"`
	// OnlyMasterCanPushTag 是否仅允许负责人和管理员推送或删除标签、创建或删除版本。Only owners/admins can push/delete tags or releases.
	OnlyMasterCanPushTag *bool `json:"only_master_can_push_tag,omitempty"`
	// PushCommitMustBe 推送提交到仓库，对提交作者和提交人进行检查。可选值：`any`,`registered`,`pusher`
	PushCommitMustBe *string `json:"push_commit_must_be,omitempty"`
}

type PutIssueLabelsForm struct {
	// Labels Issue标签列表，最大限制为10。示例：`["标签1","标签2"]`
	Labels []string `json:"labels,omitempty"`
}

type PutPullLabelsForm struct {
	// Labels 合并请求的标签列表。Merge request tag list.
	Labels []string `json:"labels,omitempty"`
}

type Release struct {
	// Assets 附件列表。Attachment list.
	Assets []ReleaseAsset `json:"assets"`
	// Author 作者信息。Author information.
	Author UserInfo `json:"author"`
	// Body 版本描述。Release description.
	Body string `json:"body"`
	// CreatedAt 创建时间。Created at.
	CreatedAt string `json:"created_at"`
	// Draft 是否为草稿版本。Whether this is a draft release.
	Draft bool `json:"draft"`
	// Id 版本唯一标识符。Release unique identifier.
	Id string `json:"id"`
	// IsLatest 是否为最新版本。Whether this is the latest version.
	IsLatest bool `json:"is_latest"`
	// Name 版本标题。Release title.
	Name string `json:"name"`
	// Prerelease 是否为预发布版本。Whether this is a pre-release.
	Prerelease bool `json:"prerelease"`
	// PublishedAt 版本发布时间。Release published at.
	PublishedAt string `json:"published_at"`
	// TagCommitish 标签与提交标识符。Tag and commit identifier.
	TagCommitish string `json:"tag_commitish"`
	// TagName 标签名称。Tag name.
	TagName string `json:"tag_name"`
	// UpdatedAt 更新时间。Updated at.
	UpdatedAt string `json:"updated_at"`
}

type ReleaseAsset struct {
	// BrowerDownloadUrl 拼写错误，即将删除，请使用 browser_download_url。Spelling error, about to be deleted. Please use browser_download_url.
	BrowerDownloadUrl string `json:"brower_download_url"`
	// BrowserDownloadUrl 浏览器下载URL（通过主域名，用于用户直接访问）。Browser download URL (via main domain, for direct user access).
	BrowserDownloadUrl string `json:"browser_download_url"`
	// ContentType 附件内容类型。Attachment content type.
	ContentType string `json:"content_type"`
	// CreatedAt 创建时间。Created at.
	CreatedAt string `json:"created_at"`
	// DownloadCount 下载次数。Download count.
	DownloadCount int `json:"download_count"`
	// HashAlgo 附件哈希算法。Attachment hash algorithm.
	HashAlgo string `json:"hash_algo"`
	// HashValue 附件哈希值。Attachment hash.
	HashValue string `json:"hash_value"`
	// Id 附件唯一标识符。Attachment unique identifier.
	Id string `json:"id"`
	// Name 附件名称。Attachment name.
	Name string `json:"name"`
	// Path 附件路径。Attachment path.
	Path string `json:"path"`
	// Size 附件大小（字节）。Attachment size (bytes).
	Size int `json:"size"`
	// UpdatedAt 更新时间。Updated at.
	UpdatedAt string `json:"updated_at"`
	// Uploader 附件上传者信息。Attachment uploader information.
	Uploader UserInfo `json:"uploader"`
	// Url API下载URL（通过API域名，用于程序化下载）。API download URL (via API domain, for programmatic download).
	Url string `json:"url"`
}

type ApiRepo struct {
	// Id 仓库的唯一标识符。Repository unique identifier.
	Id string `json:"id"`
	// Name 仓库名称。Repository name.
	Name string `json:"name"`
	// Path 仓库的路径标识符。Repository path identifier.
	Path string `json:"path"`
	// WebUrl 仓库的Web访问地址。
	WebUrl string `json:"web_url"`
}

type RepoContribTrend struct {
	// Meta 元数据信息，包含生成分支、哈希和时间戳。Metadata information, including generation branch, hash, and timestamp.
	Meta Meta `json:"meta"`
	// RepoData 仓库级别的周度统计数据。Weekly statistics for the repository.
	RepoData []Week `json:"repo_data"`
	// UserTotal 贡献者总数。Total contributors.
	UserTotal int `json:"user_total"`
	// UsersData 贡献者级别的趋势数据，按提交数排序。Contributor-level trend data, sorted by commit count.
	UsersData []ContributorTrend `json:"users_data"`
	// WeekTotal 统计的周总数。Total number of weeks in the statistics.
	WeekTotal int `json:"week_total"`
	// WithLineCounts 是否统计增删的行数，默认总提交超过10000的仓库不统计。Count added/deleted lines. Off for repos >10000 commits.
	WithLineCounts bool `json:"with_line_counts"`
}

type RepoInfo struct {
	// Id 仓库ID。Repository ID.
	Id string `json:"id"`
	// Name 仓库名称。Repository name.
	Name string `json:"name"`
	// Path 仓库路径。Repository path.
	Path string `json:"path"`
	// WebUrl 仓库Web访问地址。
	WebUrl string `json:"web_url"`
}

type RepoProperty struct {
	// Key 自定义属性键名（唯一）。Custom property key (unique).
	Key string `json:"key"`
	// Name 自定义属性显示名称。Custom property display name.
	Name string `json:"name"`
	// Type 自定义属性类型。枚举值：`string`,`date`,`number`
	Type string `json:"type"`
	// Visible 是否可见。Whether visible.
	Visible bool `json:"visible"`
}

type Signature struct {
	// Date 签名时间。Signature time.
	Date string `json:"date"`
	// Email 签名者邮箱。Signer email.
	Email string `json:"email"`
	// Name 签名者姓名。Signer name.
	Name string `json:"name"`
}

type StatusGroup struct {
	// Annotations Annotations 附加信息。Additional annotations.
	Annotations map[string]string `json:"annotations"`
	// Context Context 白名单过滤后的安全上下文字段（如 pipeline_id/sn 等）。Whitelisted context fields.
	Context map[string]string `json:"context"`
	// Key Key 分类特有的标识信息，原样透出（如 npc 分类为 {"name":..., "slug":...}）。 采用 map 承载以保持分类无关，便于未来扩展。Category-specific identity, passed through as-is.
	Key map[string]string `json:"key"`
	// Statuses Statuses 具体状态检查列表。Specific status check list.
	Statuses []StatusItem `json:"statuses"`
}

type StatusItem struct {
	// Annotations 附加信息，如用量、token 等。Additional annotations such as usage/token.
	Annotations map[string]string `json:"annotations"`
	// Context 上下文标识，通常为流水线名称。Context identifier, usually the pipeline name.
	Context string `json:"context"`
	// Description 描述信息。Description.
	Description string `json:"description"`
	// State 状态。枚举值：`success`,`pending`,`failure`,`error`,`skipped`。Status check result.
	State string `json:"state"`
	// TargetUrl 构建详情链接。Build detail link.
	TargetUrl string `json:"target_url"`
	// Tasks 执行计划。Task plan.
	Tasks map[string]string `json:"tasks"`
}

type StatusesMap struct {
	_ struct{} `json:"-"`
}

type Tag struct {
	// Commit 标签指向的commit对象详细信息。
	Commit Commit `json:"commit"`
	// Name 标签名称。Tag name.
	Name string `json:"name"`
	// Target 标签目标对象哈希值。Tag target object hash.
	Target string `json:"target"`
	// TargetType 目标对象类型。Target object type.
	TargetType string `json:"target_type"`
	// Verification 标签的GPG签名验证信息。Tag GPG signature verification info.
	Verification TagObjectVerification `json:"verification"`
}

type TagObjectVerification struct {
	// Payload 签名的载荷数据。Signature payload data.
	Payload string `json:"payload"`
	// Reason 验证结果的原因描述。Verification result reason description.
	Reason string `json:"reason"`
	// Signature GPG签名内容。GPG signature content.
	Signature string `json:"signature"`
	// Verified 签名验证是否通过。Whether signature verification passed.
	Verified bool `json:"verified"`
	// VerifiedAt 验证时间戳。Verification timestamp.
	VerifiedAt string `json:"verified_at"`
}

type TreeEntry struct {
	// Name 对象名称（文件名或目录名）。Object name (file or directory name).
	Name string `json:"name"`
	// Path 对象在仓库中的完整路径。Full path of the object in the repository.
	Path string `json:"path"`
	// Sha Git对象的哈希值。Git object hash.
	Sha string `json:"sha"`
	// Type 对象类型。枚举值：`tree`,`blob`,`link`,`submodule`
	Type string `json:"type"`
}

type UserInfo struct {
	// Avatar 用户头像。User avatar.
	Avatar string `json:"avatar"`
	// Email 用户邮箱。User email.
	Email string `json:"email"`
	// Freeze 是否冻结。Whether frozen.
	Freeze bool `json:"freeze"`
	// IsNpc 是否是 NPC。
	IsNpc bool `json:"is_npc"`
	// Nickname 昵称。 Nickname.
	Nickname string `json:"nickname"`
	// Username 用户名。Username.
	Username string `json:"username"`
}

type UserIssue struct {
	// Assignees Issue处理人列表，最多支持8个处理人。
	Assignees []UserInfo `json:"assignees"`
	// Author Issue创建者信息。
	Author UserInfo `json:"author"`
	// ClosedAt Issue关闭时间。Issue closed time.
	ClosedAt string `json:"closed_at"`
	// CommentCount Issue评论数量。
	CommentCount int `json:"comment_count"`
	// CreatedAt Issue创建时间。
	CreatedAt string `json:"created_at"`
	// EndedAt Issue结束日期。
	EndedAt string `json:"ended_at"`
	// Invisible Issue是否为私密 issue。Whether the issue is private.
	Invisible bool `json:"invisible"`
	// Labels Issue标签列表，最多支持10个标签。
	Labels []Label `json:"labels"`
	// LastActedAt Issue最后活动时间。
	LastActedAt string `json:"last_acted_at"`
	// Number Issue的唯一标识编号。
	Number string `json:"number"`
	// Priority Issue优先级。枚举值：`-2P`,`-1P`,`P0`,`P1`,`P2`,`P3`
	Priority string `json:"priority"`
	// Repo 关联的仓库信息。Associated repository info.
	Repo RepoInfo `json:"repo"`
	// StartedAt Issue开始日期。
	StartedAt string `json:"started_at"`
	// State Issue状态。枚举值：`open`,`closed`
	State string `json:"state"`
	// StateReason 状态变更原因。枚举值：`open`,`completed`,`not_planned`,`reopened`
	StateReason string `json:"state_reason"`
	// Title Issue标题，长度限制2-255字符。
	Title string `json:"title"`
	// UpdatedAt Issue最后更新时间。
	UpdatedAt string `json:"updated_at"`
}

type Week struct {
	// A 每周增加的行数。 Number of lines added per week.
	A int `json:"a"`
	// C 每周的提交数量。 Number of commits per week.
	C int `json:"c"`
	// D 每周删除的行数。 Number of lines deleted per week.
	D int `json:"d"`
	// W 周的时间戳。Week timestamp.
	W int `json:"w"`
}
