// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import "encoding/json"

type Dependency struct {
	// Alias Alias usable alias to be used for the chart
	Alias string `json:"alias"`
	// Condition A yaml path that resolves to a boolean, used for enabling/disabling charts (e.g. subchart1.enabled )
	Condition string `json:"condition"`
	// Enabled Enabled bool determines if chart should be loaded
	Enabled bool `json:"enabled"`
	// ImportValues ImportValues holds the mapping of source values to parent key to be imported. Each item can be a string or pair of child/parent sublist items.
	ImportValues []json.RawMessage `json:"import-values"`
	// Name Name is the name of the dependency. This must mach the name in the dependency's Chart.yaml.
	Name string `json:"name"`
	// Repository The URL to the repository. Appending `index.yaml` to this string should result in a URL that can be used to fetch the repository index.
	Repository string `json:"repository"`
	// Tags Tags can be used to group charts for enabling/disabling together
	Tags []string `json:"tags"`
	// Version Version is the version (range) of this chart. A lock file will always produce a single version, while a dependency may contain a semantic version range.
	Version string `json:"version"`
}

type Maintainer struct {
	// Email Email is an optional email address to contact the named maintainer
	Email string `json:"email"`
	// Name Name is a user name or organization name
	Name string `json:"name"`
	// Url URL is an optional URL to an address for the named maintainer
	Url string `json:"url"`
}

type Metadata struct {
	// Annotations Annotations are additional mappings uninterpreted by Helm, made available for inspection by other applications.
	Annotations map[string]string `json:"annotations"`
	// ApiVersion The API Version of this chart. Required.
	ApiVersion string `json:"apiVersion"`
	// AppVersion The version of the application enclosed inside of this chart.
	AppVersion string `json:"appVersion"`
	// Condition The condition to check to enable chart
	Condition string `json:"condition"`
	// Dependencies Dependencies are a list of dependencies for a chart.
	Dependencies []Dependency `json:"dependencies"`
	// Deprecated Whether or not this chart is deprecated
	Deprecated bool `json:"deprecated"`
	// Description A one-sentence description of the chart
	Description string `json:"description"`
	// Home The URL to a relevant project page, git repo, or contact person
	Home string `json:"home"`
	// Icon The URL to an icon file.
	Icon string `json:"icon"`
	// Keywords A list of string keywords
	Keywords []string `json:"keywords"`
	// KubeVersion KubeVersion is a SemVer constraint specifying the version of Kubernetes required.
	KubeVersion string `json:"kubeVersion"`
	// Maintainers A list of name and URL/email address combinations for the maintainer(s)
	Maintainers []Maintainer `json:"maintainers"`
	// Name The name of the chart. Required.
	Name string `json:"name"`
	// Sources Source is the URL to the source code of this chart
	Sources []string `json:"sources"`
	// Tags The tags to check to enable chart
	Tags string `json:"tags"`
	// Type Specifies the chart type: application or library
	Type string `json:"type"`
	// Version A SemVer 2 conformant version string of the chart. Required.
	Version string `json:"version"`
}

type NullTime struct {
	Time string `json:"time"`
	// Valid 标识 Time 是否有效（非 NULL）。Valid is true if Time is not NULL
	Valid bool `json:"valid"`
}

// WebErr Web API 错误响应体，包含错误码、错误信息和错误参数。 Web API error response body, including error code, error message and error params.
type WebErr struct {
	Errcode  int            `json:"errcode"`
	Errmsg   string         `json:"errmsg"`
	Errparam map[string]any `json:"errparam"`
}

// WebError Web API 错误响应体，包含错误码、错误信息和错误参数。 Web API error response body, including error code, error message and error params.
type WebError struct {
	Errcode  int            `json:"errcode"`
	Errmsg   string         `json:"errmsg"`
	Errparam map[string]any `json:"errparam"`
}

// ErrorswebError Web API 错误信息，包含错误码和错误信息。 Web API error info, including error code and error message.
type ErrorswebError struct {
	// Errcode 错误码。Error code.
	Errcode int `json:"errcode"`
	// Errmsg 错误信息。Error message.
	Errmsg string `json:"errmsg"`
}

type CommitStatus struct {
	// Context 提交状态上下文标识符。Commit status context identifier.
	Context string `json:"context"`
	// CreatedAt 创建时间。Created at.
	CreatedAt string `json:"created_at"`
	// Description 提交状态描述信息。Commit status description.
	Description string `json:"description"`
	// State 提交状态。枚举值：`pending`,`success`,`failure`,`error`,`skip`
	State string `json:"state"`
	// TargetUrl 提交状态详情链接。Commit status details link.
	TargetUrl string `json:"target_url"`
	// UpdatedAt 更新时间。Updated at.
	UpdatedAt string `json:"updated_at"`
}

type SceneReaction struct {
	// Count 该表情的数量。Reaction count.
	Count int `json:"count"`
	// HasReacted 当前用户是否已使用该 Reaction。
	HasReacted bool `json:"has_reacted"`
	// Reaction Reaction 表情类型。
	Reaction string `json:"reaction"`
	// TopUsers 最近使用该 Reaction 的用户列表。
	TopUsers []UserInfo `json:"top_users"`
}

type GitInternalAppVcsServiceBffApiCommitStatus struct {
	// Context 状态检查的上下文标识符。Status check context identifier.
	Context string `json:"context"`
	// CreatedAt 创建时间。Created at.
	CreatedAt string `json:"created_at"`
	// Description 状态检查的描述信息。Status check description.
	Description string `json:"description"`
	// State 状态检查结果。Status check result.
	State string `json:"state"`
	// TargetUrl 状态检查的详细信息链接地址。Status check detail link URL.
	TargetUrl string `json:"target_url"`
	// UpdatedAt 最后更新时间。 Last updated at.
	UpdatedAt string `json:"updated_at"`
}

type GitInternalAppVcsServiceBffApiSceneReaction struct {
	// Count 该表情的数量。Reaction count.
	Count int `json:"count"`
	// HasReacted 当前用户是否已使用该 Reaction。
	HasReacted bool `json:"has_reacted"`
	// Reaction Reaction 表情类型。
	Reaction string `json:"reaction"`
	// TopUsers 最近使用该 Reaction 的用户列表。
	TopUsers []UserInfo `json:"top_users"`
}

type MissionFilter struct {
	// Field 属性名。Property name.
	Field *string `json:"field,omitempty"`
	// Operator 筛选符。Filter operator.
	Operator *string `json:"operator,omitempty"`
	// Value 属性值。Property value.
	Value []string `json:"value,omitempty"`
}

// MissionFilterFrom 任务集资源筛选请求，包含筛选条件与需返回的字段列表。 Mission resource filter request, including filter conditions and fields to return.
type MissionFilterFrom struct {
	// Fields Fields 指定需要返回的字段（基于响应中 issue/pull_request 的 JSON key）， 传空或不传则返回全量字段；传入时核心字段（id、repo_slug、number）始终会被返回。
	Fields []string `json:"fields,omitempty"`
	// Selectors 筛选条件列表。Filter selector list.
	Selectors []MissionFilter `json:"selectors,omitempty"`
}

type MissionMissionResourceDtoWebUserInfo struct {
	Nickname string `json:"nickname"`
	Username string `json:"username"`
}

type ArtifactTag struct {
	// Cargo Cargo 制品标签列表。Cargo tags.
	Cargo []CommonRegistryTag `json:"cargo"`
	// Composer Composer 制品标签列表。Composer tags.
	Composer []CommonRegistryTag `json:"composer"`
	// Conan Conan 制品标签列表。Conan tags.
	Conan []CommonRegistryTag `json:"conan"`
	// Docker Docker 制品标签列表。Docker tags.
	Docker []ContainerTag `json:"docker"`
	// Dockermodel Docker 模型制品标签列表。Docker model tags.
	Dockermodel []DockerModelTag `json:"dockermodel"`
	// Generic 通用制品标签列表。Generic tags.
	Generic []CommonRegistryTag `json:"generic"`
	// Helm Helm 制品标签列表。Helm tags.
	Helm []ChartTag `json:"helm"`
	// Maven Maven 制品标签列表。Maven tags.
	Maven []CommonRegistryTag `json:"maven"`
	// Npm Npm 制品标签列表。Npm tags.
	Npm []CommonRegistryTag `json:"npm"`
	// Nuget Nuget 制品标签列表。Nuget tags.
	Nuget []CommonRegistryTag `json:"nuget"`
	// Ohpm Ohpm 制品标签列表。Ohpm tags.
	Ohpm []CommonRegistryTag `json:"ohpm"`
	// Package 制品标识。Artifact identifier.
	Package string `json:"package"`
	// Pypi Pypi 制品标签列表。Pypi tags.
	Pypi []CommonRegistryTag `json:"pypi"`
}
