// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import "encoding/json"

type CommitAnnotation struct {
	// Key 元数据键名。Metadata key.
	Key string `json:"key"`
	// Meta 扩展元数据。 Extended metadata.
	Meta map[string]any `json:"meta"`
	// Value 元数据值。Metadata value.
	Value string `json:"value"`
}

type CommitAnnotationInBatch struct {
	// Annotations 提交元数据列表。 Commit metadata list.
	Annotations []CommitAnnotation `json:"annotations"`
	// CommitHash 提交哈希值。 Commit hash.
	CommitHash string `json:"commit_hash"`
}

type GetCommitAnnotationsInBatchForm struct {
	// CommitHashes 提交哈希值列表。 Commit hash list.
	CommitHashes []string `json:"commit_hashes,omitempty"`
	// Keys 元数据键列表。Metadata key list.
	Keys []string `json:"keys,omitempty"`
}

type IssueResource struct {
	Assignees    []MissionMissionResourceDtoWebUserInfo `json:"assignees"`
	Author       MissionMissionResourceDtoWebUserInfo   `json:"author"`
	ClosedAt     string                                 `json:"closed_at"`
	CommentCount int                                    `json:"comment_count"`
	CreatedAt    string                                 `json:"created_at"`
	EndedAt      string                                 `json:"ended_at"`
	Id           string                                 `json:"id"`
	// Invisible 是否为私密 issue。Whether the issue is private.
	Invisible   bool              `json:"invisible"`
	Labels      []LabelOptionLite `json:"labels"`
	LastActedAt string            `json:"last_acted_at"`
	Number      string            `json:"number"`
	Priority    string            `json:"priority"`
	Properties  []Property        `json:"properties"`
	RepoSlug    string            `json:"repo_slug"`
	StartedAt   string            `json:"started_at"`
	State       string            `json:"state"`
	StateReason string            `json:"state_reason"`
	Title       string            `json:"title"`
	UpdatedAt   string            `json:"updated_at"`
}

type LabelOptionLite struct {
	Color string `json:"color"`
	Id    string `json:"id"`
	Name  string `json:"name"`
	Slug  string `json:"slug"`
}

type MissionField struct {
	InteractionType InteractionType   `json:"interaction_type"`
	Name            string            `json:"name"`
	Operators       []OperatorType    `json:"operators"`
	Value           []json.RawMessage `json:"value"`
}

type MissionResources struct {
	Issues []IssueResource `json:"issues"`
	// NextCursor NextCursor 游标分页：下一页游标（最后一条记录的 id）；无更多数据时为空。
	NextCursor   string                `json:"next_cursor"`
	PullRequests []PullRequestResource `json:"pull_requests"`
	Total        int                   `json:"total"`
}

type Property struct {
	Key   string `json:"key"`
	Name  string `json:"name"`
	Type  string `json:"type"`
	Value string `json:"value"`
}

type PullRequestResource struct {
	Assignees            []MissionMissionResourceDtoWebUserInfo `json:"assignees"`
	Author               MissionMissionResourceDtoWebUserInfo   `json:"author"`
	BaseRepoRef          string                                 `json:"base_repo_ref"`
	BlockedOn            string                                 `json:"blocked_on"`
	CommentCount         int                                    `json:"comment_count"`
	CommitCount          int                                    `json:"commit_count"`
	CreatedAt            string                                 `json:"created_at"`
	FileCount            int                                    `json:"file_count"`
	HeadRepoRef          string                                 `json:"head_repo_ref"`
	Id                   string                                 `json:"id"`
	IsMerged             bool                                   `json:"is_merged"`
	IsReadyForMerge      bool                                   `json:"is_ready_for_merge"`
	Labels               []LabelOptionLite                      `json:"labels"`
	LastActedAt          string                                 `json:"last_acted_at"`
	MergeStyle           string                                 `json:"merge_style"`
	MergeableState       string                                 `json:"mergeable_state"`
	Number               string                                 `json:"number"`
	Properties           []Property                             `json:"properties"`
	RepoSlug             string                                 `json:"repo_slug"`
	Reviewers            []PullRequestResourceReviewer          `json:"reviewers"`
	State                string                                 `json:"state"`
	StatusCheckCommitSha string                                 `json:"status_check_commit_sha"`
	Title                string                                 `json:"title"`
	UpdatedAt            string                                 `json:"updated_at"`
}

type PullRequestResourceReviewer struct {
	Nickname    string `json:"nickname"`
	ReviewState string `json:"review_state"`
	Username    string `json:"username"`
}

type TagAnnotation struct {
	// Key 元数据键名。Metadata key.
	Key string `json:"key"`
	// Meta 元数据信息，用于记录标签元数据的更新操作信息，包括操作者、操作时间、平台来源等审计信息。Tag metadata audit info.
	Meta map[string]any `json:"meta"`
	// Value 元数据值。Metadata value.
	Value string `json:"value"`
}
