// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// NpcObservabilityActions 查询 NPC 调用记录。List NPC actions.
//
// 访问令牌权限: repo-cnb-history:r
//
// CNB API: GET /{repo}/-/npc-observability/actions
func (s *NpcObservabilityService) NpcObservabilityActions(ctx context.Context, repo string, opts *NpcObservabilityActionsOptions) (*NpcActionListResult, *Response, error) {
	u := escapePath("/%s/-/npc-observability/actions", repo)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out NpcActionListResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// NpcObservabilityCommits 查询 NPC push 记录。List NPC commit pushes.
//
// 访问令牌权限: repo-cnb-history:r
//
// CNB API: GET /{repo}/-/npc-observability/commits
func (s *NpcObservabilityService) NpcObservabilityCommits(ctx context.Context, repo string, opts *NpcObservabilityCommitsOptions) (*NpcCommitListResult, *Response, error) {
	u := escapePath("/%s/-/npc-observability/commits", repo)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out NpcCommitListResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// NpcObservabilityPrs 查询 NPC 提交的 PR。List PRs by NPC.
//
// 访问令牌权限: repo-cnb-history:r
//
// CNB API: GET /{repo}/-/npc-observability/prs
func (s *NpcObservabilityService) NpcObservabilityPrs(ctx context.Context, repo string, opts *NpcObservabilityPrsOptions) (*NpcPrListResult, *Response, error) {
	u := escapePath("/%s/-/npc-observability/prs", repo)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out NpcPrListResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}
