// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

// GetRepoAnnualRankOptions 获取公仓年榜。Get annual public repo ranking. 的查询参数.
type GetRepoAnnualRankOptions struct {
	// Language 语言。Programming language.
	Language *string `json:"language,omitempty"`
	// Flags 仓库类型。Repository type. 可选值: KnowledgeBase, NPC, Skills.
	Flags *string `json:"flags,omitempty"`
	// Year 年榜年份，格式为2006，不填默认为本年. Annual ranking year, format 2006, defaults to current year.
	Year *string `json:"year,omitempty"`
	// TopN 排行前n名。Top N in ranking.
	TopN *int `json:"topN,omitempty"`
}

// GetRepoDailyRankOptions 获取公仓日榜。Get daily public repo ranking. 的查询参数.
type GetRepoDailyRankOptions struct {
	// Language 语言。Programming language.
	Language *string `json:"language,omitempty"`
	// Flags 仓库类型。Repository type. 可选值: KnowledgeBase, NPC, Skills.
	Flags *string `json:"flags,omitempty"`
	// Date 日榜日期，默认为昨天. Daily ranking date, defaults to yesterday.
	Date *string `json:"date,omitempty"`
	// TopN 排行前n名。Top N in ranking.
	TopN *int `json:"topN,omitempty"`
}

// GetLanguageListOptions 获取排行榜语言。Get ranking languages. 的查询参数.
type GetLanguageListOptions struct {
	// RankType 排行榜类型。Leaderboard type. 可选值: daily, weekly, monthly, annual.
	RankType *string `json:"rankType,omitempty"`
	// Date 日期。Date.
	Date *string `json:"date,omitempty"`
}

// GetRepoMonthlyRankOptions 获取公仓月榜。Get monthly public repo ranking. 的查询参数.
type GetRepoMonthlyRankOptions struct {
	// Language 语言。Programming language.
	Language *string `json:"language,omitempty"`
	// Flags 仓库类型。Repository type. 可选值: KnowledgeBase, NPC, Skills.
	Flags *string `json:"flags,omitempty"`
	// Month 月榜月份，格式为200601，不填默认为本月. Monthly ranking month, format 200601, defaults to current month.
	Month *string `json:"month,omitempty"`
	// TopN 排行前n名。Top N in ranking.
	TopN *int `json:"topN,omitempty"`
}

// GetRepoWeeklyRankOptions 获取公仓周榜。Get weekly public repo ranking. 的查询参数.
type GetRepoWeeklyRankOptions struct {
	// Language 语言。Programming language.
	Language *string `json:"language,omitempty"`
	// Flags 仓库类型。Repository type. 可选值: KnowledgeBase, NPC, Skills.
	Flags *string `json:"flags,omitempty"`
	// Start 周榜周一日期，格式为20060102，不填默认为本周. Weekly ranking Monday date, format 20060102, defaults to current week.
	Start *string `json:"start,omitempty"`
	// TopN 排行前n名。Top N in ranking.
	TopN *int `json:"topN,omitempty"`
}

// SearchNpcOptions 搜索 NPC 角色。Search NPC characters. 的查询参数.
type SearchNpcOptions struct {
	// Key 搜索关键词。Search keyword.
	Key *string `json:"key,omitempty"`
	// TopN 返回结果数量，最大20。Number of results to return, max 20.
	TopN *int `json:"top_n,omitempty"`
}

// ListPublicReposOptions 搜索资源。Search resources. 的查询参数.
type ListPublicReposOptions struct {
	// Key 键名。Key name.
	Key *string `json:"key,omitempty"`
	// Flags 仓库类型标记，逗号分隔。Repository type flags, comma separated 可选值: KnowledgeBase, NPC, Skills.
	Flags *string `json:"flags,omitempty"`
	// FlagsMatch flags 多值匹配模式。Flags match mode when multiple flags provided 可选值: intersection, union.
	FlagsMatch *string `json:"flags_match,omitempty"`
	// OrderBy 排序类型，默认last_updated_at. Sort type, defaults to last_updated_at. 可选值: created_at, last_updated_at, stars, forks.
	OrderBy *string `json:"order_by,omitempty"`
	// Desc 排序顺序。Sort order.
	Desc *bool `json:"desc,omitempty"`
	// TopN 排行前N位，默认10，最大值100。Top N in ranking, default 10, max 100.
	TopN *int `json:"topN,omitempty"`
}

// AutoCompleteSourceOptions 查询用户资源列表。List user resources. 的查询参数.
type AutoCompleteSourceOptions struct {
	ListOptions `json:",inline"`
	// SourceType 来源类型。Source type. 可选值: Group, Repo, RootGroup.
	SourceType *string `json:"source_type,omitempty"`
	// Search 按资源筛选。Filter by resources.
	Search *string `json:"search,omitempty"`
	// Access 最小仓库权限，默认owner。Minima repository permissions 可选值: Guest, Reporter, Developer, Master, Owner.
	Access *string `json:"access,omitempty"`
	// OrderBy 排序字段。Order field. 可选值: created_at, slug_path.
	OrderBy *string `json:"order_by,omitempty"`
	// Desc 排序顺序。Ordering.
	Desc *bool `json:"desc,omitempty"`
}

// ListGPGKeysOptions 查询用户 GPG 密钥列表。List user GPG keys. 的查询参数.
type ListGPGKeysOptions struct {
	ListOptions `json:",inline"`
	// Keyword GPG 搜索关键字。GPG search key.
	Keyword *string `json:"keyword,omitempty"`
}

// ListTopGroupsOptions 获取顶层组织列表。Get top-level organizations. 的查询参数.
type ListTopGroupsOptions struct {
	ListOptions `json:",inline"`
	// Search 按组织筛选。Filter by organizations.
	Search *string `json:"search,omitempty"`
	// Role 按角色筛选。Filter by role. 可选值: Guest, Reporter, Developer, Master, Owner.
	Role *string `json:"role,omitempty"`
}

// ListGroupsOptions 查询子组织列表。Get sub-organizations. 的查询参数.
type ListGroupsOptions struct {
	ListOptions `json:",inline"`
	// Access 访问权限级别。Access level.
	Access *int `json:"access,omitempty"`
}

// ListUserIssuesOptions 查询我的 Issue 列表。List my issues. 的查询参数.
type ListUserIssuesOptions struct {
	ListOptions `json:",inline"`
	// Filter Issue筛选类型。可选值：`created`（我创建的）、`assigned`（分配给我的）
	Filter *string `json:"filter,omitempty"`
	// State Issue状态过滤。可选值：`open`、`closed`
	State *string `json:"state,omitempty"`
	// Priority Issue优先级过滤。示例：`-2P,-1P,P0,P1,P2,P3`
	Priority *string `json:"priority,omitempty"`
	// Labels Issue标签过滤。示例：`git,bug,feature`
	Labels *string `json:"labels,omitempty"`
	// LabelsOperator 标签过滤操作符。可选值：`contains_any`,`contains_all`
	LabelsOperator *string `json:"labels_operator,omitempty"`
	// UpdatedTimeBegin Issue更新时间范围开始。示例：`2022-01-31`
	UpdatedTimeBegin *string `json:"updated_time_begin,omitempty"`
	// UpdatedTimeEnd Issue更新时间范围结束。示例：`2022-02-16`
	UpdatedTimeEnd *string `json:"updated_time_end,omitempty"`
	// CloseTimeBegin Issue关闭时间范围开始。示例：`2022-01-31`
	CloseTimeBegin *string `json:"close_time_begin,omitempty"`
	// CloseTimeEnd Issue关闭时间范围结束。示例：`2022-02-16`
	CloseTimeEnd *string `json:"close_time_end,omitempty"`
	// CreatedTimeBegin Issue创建时间范围开始。示例：`2022-01-31`
	CreatedTimeBegin *string `json:"created_time_begin,omitempty"`
	// CreatedTimeEnd Issue创建时间范围结束。示例：`2022-02-16`
	CreatedTimeEnd *string `json:"created_time_end,omitempty"`
	// OrderBy Issue排序字段，-前缀表示倒序。可选值：`created_at`,`-created_at`,`-updated_at`
	OrderBy *string `json:"order_by,omitempty"`
}

// GetReposOptions 获取我的仓库。List my repositories. 的查询参数.
type GetReposOptions struct {
	ListOptions `json:",inline"`
	// Search 按仓库筛选。Filter by repositories.
	Search *string `json:"search,omitempty"`
	// FilterType 仓库类型。Repository type. 可选值: private, public, secret.
	FilterType *string `json:"filter_type,omitempty"`
	// Role 最小仓库权限，默认owner。Minima repository permissions 可选值: Guest, Reporter, Developer, Master, Owner.
	Role *string `json:"role,omitempty"`
	// Flags 仓库类型标记，逗号分隔。Repository type flags, comma separated 可选值: KnowledgeBase, NPC, Skills.
	Flags *string `json:"flags,omitempty"`
	// FlagsMatch flags 多值匹配模式。Flags match mode when multiple flags provided 可选值: intersection, union.
	FlagsMatch *string `json:"flags_match,omitempty"`
	// Status 仓库状态。Repository status 可选值: active, archived.
	Status *string `json:"status,omitempty"`
	// OrderBy 排序字段。Order field. 可选值: created_at, last_updated_at, stars, slug_path, forks.
	OrderBy *string `json:"order_by,omitempty"`
	// Desc 排序顺序。Ordering.
	Desc *bool `json:"desc,omitempty"`
}

// GetUserAllStaredReposOptions 获取 Star 仓库列表。List starred repositories. 的查询参数.
type GetUserAllStaredReposOptions struct {
	ListOptions `json:",inline"`
	// Search 按仓库筛选。Filter by repositories.
	Search *string `json:"search,omitempty"`
	// Flags 仓库类型标记，逗号分隔。Repository type flags, comma separated 可选值: KnowledgeBase, NPC, Skills.
	Flags *string `json:"flags,omitempty"`
	// FlagsMatch flags 多值匹配模式。Flags match mode when multiple flags provided 可选值: intersection, union.
	FlagsMatch *string `json:"flags_match,omitempty"`
	// Status 仓库状态。Repository status 可选值: active, archived.
	Status *string `json:"status,omitempty"`
	// Desc 排序顺序。Ordering.
	Desc *bool `json:"desc,omitempty"`
	// OrderBy 排序字段。Order field. 可选值: created_at, last_updated_at, stared_time, stars, forks.
	OrderBy *string `json:"order_by,omitempty"`
}

// GetUserActivitiesByDateOptions 获取动态活跃详情。Get user activities. 的查询参数.
type GetUserActivitiesByDateOptions struct {
	// Date 查询日期，格式 yyyyMM，或者 yyyyMMdd. Query date, format yyyyMM or yyyyMMdd.
	Date *string `json:"date,omitempty"`
}

// GetUserCalendarOptions 获取活跃点日历。Get activity calendar. 的查询参数.
type GetUserCalendarOptions struct {
	// Year 查询日期，格式 yyyy，不指定时查询最近一年. Query date, format yyyy, defaults to the past year.
	Year *string `json:"year,omitempty"`
}

// GetFollowersByUserIDOptions 获取粉丝列表。Get followers list. 的查询参数.
type GetFollowersByUserIDOptions struct {
	ListOptions `json:",inline"`
}

// GetFollowingByUserIDOptions 获取关注人列表。Get following list. 的查询参数.
type GetFollowingByUserIDOptions struct {
	ListOptions `json:",inline"`
}

// GetGroupsByUserIDOptions 获取用户顶层组织。Get user top-level organizations. 的查询参数.
type GetGroupsByUserIDOptions struct {
	ListOptions `json:",inline"`
	// Search 按组织筛选。Filter organizations.
	Search *string `json:"search,omitempty"`
}

// GetUserRepoActivityDetailsOptions 获取仓库动态详情。Get repository activity details. 的查询参数.
type GetUserRepoActivityDetailsOptions struct {
	// Slug 仓库路径. Repository path.
	Slug *string `json:"slug,omitempty"`
	// Date 查询日期，格式 yyyyMM，或者 yyyyMMdd. Query date, format yyyyMM or yyyyMMdd.
	Date *string `json:"date,omitempty"`
}

// GetReposByUserNameOptions 获取用户可见仓库。List user visible repositories. 的查询参数.
type GetReposByUserNameOptions struct {
	ListOptions `json:",inline"`
	// Search 按仓库筛选。Filter by repositories.
	Search *string `json:"search,omitempty"`
	// FilterType 仓库类型。Repositories type. 可选值: private, public, secret.
	FilterType *string `json:"filter_type,omitempty"`
	// Flags 仓库类型标记，逗号分隔。Repository type flags, comma separated 可选值: KnowledgeBase, NPC, Skills.
	Flags *string `json:"flags,omitempty"`
	// FlagsMatch flags 多值匹配模式。Flags match mode when multiple flags provided 可选值: intersection, union.
	FlagsMatch *string `json:"flags_match,omitempty"`
	// Status 仓库状态。Repository status 可选值: active, archived.
	Status *string `json:"status,omitempty"`
	// Role 最小仓库权限，默认owner。Minima repository permissions. 可选值: Guest, Reporter, Developer, Master, Owner.
	Role *string `json:"role,omitempty"`
	// Desc 排序顺序。Ordering.
	Desc *bool `json:"desc,omitempty"`
	// OrderBy 排序字段。Order field. 可选值: created_at, last_updated_at, stars, slug_path, forks.
	OrderBy *string `json:"order_by,omitempty"`
}

// GetUserStaredReposOptions 获取用户 Star 仓库。Get user starred repositories. 的查询参数.
type GetUserStaredReposOptions struct {
	ListOptions `json:",inline"`
	// Search 过滤仓库。Filter by repositories
	Search *string `json:"search,omitempty"`
	// Flags 仓库类型标记，逗号分隔。Repository type flags, comma separated 可选值: KnowledgeBase, NPC, Skills.
	Flags *string `json:"flags,omitempty"`
	// FlagsMatch flags 多值匹配模式。Flags match mode when multiple flags provided 可选值: intersection, union.
	FlagsMatch *string `json:"flags_match,omitempty"`
	// Status 仓库状态。Repository status 可选值: active, archived.
	Status *string `json:"status,omitempty"`
	// Desc 排序顺序。Ordering.
	Desc *bool `json:"desc,omitempty"`
	// OrderBy 排序字段。Order field. 可选值: created_at, last_updated_at, stars, forks.
	OrderBy *string `json:"order_by,omitempty"`
}

// ListWorkspacesOptions 获取我的云原生开发环境列表。List my workspaces. 的查询参数.
type ListWorkspacesOptions struct {
	ListOptions `json:",inline"`
	// Branch Git分支名，例如 "main"。Git branch name, e.g. "main"
	Branch *string `json:"branch,omitempty"`
	// End 查询结束时间。Query end time. format YYYY-MM-DD HH:mm:ssZZ, e.g. 2024-12-01 00:00:00+0800
	End *string `json:"end,omitempty"`
	// Slug 仓库路径，例如 "groupname/reponame"。Repository path, e.g. "groupname/reponame"
	Slug *string `json:"slug,omitempty"`
	// Start 查询开始时间。Query start time. format YYYY-MM-DD HH:mm:ssZZ, e.g. 2024-12-01 00:00:00+0800
	Start *string `json:"start,omitempty"`
	// Status 开发环境状态，running: 开发环境已启动，closed：开发环境已关闭。Workspace status: "running" for started, "closed" for stopped.
	Status *string `json:"status,omitempty"`
}

// ListInheritMembersOfGroupOptions 获取继承成员。List inherited members. 的查询参数.
type ListInheritMembersOfGroupOptions struct {
	ListOptions `json:",inline"`
	// Search 过滤成员。Filter by member
	Search *string `json:"search,omitempty"`
	// Role 角色。Role. 可选值: Guest, Reporter, Developer, Master, Owner.
	Role *string `json:"role,omitempty"`
}

// ListMembersOfGroupOptions 获取组织直接成员列表。List organization direct members. 的查询参数.
type ListMembersOfGroupOptions struct {
	ListOptions `json:",inline"`
	// Role 角色。Role. 可选值: Guest, Reporter, Developer, Master, Owner.
	Role *string `json:"role,omitempty"`
	// Search 过滤成员。Filter by member.
	Search *string `json:"search,omitempty"`
}

// GetMemberAccessLevelOfGroupOptions 获取访问成员权限。Get access member permissions. 的查询参数.
type GetMemberAccessLevelOfGroupOptions struct {
	// IncludeInherit 是否包含继承的权限。If inherited permissions are included.
	IncludeInherit *bool `json:"include_inherit,omitempty"`
}

// ListMissionFieldsOpenAPIOptions 获取任务集属性。Get mission fields. 的查询参数.
type ListMissionFieldsOpenAPIOptions struct {
	// Type 资源类型，issues或pull_requests。Resource type, issues or pull_requests.
	Type *string `json:"type,omitempty"`
}

// ListMissionResourcesOpenAPIOptions 查询任务集资源列表。Query mission resources. 的查询参数.
type ListMissionResourcesOpenAPIOptions struct {
	// Cursor 游标分页：传 next_cursor 拉下一页；首页传空。Cursor: next_cursor for next page; empty for 1st.
	Cursor *string `json:"cursor,omitempty"`
}

// GetMissionViewConfigOptions 查询任务集视图配置信息。Get mission view config. 的查询参数.
type GetMissionViewConfigOptions struct {
	// Id 视图ID。View ID.
	Id *string `json:"id,omitempty"`
}

// GetBuildLogsOptions 查询流水线构建列表。List pipeline builds. 的查询参数.
type GetBuildLogsOptions struct {
	ListOptions `json:",inline"`
	// CreateTime 起始日期，格式 "YYYY-MM-DD"，例如 "2024-12-01"。Start date in "YYYY-MM-DD" format, e.g. "2024-12-01"
	CreateTime *string `json:"createTime,omitempty"`
	// EndTime 结束日期，格式 "YYYY-MM-DD"，例如 "2024-12-01"。End date in "YYYY-MM-DD" format, e.g. "2024-12-01"
	EndTime *string `json:"endTime,omitempty"`
	// Event 事件名称，例如 "push"。Event name, e.g. "push"
	Event *string `json:"event,omitempty"`
	// Sha 提交ID。Commit ID.
	Sha *string `json:"sha,omitempty"`
	// Sn 构建序列号，例如 "cnb-1qa-1i3f5ecau"。Build SN, e.g. "cnb-1qa-1i3f5ecau"
	Sn *string `json:"sn,omitempty"`
	// SourceRef 源分支名称，例如 "dev"。Source branch name, e.g. "dev"
	SourceRef *string `json:"sourceRef,omitempty"`
	// Status 构建状态："pending"、"success"、"error"、"cancel"。Build status: "pending", "success", "error", "cancel"
	Status *string `json:"status,omitempty"`
	// TargetRef 目标分支名称，例如 "main"。Target branch name, e.g. "main"
	TargetRef *string `json:"targetRef,omitempty"`
	// UserId 用户ID。User ID.
	UserId *string `json:"userId,omitempty"`
	// UserName 用户名。Username.
	UserName *string `json:"userName,omitempty"`
}

// GetCommitAssetsOptions 下载 Commit 附件。Download commit attachments. 的查询参数.
type GetCommitAssetsOptions struct {
	// Share 是否可下载;302跳转12h有效最多10次。Downloadable;302 valid 12h,max 10 downloads.
	Share *bool `json:"share,omitempty"`
}

// ListForksReposOptions 获取仓库 Fork 列表。Get repository fork list. 的查询参数.
type ListForksReposOptions struct {
	ListOptions `json:",inline"`
	// StartFromRoot 是否从fork根节点开始展示。Whether to start from the root node of the fork.
	StartFromRoot *bool `json:"start_from_root,omitempty"`
}

// ListBranchesOptions 查询分支列表。List branches. 的查询参数.
type ListBranchesOptions struct {
	ListOptions `json:",inline"`
	// Query 分支名称关键字，按分支名过滤。Branch name keyword, filter by branch name.
	Query *string `json:"query,omitempty"`
}

// PostCommitAssetUploadConfirmationOptions 确认提交附件上传。Confirm commit asset upload. 的查询参数.
type PostCommitAssetUploadConfirmationOptions struct {
	// Ttl 附件保持的天数。0 表示永久，最大不能超过 180 天. Attachment retention days. 0 means permanent, max 180 days.
	Ttl *int `json:"ttl,omitempty"`
}

// ListCommitsOptions 查询提交列表。List commits. 的查询参数.
type ListCommitsOptions struct {
	ListOptions `json:",inline"`
	// Sha 提交标识符。格式：`分支名称`,`提交哈希值`. Commit identifier. Format: `branch_name`,`commit_hash`
	Sha *string `json:"sha,omitempty"`
	// Author 作者匹配模式，支持Git原生正则表达式匹配作者信息。
	Author *string `json:"author,omitempty"`
	// Committer 提交者匹配模式，支持Git原生正则表达式匹配提交者信息。
	Committer *string `json:"committer,omitempty"`
	// Since 提交时间起始范围。示例：`2025-01-01T00:00:00Z`. Commit time range start. Example: `2025-01-01T00:00:00Z`
	Since *string `json:"since,omitempty"`
	// Until 提交时间结束范围。示例：`2025-12-31T23:59:59Z`. Commit time range end. Example: `2025-12-31T23:59:59Z`
	Until *string `json:"until,omitempty"`
}

// GetContentWithoutPathOptions 查询仓库根目录内容。Get repository root contents. 的查询参数.
type GetContentWithoutPathOptions struct {
	// Ref 提交的哈希值或分支名称。Commit hash or branch name.
	Ref *string `json:"ref,omitempty"`
}

// GetContentOptions 查询仓库文件内容。Get repository file content. 的查询参数.
type GetContentOptions struct {
	// Ref 提交的哈希值或分支名称。Commit hash or branch name.
	Ref *string `json:"ref,omitempty"`
}

// GetRawOptions 获取文件原始内容。Get raw file content. 的查询参数.
type GetRawOptions struct {
	// MaxInByte 获得文件内容大小限制（字节），0表示使用gitConfig.RawFileLimitInByte配置值。
	MaxInByte *int `json:"max_in_byte,omitempty"`
}

// ListTagsOptions 查询标签列表。List tags. 的查询参数.
type ListTagsOptions struct {
	ListOptions `json:",inline"`
}

// ListInheritMembersOfRepoOptions 获取继承成员。List inherited members. 的查询参数.
type ListInheritMembersOfRepoOptions struct {
	ListOptions `json:",inline"`
	// Search 过滤成员。Filter by member
	Search *string `json:"search,omitempty"`
	// Role 角色。Role. 可选值: Guest, Reporter, Developer, Master, Owner.
	Role *string `json:"role,omitempty"`
}

// ListIssuesOptions 查询仓库 Issue 列表。List repository issues. 的查询参数.
type ListIssuesOptions struct {
	ListOptions `json:",inline"`
	// State Issue状态过滤。可选值：`open`、`closed`
	State *string `json:"state,omitempty"`
	// Keyword Issue搜索关键词，支持在标题和内容中模糊搜索。
	Keyword *string `json:"keyword,omitempty"`
	// Priority Issue优先级过滤。示例：`-2P,-1P,P0,P1,P2,P3`
	Priority *string `json:"priority,omitempty"`
	// Labels Issue标签过滤。示例：`git,bug,feature`
	Labels *string `json:"labels,omitempty"`
	// LabelsOperator 标签过滤操作符。可选值：`contains_any`,`contains_all`
	LabelsOperator *string `json:"labels_operator,omitempty"`
	// Authors Issue创建者过滤，多个作者用英文逗号分隔。示例：`张三,李四`
	Authors *string `json:"authors,omitempty"`
	// Assignees Issue处理人过滤，多个处理人用英文逗号分隔，-表示未分配处理人。示例：`张三,李四`,`-`
	Assignees *string `json:"assignees,omitempty"`
	// UpdatedTimeBegin Issue更新时间范围开始。示例：`2022-01-31`
	UpdatedTimeBegin *string `json:"updated_time_begin,omitempty"`
	// UpdatedTimeEnd Issue更新时间范围结束。示例：`2022-02-16`
	UpdatedTimeEnd *string `json:"updated_time_end,omitempty"`
	// CloseTimeBegin Issue关闭时间范围开始。示例：`2022-01-31`
	CloseTimeBegin *string `json:"close_time_begin,omitempty"`
	// CloseTimeEnd Issue关闭时间范围结束。示例：`2022-02-16`
	CloseTimeEnd *string `json:"close_time_end,omitempty"`
	// OrderBy Issue排序字段，-前缀表示倒序。可选值：`created_at`,`-created_at`,`-updated_at`,`-last_acted_at`
	OrderBy *string `json:"order_by,omitempty"`
}

// ListIssueActivitiesOptions 查询 Issue 动态。List issue activities. 的查询参数.
type ListIssueActivitiesOptions struct {
	ListOptions `json:",inline"`
}

// ListIssueCommentsOptions 查询 Issue 评论。List issue comments. 的查询参数.
type ListIssueCommentsOptions struct {
	ListOptions `json:",inline"`
	// Sort 排序方式。支持 created, updated 升序; -created, -updated 降序
	Sort *string `json:"sort,omitempty"`
}

// ListIssueLabelsOptions 查询 Issue 标签。List issue labels. 的查询参数.
type ListIssueLabelsOptions struct {
	ListOptions `json:",inline"`
}

// QueryKnowledgeBaseGetOptions 查询知识库。Query knowledge base. 的查询参数.
type QueryKnowledgeBaseGetOptions struct {
	// Query 查询语句。Query text.
	Query *string `json:"query,omitempty"`
	// TopK 返回结果数量，默认 5。Number of results to return, default 5.
	TopK *int `json:"top_k,omitempty"`
	// ScoreThreshold 分数阈值，默认 0。Score threshold, default 0.
	ScoreThreshold *float64 `json:"score_threshold,omitempty"`
	// MetadataFilteringConditions 元数据过滤条件，JSON 字符串
	MetadataFilteringConditions *string `json:"metadata_filtering_conditions,omitempty"`
}

// ListLabelsOptions 查询仓库标签列表。List repository labels. 的查询参数.
type ListLabelsOptions struct {
	ListOptions `json:",inline"`
	// Keyword 标签搜索关键词，支持模糊匹配。Label search keyword, supports fuzzy matching.
	Keyword *string `json:"keyword,omitempty"`
}

// ListMembersOfRepoOptions 获取仓库直接成员列表。List repository direct members. 的查询参数.
type ListMembersOfRepoOptions struct {
	ListOptions `json:",inline"`
	// Role 角色。Role. 可选值: Guest, Reporter, Developer, Master, Owner.
	Role *string `json:"role,omitempty"`
	// Search 过滤成员。Filter by member.
	Search *string `json:"search,omitempty"`
}

// GetMemberAccessLevelOfRepoOptions 获取成员访问权限。Get member access level. 的查询参数.
type GetMemberAccessLevelOfRepoOptions struct {
	// IncludeInherit 是否包含继承的权限。If inherited permissions are included.
	IncludeInherit *bool `json:"include_inherit,omitempty"`
}

// NpcObservabilityActionsOptions 查询 NPC 调用记录。List NPC actions. 的查询参数.
type NpcObservabilityActionsOptions struct {
	ListOptions `json:",inline"`
	// EndTime 结束时间，ISO8601 格式，默认当前时间；与 start_time 跨度 ≤ 90 天。End time in ISO8601, default now. Range <= 90 days.
	EndTime *string `json:"end_time,omitempty"`
	// Event 事件类型，仅支持 "issue.comment@npc" 与 "pull_request.comment@npc"。Event type.
	Event *string `json:"event,omitempty"`
	// NpcName NPC 角色名。NPC role name.
	NpcName *string `json:"npc_name,omitempty"`
	// NpcSlug NPC 仓库 slug。NPC repo slug.
	NpcSlug *string `json:"npc_slug,omitempty"`
	// StartTime 起始时间，ISO8601 格式，例如 "2026-06-10T00:00:00Z"，默认 7 天前。Start time in ISO8601, default 7 days ago.
	StartTime *string `json:"start_time,omitempty"`
	// TriggerUsername 评论作者用户名。Comment author username.
	TriggerUsername *string `json:"trigger_username,omitempty"`
}

// NpcObservabilityCommitsOptions 查询 NPC push 记录。List NPC commit pushes. 的查询参数.
type NpcObservabilityCommitsOptions struct {
	ListOptions `json:",inline"`
	// EndTime 结束时间，ISO8601 格式，默认当前；与 start_time 跨度 ≤ 90 天。End time in ISO8601, default now. Range <= 90 days.
	EndTime *string `json:"end_time,omitempty"`
	// NpcName NPC 角色名。NPC role name.
	NpcName *string `json:"npc_name,omitempty"`
	// NpcSlug NPC 仓库 slug。NPC repo slug.
	NpcSlug *string `json:"npc_slug,omitempty"`
	// StartTime 起始时间，ISO8601 格式，默认 7 天前。Start time in ISO8601, default 7 days ago.
	StartTime *string `json:"start_time,omitempty"`
}

// NpcObservabilityPrsOptions 查询 NPC 提交的 PR。List PRs by NPC. 的查询参数.
type NpcObservabilityPrsOptions struct {
	ListOptions `json:",inline"`
	// EndTime 结束时间，按 PR 创建时间过滤；与 start_time 跨度 ≤ 90 天。End time.
	EndTime *string `json:"end_time,omitempty"`
	// NpcName NPC 角色名。NPC role name.
	NpcName *string `json:"npc_name,omitempty"`
	// NpcSlug NPC 仓库 slug。NPC repo slug.
	NpcSlug *string `json:"npc_slug,omitempty"`
	// StartTime 起始时间，按 PR 创建时间过滤。Start time, filter by PR creation time.
	StartTime *string `json:"start_time,omitempty"`
	// State PR 状态：open / merged / closed。PR state.
	State *string `json:"state,omitempty"`
}

// ListRepoInvisiblePropertiesOptions 查询仓库隐藏自定义属性。Get hidden custom properties. 的查询参数.
type ListRepoInvisiblePropertiesOptions struct {
	ListOptions `json:",inline"`
	// Keyword 搜索关键字。Search keyword.
	Keyword *string `json:"keyword,omitempty"`
}

// ListPullsByNumbersOptions 批量查询合并请求。Batch get pull requests. 的查询参数.
type ListPullsByNumbersOptions struct {
	// N Pull唯一标识编号
	N []int `json:"n,omitempty"`
}

// ListPullsOptions 查询合并请求列表。List pull requests. 的查询参数.
type ListPullsOptions struct {
	ListOptions `json:",inline"`
	// State 合并请求状态过滤。可选值：`open`,`closed`,`all`
	State *string `json:"state,omitempty"`
	// Authors 作者名称过滤。示例值：`张三,李四`. Author name filter. Example: `Zhang San,Li Si`
	Authors *string `json:"authors,omitempty"`
	// Reviewers 评审人名称过滤，-表示无评审人。示例值：`张三,李四`,`-`. Reviewer name filter, - means no reviewer. Example: `Zhang San,Li Si`,`-`
	Reviewers *string `json:"reviewers,omitempty"`
	// ReviewersOperator 评审者操作符。示例值：`contains_any`,`contains_all`
	ReviewersOperator *string `json:"reviewers_operator,omitempty"`
	// Assignees 处理人名称过滤，-表示无处理人。示例值：`张三,李四`,`-`. Assignee name filter, - means no assignee. Example: `Zhang San,Li Si`,`-`
	Assignees *string `json:"assignees,omitempty"`
	// AssigneesOperator 处理人操作符。示例值：`contains_any`,`contains_all`
	AssigneesOperator *string `json:"assignees_operator,omitempty"`
	// Labels 标签过滤。示例值：`git,bug,feature`
	Labels *string `json:"labels,omitempty"`
	// LabelsOperator 标签操作符。示例值：`contains_any`,`contains_all`
	LabelsOperator *string `json:"labels_operator,omitempty"`
	// BaseRef 目标分支引用。示例值：`master`
	BaseRef *string `json:"base_ref,omitempty"`
	// UpdatedTimeBegin 合并请求更新时间范围开始。示例：`2022-01-31`. PR update time range start. Example: `2022-01-31`
	UpdatedTimeBegin *string `json:"updated_time_begin,omitempty"`
	// UpdatedTimeEnd 合并请求更新时间范围结束。示例：`2022-02-16`. PR update time range end. Example: `2022-02-16`
	UpdatedTimeEnd *string `json:"updated_time_end,omitempty"`
	// OrderBy 合并请求排序字段，-前缀表示倒序。可选值：`created_at`,`-created_at`,`-updated_at`
	OrderBy *string `json:"order_by,omitempty"`
}

// ListPullCommentsOptions 查询合并请求评论列表。List pull request comments. 的查询参数.
type ListPullCommentsOptions struct {
	ListOptions `json:",inline"`
}

// ListPullCommitsOptions 查询合并请求提交列表。List pull request commits. 的查询参数.
type ListPullCommitsOptions struct {
	ListOptions `json:",inline"`
}

// ListPullLabelsOptions 查询合并请求标签。List pull request labels. 的查询参数.
type ListPullLabelsOptions struct {
	ListOptions `json:",inline"`
}

// ListPullReviewsOptions 查询合并请求评审列表。List pull request reviews. 的查询参数.
type ListPullReviewsOptions struct {
	ListOptions `json:",inline"`
}

// ListPullReviewCommentsOptions 查询评审评论列表。List review comments. 的查询参数.
type ListPullReviewCommentsOptions struct {
	ListOptions `json:",inline"`
}

// ListReleasesOptions 查询版本列表。List releases. 的查询参数.
type ListReleasesOptions struct {
	ListOptions `json:",inline"`
}

// GetReleasesAssetOptions 下载 Release 附件。Download release attachments. 的查询参数.
type GetReleasesAssetOptions struct {
	// Share 是否可下载;302跳转12h有效最多10次。Downloadable;302 valid 12h,max 10 downloads.
	Share *bool `json:"share,omitempty"`
}

// PostReleaseAssetUploadConfirmationOptions 确认附件上传。Confirm asset upload. 的查询参数.
type PostReleaseAssetUploadConfirmationOptions struct {
	// Ttl 附件保持的天数。0 表示永久，最大不能超过 180 天. Attachment retention days. 0 means permanent, max 180 days.
	Ttl *int `json:"ttl,omitempty"`
}

// GetRepoSecurityOverviewOptions 查询仓库安全概览。Get repository security overview. 的查询参数.
type GetRepoSecurityOverviewOptions struct {
	// Types 类型:code_sensitive,code_vulnerability,code_issue,code_license;空=全部。Types: comma-sep;empty=all.
	Types *string `json:"types,omitempty"`
	// Tab 查询类型下开启或忽略的各风险类型概览数量,可选值：open,ignore,all，默认all。Risk status filter: open, ignore, all; default all.
	Tab *string `json:"tab,omitempty"`
}

// TopContributorsOptions 获取仓库 top 活跃用户。List the top active users. 的查询参数.
type TopContributorsOptions struct {
	// Top 返回的用户个数。Number of users to return.
	Top *int `json:"top,omitempty"`
}

// GetReposVolumeOptions 获取组织仓库用量。Get organization repository usage. 的查询参数.
type GetReposVolumeOptions struct {
	ListOptions `json:",inline"`
	// Type 资源类型. Resource type. 可选值: charge_type_git, charge_type_object, charge_type_ci, charge_type_dev, charge_type_ci_gpu, charge_type_dev_gpu, charge_type_credit, charge_type_token.
	Type *string `json:"type,omitempty"`
}

// GetVolumeOptions 获取组织资源用量。Get organization resource usage. 的查询参数.
type GetVolumeOptions struct {
	// Month 月份，默认是当前月份. Month, defaults to current month.
	Month *string `json:"month,omitempty"`
}

// ListCodeIssueOpenAPIOptions 查询代码扫描问题列表。List code scan issues. 的查询参数.
type ListCodeIssueOpenAPIOptions struct {
	ListOptions `json:",inline"`
	// IssueRule 问题规则，用于筛选特定类型的问题。示例值：`critical-risk`, `LIC_CRITICAL`, `VUL_CRITICAL`
	IssueRule *string `json:"issue_rule,omitempty"`
	// RiskLevel 严重程度，用于筛选特定风险等级的问题。枚举值：`info`, `warning`, `error`, `fatal`, `all`
	RiskLevel *string `json:"risk_level,omitempty"`
}

// GetRepoContributorTrendOptions 查询贡献者趋势数据。Get contributor trend data. 的查询参数.
type GetRepoContributorTrendOptions struct {
	// Limit 查询结果数量限制，当limit小于0时，默认为15。格式：[0,100]
	Limit *int `json:"limit,omitempty"`
	// ExcludeExternalUsers 是否排除外部用户。示例值：`true`,`false`
	ExcludeExternalUsers *bool `json:"exclude_external_users,omitempty"`
}

// GetPresignedLFSDownloadLinkOptions 获取 LFS 文件下载链接。Get LFS file download URL. 的查询参数.
type GetPresignedLFSDownloadLinkOptions struct {
	// Name LFS文件名称。未提供时默认使用oid作为文件名。
	Name *string `json:"name,omitempty"`
}

// ListAssetsOptions 获取仓库 asset 记录列表。Get repository asset records. 的查询参数.
type ListAssetsOptions struct {
	ListOptions `json:",inline"`
}

// ListAllMembersOptions 获取仓库有效成员列表。List repository active members. 的查询参数.
type ListAllMembersOptions struct {
	ListOptions `json:",inline"`
	// Role 角色。Role. 可选值: Guest, Reporter, Developer, Master, Owner.
	Role *string `json:"role,omitempty"`
	// Search 过滤成员。Filter by member
	Search *string `json:"search,omitempty"`
	// Names 精准匹配用户名,多个用户名用逗号间隔。Exact username matching, multiple usernames separated by commas.
	Names *string `json:"names,omitempty"`
	// OrderBy 排序字段。Order field. 可选值: created_at, stars, follower.
	OrderBy *string `json:"order_by,omitempty"`
	// Desc 排序顺序。Ordering.
	Desc *bool `json:"desc,omitempty"`
}

// GetGroupSubMissionsOptions 查询我的任务集。List my missions. 的查询参数.
type GetGroupSubMissionsOptions struct {
	ListOptions `json:",inline"`
	// FilterType 任务集类型。Mission type. 可选值: private, public.
	FilterType *string `json:"filter_type,omitempty"`
	// OrderBy 排序类型，默认created_at。Sort order, default created_at. 可选值: created_at, name.
	OrderBy *string `json:"order_by,omitempty"`
	// Desc 排序顺序。Sort order.
	Desc *bool `json:"desc,omitempty"`
	// Descendant 查询范围:全部/当前组织/子组织仓库。Query scope: all/current org/sub-org repos. 可选值: all, sub, grand.
	Descendant *string `json:"descendant,omitempty"`
	// Search 搜索关键字。Search keyword.
	Search *string `json:"search,omitempty"`
}

// ListOutsideCollaboratorsOptions 获取外部贡献者。List external contributors. 的查询参数.
type ListOutsideCollaboratorsOptions struct {
	ListOptions `json:",inline"`
	// Role 角色。Role. 可选值: Guest, Reporter, Developer, Master.
	Role *string `json:"role,omitempty"`
	// Search 过滤成员。Filter by member.
	Search *string `json:"search,omitempty"`
}

// UpdateOutsideCollaboratorsOptions 更新外部贡献者权限。Update contributor permission. 的查询参数.
type UpdateOutsideCollaboratorsOptions struct {
	// Role 角色。Role. 可选值: Guest, Reporter, Developer.
	Role *string `json:"role,omitempty"`
}

// ListPackagesOptions 查询制品列表。 List all packages. 的查询参数.
type ListPackagesOptions struct {
	ListOptions `json:",inline"`
	// Type 制品类型。Type. 可选值: all, docker, helm, dockermodel, maven, npm, ohpm, pypi, nuget, composer, conan, cargo.
	Type *string `json:"type,omitempty"`
	// Ordering 顺序类型。Ordering type. 可选值: pull_count, last_push_at, name_ascend, name_descend.
	Ordering *string `json:"ordering,omitempty"`
	// Name 关键字。Key word to search package name.
	Name *string `json:"name,omitempty"`
}

// GetPackageTagDetailOptions 获取制品标签详情。Get package tag details. 的查询参数.
type GetPackageTagDetailOptions struct {
	// Sha256 摘要。Digest.
	Sha256 *string `json:"sha256,omitempty"`
	// Arch 架构，docker制品必需，例: linux/amd64/v3。required for docker artifacts
	Arch *string `json:"arch,omitempty"`
}

// ListPackageTagsOptions 查询制品标签列表。List package tags. 的查询参数.
type ListPackageTagsOptions struct {
	ListOptions `json:",inline"`
	// Ordering 顺序。Ordering type. 可选值: pull_count, last_push_at.
	Ordering *string `json:"ordering,omitempty"`
	// TagName 关键字。Key word to search tag name.
	TagName *string `json:"tag_name,omitempty"`
}

// SetPinnedRepoByGroupBody SetPinnedRepoByGroup 的请求体.
type SetPinnedRepoByGroupBody struct {
	_ struct{} `json:"-"`
}

// GetGroupSubRegistriesOptions 查询我的制品仓库。List my registries. 的查询参数.
type GetGroupSubRegistriesOptions struct {
	ListOptions `json:",inline"`
	// RegistryType 制品仓库类型。Registry type. 可选值: npm, maven, ohpm.
	RegistryType *string `json:"registry_type,omitempty"`
	// FilterType 制品仓库可见性类型。Registry visibility type. 可选值: private, public.
	FilterType *string `json:"filter_type,omitempty"`
	// OrderBy 排序类型，默认created_at。Sort order, default created_at. 可选值: created_at, name.
	OrderBy *string `json:"order_by,omitempty"`
	// Desc 排序顺序。Sort order.
	Desc *bool `json:"desc,omitempty"`
	// Descendant 查询范围。Query scope: all/current org/sub-org registries. 可选值: all, sub, grand.
	Descendant *string `json:"descendant,omitempty"`
	// Search 搜索关键字。Search keyword.
	Search *string `json:"search,omitempty"`
}

// GetGroupSubReposOptions 查询组织可见仓库。List visible repos. 的查询参数.
type GetGroupSubReposOptions struct {
	ListOptions `json:",inline"`
	// FilterType 仓库类型。Repositories type. 可选值: private, public, secret.
	FilterType *string `json:"filter_type,omitempty"`
	// Flags 仓库类型标记，逗号分隔。Repository type flags, comma separated 可选值: KnowledgeBase, NPC, Skills.
	Flags *string `json:"flags,omitempty"`
	// FlagsMatch flags 多值匹配模式。Flags match mode when multiple flags provided 可选值: intersection, union.
	FlagsMatch *string `json:"flags_match,omitempty"`
	// Status 仓库状态。Repository status 可选值: active, archived.
	Status *string `json:"status,omitempty"`
	// OrderBy 排序字段。Order field 可选值: created_at, last_updated_at, stars, slug_path, forks.
	OrderBy *string `json:"order_by,omitempty"`
	// Desc 排序顺序。Ordering.
	Desc *bool `json:"desc,omitempty"`
	// Descendant 查全部/查询直接属于当前组织的仓库/查询子组织的仓库。Get all/Get repos belong to current org or sub-organization 可选值: all, sub, grand.
	Descendant *string `json:"descendant,omitempty"`
	// Search 关键字。Key word.
	Search *string `json:"search,omitempty"`
}

// GetArtifactSecurityOverviewOptions 查询制品安全概览。Get artifact security overview. 的查询参数.
type GetArtifactSecurityOverviewOptions struct {
	// Filename 文件名（pypi 类型建议传入；未传时以 artifactID 作为默认值）。File name (recommended for pypi; defaults to artifactID if omitted).
	Filename *string `json:"filename,omitempty"`
	// Types 类型: artifact_vulnerability,artifact_license,artifact_sbom，逗号分隔。容器制品不支持 sbom。
	Types *string `json:"types,omitempty"`
}

// ListStarUsersOptions 获取仓库 Star 用户列表。Get repository star users. 的查询参数.
type ListStarUsersOptions struct {
	ListOptions `json:",inline"`
	// FilterType 筛选类型。Filter type. 可选值: all, followed.
	FilterType *string `json:"filter_type,omitempty"`
}

// ListSubgroupsOptions 获取子组织列表。Get sub-organizations. 的查询参数.
type ListSubgroupsOptions struct {
	ListOptions `json:",inline"`
	// Search 按组织筛选。Filter organization.
	Search *string `json:"search,omitempty"`
}
