// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// CreateOrganization 创建组织。Create organization.
//
// 访问令牌权限: group-manage:rw
//
// CNB API: POST /groups
func (s *OrganizationsService) CreateOrganization(ctx context.Context, body CreateGroupReq) (*Response, error) {
	u := escapePath("/groups")
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// ListTopGroups 获取顶层组织列表。Get top-level organizations.
//
// 访问令牌权限: account-engage:r
//
// CNB API: GET /user/groups
func (s *OrganizationsService) ListTopGroups(ctx context.Context, opts *ListTopGroupsOptions) ([]*OrganizationAccess, *Response, error) {
	u := escapePath("/user/groups")
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*OrganizationAccess
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// ListGroups 查询子组织列表。Get sub-organizations.
//
// 访问令牌权限: account-engage:r
//
// CNB API: GET /user/groups/{slug}
func (s *OrganizationsService) ListGroups(ctx context.Context, slug string, opts *ListGroupsOptions) ([]*OrganizationAccess, *Response, error) {
	u := escapePath("/user/groups/%s", slug)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*OrganizationAccess
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// GetGroupsByUserID 获取用户顶层组织。Get user top-level organizations.
//
// 访问令牌权限: account-engage:r
//
// CNB API: GET /users/{username}/groups
func (s *OrganizationsService) GetGroupsByUserID(ctx context.Context, username string, opts *GetGroupsByUserIDOptions) (*OrganizationUnion, *Response, error) {
	u := escapePath("/users/%s/groups", username)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out OrganizationUnion
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetGroup 获取组织信息。Get organization info.
//
// 访问令牌权限: group-resource:r
//
// CNB API: GET /{group}
func (s *OrganizationsService) GetGroup(ctx context.Context, group string) (*OrganizationAccess, *Response, error) {
	u := escapePath("/%s", group)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out OrganizationAccess
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// UpdateOrganization 更新组织信息。Update organization information.
//
// 访问令牌权限: group-manage:rw
//
// CNB API: PUT /{group}
func (s *OrganizationsService) UpdateOrganization(ctx context.Context, group string, body UpdateGroupReq) (*Response, error) {
	u := escapePath("/%s", group)
	req, err := s.client.NewRequest(http.MethodPut, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// DeleteOrganization 删除组织。Delete organization.
//
// 访问令牌权限: group-delete:rw
//
// CNB API: DELETE /{group}
func (s *OrganizationsService) DeleteOrganization(ctx context.Context, group string) (*Response, error) {
	u := escapePath("/%s", group)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// TransferGroup 转移组织。Transfer an organization.
//
// 访问令牌权限: group-manage:rw
//
// CNB API: POST /{group}/-/transfer
func (s *OrganizationsService) TransferGroup(ctx context.Context, group string, body TransferSlugReq) (*Response, error) {
	u := escapePath("/%s/-/transfer", group)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// UploadLogos 上传 Logo。Upload logo.
//
// 访问令牌权限: group-manage:rw
//
// CNB API: POST /{group}/-/upload/logos
func (s *OrganizationsService) UploadLogos(ctx context.Context, group string, body UploadRequestParams) (*UploadAssetsResponse, *Response, error) {
	u := escapePath("/%s/-/upload/logos", group)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out UploadAssetsResponse
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetGroupSetting 获取组织配置。Get organization settings.
//
// 访问令牌权限: group-manage:r
//
// CNB API: GET /{slug}/-/settings
func (s *OrganizationsService) GetGroupSetting(ctx context.Context, slug string) (*OrganizationSettingWithParent, *Response, error) {
	u := escapePath("/%s/-/settings", slug)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out OrganizationSettingWithParent
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// UpdateGroupSetting 更新组织配置。Update organization configuration.
//
// 访问令牌权限: group-manage:rw
//
// CNB API: PUT /{slug}/-/settings
func (s *OrganizationsService) UpdateGroupSetting(ctx context.Context, slug string, body GroupSettingReq) (*Response, error) {
	u := escapePath("/%s/-/settings", slug)
	req, err := s.client.NewRequest(http.MethodPut, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// ListSubgroups 获取子组织列表。Get sub-organizations.
//
// 访问令牌权限: group-resource:r
//
// CNB API: GET /{slug}/-/sub-groups
func (s *OrganizationsService) ListSubgroups(ctx context.Context, slug string, opts *ListSubgroupsOptions) ([]*OrganizationUnion, *Response, error) {
	u := escapePath("/%s/-/sub-groups", slug)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*OrganizationUnion
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
