// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// GetPrFiles 获取合并请求文件。Get pull request files.
//
// 访问令牌权限: repo-pr:r
//
// CNB API: GET /{repo}/-/files/pulls/{file_path}
func (s *PullsService) GetPrFiles(ctx context.Context, repo string, filePath string) (*Response, error) {
	u := escapePath("/%s/-/files/pulls/%s", repo, filePath)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// DeleteRepoFiles 删除上传附件。Delete uploaded file.
//
// 访问令牌权限: repo-manage:rw
//
// CNB API: DELETE /{repo}/-/files/{filePath}
func (s *PullsService) DeleteRepoFiles(ctx context.Context, repo string, filePath string) (*Response, error) {
	u := escapePath("/%s/-/files/%s", repo, filePath)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// GetPrImgs 获取合并请求图片。Get pull request images.
//
// 访问令牌权限: repo-pr:r
//
// CNB API: GET /{repo}/-/imgs/pulls/{img_path}
func (s *PullsService) GetPrImgs(ctx context.Context, repo string, imgPath string) (*Response, error) {
	u := escapePath("/%s/-/imgs/pulls/%s", repo, imgPath)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// DeleteRepoImgs 删除上传图片。Delete uploaded image.
//
// 访问令牌权限: repo-manage:rw
//
// CNB API: DELETE /{repo}/-/imgs/{imgPath}
func (s *PullsService) DeleteRepoImgs(ctx context.Context, repo string, imgPath string) (*Response, error) {
	u := escapePath("/%s/-/imgs/%s", repo, imgPath)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// ListPullsByNumbers 批量查询合并请求。Batch get pull requests.
//
// 访问令牌权限: repo-pr:r
//
// CNB API: GET /{repo}/-/pull-in-batch
func (s *PullsService) ListPullsByNumbers(ctx context.Context, repo string, opts *ListPullsByNumbersOptions) ([]*PullRequestInfo, *Response, error) {
	u := escapePath("/%s/-/pull-in-batch", repo)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*PullRequestInfo
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// ListPulls 查询合并请求列表。List pull requests.
//
// 访问令牌权限: repo-pr:r
//
// CNB API: GET /{repo}/-/pulls
func (s *PullsService) ListPulls(ctx context.Context, repo string, opts *ListPullsOptions) ([]*PullRequest, *Response, error) {
	u := escapePath("/%s/-/pulls", repo)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*PullRequest
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// PostPull 创建合并请求。Create pull request.
//
// 访问令牌权限: repo-pr:rw
//
// CNB API: POST /{repo}/-/pulls
func (s *PullsService) PostPull(ctx context.Context, repo string, body PullCreationForm) (*Pull, *Response, error) {
	u := escapePath("/%s/-/pulls", repo)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out Pull
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetPull 获取合并请求。Get pull request.
//
// 访问令牌权限: repo-pr:r
//
// CNB API: GET /{repo}/-/pulls/{number}
func (s *PullsService) GetPull(ctx context.Context, repo string, number string) (*Pull, *Response, error) {
	u := escapePath("/%s/-/pulls/%s", repo, number)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out Pull
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// PatchPull 更新合并请求。Update pull request.
//
// 访问令牌权限: repo-pr:rw
//
// CNB API: PATCH /{repo}/-/pulls/{number}
func (s *PullsService) PatchPull(ctx context.Context, repo string, number string, body PatchPullRequest) (*Pull, *Response, error) {
	u := escapePath("/%s/-/pulls/%s", repo, number)
	req, err := s.client.NewRequest(http.MethodPatch, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out Pull
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// ListPullAssignees 查询合并请求处理人。List pull request assignees.
//
// 访问令牌权限: repo-pr:r
//
// CNB API: GET /{repo}/-/pulls/{number}/assignees
func (s *PullsService) ListPullAssignees(ctx context.Context, repo string, number string) ([]*UserInfo, *Response, error) {
	u := escapePath("/%s/-/pulls/%s/assignees", repo, number)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*UserInfo
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// PostPullAssignees 添加合并请求处理人。Add pull request assignees.
//
// 访问令牌权限: repo-pr:rw
//
// CNB API: POST /{repo}/-/pulls/{number}/assignees
func (s *PullsService) PostPullAssignees(ctx context.Context, repo string, number string, body PostPullAssigneesForm) (*Pull, *Response, error) {
	u := escapePath("/%s/-/pulls/%s/assignees", repo, number)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out Pull
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// DeletePullAssignees 移除合并请求处理人。Remove pull request assignee.
//
// 访问令牌权限: repo-pr:rw
//
// CNB API: DELETE /{repo}/-/pulls/{number}/assignees
func (s *PullsService) DeletePullAssignees(ctx context.Context, repo string, number string, body DeletePullAssigneesForm) (*Pull, *Response, error) {
	u := escapePath("/%s/-/pulls/%s/assignees", repo, number)
	req, err := s.client.NewRequest(http.MethodDelete, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out Pull
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// CanUserBeAssignedToPull 检查用户可分配性。Check user assignability.
//
// 访问令牌权限: repo-pr:r
//
// CNB API: GET /{repo}/-/pulls/{number}/assignees/{assignee}
func (s *PullsService) CanUserBeAssignedToPull(ctx context.Context, repo string, number string, assignee string) (*Response, error) {
	u := escapePath("/%s/-/pulls/%s/assignees/%s", repo, number, assignee)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// ListPullComments 查询合并请求评论列表。List pull request comments.
//
// 访问令牌权限: repo-notes:r
//
// CNB API: GET /{repo}/-/pulls/{number}/comments
func (s *PullsService) ListPullComments(ctx context.Context, repo string, number string, opts *ListPullCommentsOptions) ([]*PullRequestComment, *Response, error) {
	u := escapePath("/%s/-/pulls/%s/comments", repo, number)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*PullRequestComment
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// PostPullComment 创建合并请求评论。Create pull request comment.
//
// 访问令牌权限: repo-notes:rw
//
// CNB API: POST /{repo}/-/pulls/{number}/comments
func (s *PullsService) PostPullComment(ctx context.Context, repo string, number string, body PullCommentCreationForm) (*PullRequestComment, *Response, error) {
	u := escapePath("/%s/-/pulls/%s/comments", repo, number)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out PullRequestComment
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetPullComment 获取合并请求评论。Get pull request comment.
//
// 访问令牌权限: repo-notes:r
//
// CNB API: GET /{repo}/-/pulls/{number}/comments/{comment_id}
func (s *PullsService) GetPullComment(ctx context.Context, repo string, number string, commentId int) (*PullRequestComment, *Response, error) {
	u := escapePath("/%s/-/pulls/%s/comments/%d", repo, number, commentId)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out PullRequestComment
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// PatchPullComment 更新合并请求评论。Update pull request comment.
//
// 访问令牌权限: repo-notes:rw
//
// CNB API: PATCH /{repo}/-/pulls/{number}/comments/{comment_id}
func (s *PullsService) PatchPullComment(ctx context.Context, repo string, number string, commentId int, body PatchPullCommentForm) (*PullRequestComment, *Response, error) {
	u := escapePath("/%s/-/pulls/%s/comments/%d", repo, number, commentId)
	req, err := s.client.NewRequest(http.MethodPatch, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out PullRequestComment
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// ListPullCommitStatuses 查询合并请求状态检查。Get pull request status checks.
//
// 访问令牌权限: repo-pr:r
//
// CNB API: GET /{repo}/-/pulls/{number}/commit-statuses
func (s *PullsService) ListPullCommitStatuses(ctx context.Context, repo string, number int) (*CommitStatuses, *Response, error) {
	u := escapePath("/%s/-/pulls/%d/commit-statuses", repo, number)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out CommitStatuses
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// ListPullCommits 查询合并请求提交列表。List pull request commits.
//
// 访问令牌权限: repo-pr:r
//
// CNB API: GET /{repo}/-/pulls/{number}/commits
func (s *PullsService) ListPullCommits(ctx context.Context, repo string, number string, opts *ListPullCommitsOptions) ([]*Commit, *Response, error) {
	u := escapePath("/%s/-/pulls/%s/commits", repo, number)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*Commit
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// ListPullFiles 查询合并请求文件列表。List pull request files.
//
// 访问令牌权限: repo-pr:r
//
// CNB API: GET /{repo}/-/pulls/{number}/files
func (s *PullsService) ListPullFiles(ctx context.Context, repo string, number string) ([]*PullFile, *Response, error) {
	u := escapePath("/%s/-/pulls/%s/files", repo, number)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*PullFile
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// ListPullLabels 查询合并请求标签。List pull request labels.
//
// 访问令牌权限: repo-pr:r
//
// CNB API: GET /{repo}/-/pulls/{number}/labels
func (s *PullsService) ListPullLabels(ctx context.Context, repo string, number int, opts *ListPullLabelsOptions) ([]*Label, *Response, error) {
	u := escapePath("/%s/-/pulls/%d/labels", repo, number)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*Label
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// PutPullLabels 设置合并请求标签。Set pull request labels.
//
// 访问令牌权限: repo-pr:rw
//
// CNB API: PUT /{repo}/-/pulls/{number}/labels
func (s *PullsService) PutPullLabels(ctx context.Context, repo string, number string, body PutPullLabelsForm) (*Label, *Response, error) {
	u := escapePath("/%s/-/pulls/%s/labels", repo, number)
	req, err := s.client.NewRequest(http.MethodPut, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out Label
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// PostPullLabels 添加合并请求标签。Add pull request labels.
//
// 访问令牌权限: repo-pr:rw
//
// CNB API: POST /{repo}/-/pulls/{number}/labels
func (s *PullsService) PostPullLabels(ctx context.Context, repo string, number string, body PostPullLabelsForm) (*Label, *Response, error) {
	u := escapePath("/%s/-/pulls/%s/labels", repo, number)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out Label
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// DeletePullLabels 删除全部合并请求标签。Clear all pull request labels.
//
// 访问令牌权限: repo-pr:rw
//
// CNB API: DELETE /{repo}/-/pulls/{number}/labels
func (s *PullsService) DeletePullLabels(ctx context.Context, repo string, number string) (*Response, error) {
	u := escapePath("/%s/-/pulls/%s/labels", repo, number)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// DeletePullLabel 移除合并请求标签。Remove pull request label.
//
// 访问令牌权限: repo-pr:rw
//
// CNB API: DELETE /{repo}/-/pulls/{number}/labels/{name}
func (s *PullsService) DeletePullLabel(ctx context.Context, repo string, number string, name string) (*Label, *Response, error) {
	u := escapePath("/%s/-/pulls/%s/labels/%s", repo, number, name)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out Label
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// MergePull 合并拉取请求。Merge pull request.
//
// 访问令牌权限: repo-pr:rw
//
// CNB API: PUT /{repo}/-/pulls/{number}/merge
func (s *PullsService) MergePull(ctx context.Context, repo string, number string, body MergePullRequest) (*MergePullResponse, *Response, error) {
	u := escapePath("/%s/-/pulls/%s/merge", repo, number)
	req, err := s.client.NewRequest(http.MethodPut, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out MergePullResponse
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// PostPullReviewers 添加合并请求评审人。Add pull request reviewers.
//
// 访问令牌权限: repo-pr:rw
//
// CNB API: POST /{repo}/-/pulls/{number}/reviewers
func (s *PullsService) PostPullReviewers(ctx context.Context, repo string, number string, body PostPullReviewersForm) (*Pull, *Response, error) {
	u := escapePath("/%s/-/pulls/%s/reviewers", repo, number)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out Pull
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// DeletePullReviewers 移除合并请求评审人。Remove pull request reviewer.
//
// 访问令牌权限: repo-pr:rw
//
// CNB API: DELETE /{repo}/-/pulls/{number}/reviewers
func (s *PullsService) DeletePullReviewers(ctx context.Context, repo string, number string, body DeletePullReviewersForm) (*Pull, *Response, error) {
	u := escapePath("/%s/-/pulls/%s/reviewers", repo, number)
	req, err := s.client.NewRequest(http.MethodDelete, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out Pull
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// ListPullReviews 查询合并请求评审列表。List pull request reviews.
//
// 访问令牌权限: repo-notes:r
//
// CNB API: GET /{repo}/-/pulls/{number}/reviews
func (s *PullsService) ListPullReviews(ctx context.Context, repo string, number string, opts *ListPullReviewsOptions) ([]*PullReview, *Response, error) {
	u := escapePath("/%s/-/pulls/%s/reviews", repo, number)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*PullReview
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// PostPullReview 创建合并请求评审。Create pull request review.
//
// 访问令牌权限: repo-notes:rw
//
// CNB API: POST /{repo}/-/pulls/{number}/reviews
func (s *PullsService) PostPullReview(ctx context.Context, repo string, number string, body PullReviewCreationForm) (*Response, error) {
	u := escapePath("/%s/-/pulls/%s/reviews", repo, number)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// ListPullReviewComments 查询评审评论列表。List review comments.
//
// 访问令牌权限: repo-notes:r
//
// CNB API: GET /{repo}/-/pulls/{number}/reviews/{review_id}/comments
func (s *PullsService) ListPullReviewComments(ctx context.Context, repo string, number int, reviewId int, opts *ListPullReviewCommentsOptions) ([]*PullReviewComment, *Response, error) {
	u := escapePath("/%s/-/pulls/%d/reviews/%d/comments", repo, number, reviewId)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*PullReviewComment
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// PostPullRequestReviewReply 回复评审评论。Reply to review comment.
//
// 访问令牌权限: repo-notes:rw
//
// CNB API: POST /{repo}/-/pulls/{number}/reviews/{review_id}/replies
func (s *PullsService) PostPullRequestReviewReply(ctx context.Context, repo string, number int, reviewId int, body PostPullRequestReviewReplyForm) (*PullReviewComment, *Response, error) {
	u := escapePath("/%s/-/pulls/%d/reviews/%d/replies", repo, number, reviewId)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out PullReviewComment
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// UploadFiles 上传文件。Upload files.
//
// 访问令牌权限: repo-notes:rw
//
// CNB API: POST /{repo}/-/upload/files
func (s *PullsService) UploadFiles(ctx context.Context, repo string, body UploadRequestParams) (*UploadAssetsResponse, *Response, error) {
	u := escapePath("/%s/-/upload/files", repo)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out UploadAssetsResponse
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// UploadImgs 上传图片。Upload images.
//
// 访问令牌权限: repo-code:rw
//
// CNB API: POST /{repo}/-/upload/imgs
func (s *PullsService) UploadImgs(ctx context.Context, repo string, body UploadRequestParams) (*UploadAssetsResponse, *Response, error) {
	u := escapePath("/%s/-/upload/imgs", repo)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out UploadAssetsResponse
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}
