// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// GetRepoAnnualRank 获取公仓年榜。Get annual public repo ranking.
//
// 访问令牌权限: repo-basic-info:r
//
// CNB API: GET /ranks/repo/annual
func (s *RankService) GetRepoAnnualRank(ctx context.Context, opts *GetRepoAnnualRankOptions) (*GetRankResult, *Response, error) {
	u := escapePath("/ranks/repo/annual")
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out GetRankResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetRepoDailyRank 获取公仓日榜。Get daily public repo ranking.
//
// 访问令牌权限: repo-basic-info:r
//
// CNB API: GET /ranks/repo/daily
func (s *RankService) GetRepoDailyRank(ctx context.Context, opts *GetRepoDailyRankOptions) (*GetRankResult, *Response, error) {
	u := escapePath("/ranks/repo/daily")
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out GetRankResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetLanguageList 获取排行榜语言。Get ranking languages.
//
// 访问令牌权限: repo-basic-info:r
//
// CNB API: GET /ranks/repo/language-list
func (s *RankService) GetLanguageList(ctx context.Context, opts *GetLanguageListOptions) (*RankLanguageList, *Response, error) {
	u := escapePath("/ranks/repo/language-list")
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out RankLanguageList
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetRepoMonthlyRank 获取公仓月榜。Get monthly public repo ranking.
//
// 访问令牌权限: repo-basic-info:r
//
// CNB API: GET /ranks/repo/monthly
func (s *RankService) GetRepoMonthlyRank(ctx context.Context, opts *GetRepoMonthlyRankOptions) (*GetRankResult, *Response, error) {
	u := escapePath("/ranks/repo/monthly")
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out GetRankResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetRepoWeeklyRank 获取公仓周榜。Get weekly public repo ranking.
//
// 访问令牌权限: repo-basic-info:r
//
// CNB API: GET /ranks/repo/weekly
func (s *RankService) GetRepoWeeklyRank(ctx context.Context, opts *GetRepoWeeklyRankOptions) (*GetRankResult, *Response, error) {
	u := escapePath("/ranks/repo/weekly")
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out GetRankResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}
