// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// DeleteRegistry 删除制品库。Delete the registry.
//
// 访问令牌权限: registry-delete:rw
//
// CNB API: DELETE /{registry}
func (s *RegistriesService) DeleteRegistry(ctx context.Context, registry string) (*Response, error) {
	u := escapePath("/%s", registry)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// ListPackages 查询制品列表。 List all packages.
//
// 访问令牌权限: registry-package:r
//
// CNB API: GET /{slug}/-/packages
func (s *RegistriesService) ListPackages(ctx context.Context, slug string, opts *ListPackagesOptions) ([]*Package, *Response, error) {
	u := escapePath("/%s/-/packages", slug)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*Package
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// GetPackage 获取指定制品的详细信息。 Get the package detail.
//
// 访问令牌权限: registry-package:r
//
// CNB API: GET /{slug}/-/packages/{type}/{name}
func (s *RegistriesService) GetPackage(ctx context.Context, slug string, pkgType string, name string) (*PackageDetail, *Response, error) {
	u := escapePath("/%s/-/packages/%s/%s", slug, pkgType, name)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out PackageDetail
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// DeletePackage 删除制品。Delete the specific package.
//
// 访问令牌权限: registry-package-delete:rw
//
// CNB API: DELETE /{slug}/-/packages/{type}/{name}
func (s *RegistriesService) DeletePackage(ctx context.Context, slug string, pkgType string, name string) (*Response, error) {
	u := escapePath("/%s/-/packages/%s/%s", slug, pkgType, name)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// UpdatePackageDescription 更新制品描述。Update the description of the specific package.
//
// 访问令牌权限: registry-package:rw
//
// CNB API: PUT /{slug}/-/packages/{type}/{name}/-/description
func (s *RegistriesService) UpdatePackageDescription(ctx context.Context, slug string, pkgType string, name string, body UpdatePackageRequest) (*Response, error) {
	u := escapePath("/%s/-/packages/%s/%s/-/description", slug, pkgType, name)
	req, err := s.client.NewRequest(http.MethodPut, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// GetPackageTagDetail 获取制品标签详情。Get package tag details.
//
// 访问令牌权限: registry-package:r
//
// CNB API: GET /{slug}/-/packages/{type}/{name}/-/tag/{tag}
func (s *RegistriesService) GetPackageTagDetail(ctx context.Context, slug string, pkgType string, name string, tag string, opts *GetPackageTagDetailOptions) (*TagDetail, *Response, error) {
	u := escapePath("/%s/-/packages/%s/%s/-/tag/%s", slug, pkgType, name, tag)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out TagDetail
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// DeletePackageTag 删除制品标签。Delete package tag.
//
// 访问令牌权限: registry-package-delete:rw
//
// CNB API: DELETE /{slug}/-/packages/{type}/{name}/-/tag/{tag}
func (s *RegistriesService) DeletePackageTag(ctx context.Context, slug string, pkgType string, name string, tag string) (*Response, error) {
	u := escapePath("/%s/-/packages/%s/%s/-/tag/%s", slug, pkgType, name, tag)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// GetPackageTagProvenance 获取制品标签溯源。Get package tag provenance.
//
// 访问令牌权限: registry-package:r
//
// CNB API: GET /{slug}/-/packages/{type}/{name}/-/tag/{tag}/provenance
func (s *RegistriesService) GetPackageTagProvenance(ctx context.Context, slug string, pkgType string, name string, tag string) (*Provenance, *Response, error) {
	u := escapePath("/%s/-/packages/%s/%s/-/tag/%s/provenance", slug, pkgType, name, tag)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out Provenance
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// ListPackageTags 查询制品标签列表。List package tags.
//
// 访问令牌权限: registry-package:r
//
// CNB API: GET /{slug}/-/packages/{type}/{name}/-/tags
func (s *RegistriesService) ListPackageTags(ctx context.Context, slug string, pkgType string, name string, opts *ListPackageTagsOptions) (*PlatformServiceApiInternalModelsArtifactoryDtoTag, *Response, error) {
	u := escapePath("/%s/-/packages/%s/%s/-/tags", slug, pkgType, name)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out PlatformServiceApiInternalModelsArtifactoryDtoTag
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetGroupSubRegistries 查询我的制品仓库。List my registries.
//
// 访问令牌权限: group-resource:r
//
// CNB API: GET /{slug}/-/registries
func (s *RegistriesService) GetGroupSubRegistries(ctx context.Context, slug string, opts *GetGroupSubRegistriesOptions) ([]*Registry4User, *Response, error) {
	u := escapePath("/%s/-/registries", slug)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*Registry4User
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
