// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// ListReleases 查询版本列表。List releases.
//
// 访问令牌权限: repo-release:r
//
// CNB API: GET /{repo}/-/releases
func (s *ReleasesService) ListReleases(ctx context.Context, repo string, opts *ListReleasesOptions) ([]*Release, *Response, error) {
	u := escapePath("/%s/-/releases", repo)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*Release
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// PostRelease 创建版本。Create release.
//
// 访问令牌权限: repo-release:rw
//
// CNB API: POST /{repo}/-/releases
func (s *ReleasesService) PostRelease(ctx context.Context, repo string, body PostReleaseForm) (*Release, *Response, error) {
	u := escapePath("/%s/-/releases", repo)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out Release
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetReleasesAsset 下载 Release 附件。Download release attachments.
//
// 访问令牌权限: repo-release:r
//
// CNB API: GET /{repo}/-/releases/download/{tag}/{filename}
func (s *ReleasesService) GetReleasesAsset(ctx context.Context, repo string, tag string, filename string, opts *GetReleasesAssetOptions) (*Response, error) {
	u := escapePath("/%s/-/releases/download/%s/%s", repo, tag, filename)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// HeadReleasesAsset 检查 Release 附件。Check release attachment.
//
// 访问令牌权限: repo-release:r
//
// CNB API: HEAD /{repo}/-/releases/download/{tag}/{filename}
func (s *ReleasesService) HeadReleasesAsset(ctx context.Context, repo string, tag string, filename string) (*Response, error) {
	u := escapePath("/%s/-/releases/download/%s/%s", repo, tag, filename)
	req, err := s.client.NewRequest(http.MethodHead, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// GetLatestRelease 获取最新版本。Get latest release.
//
// 访问令牌权限: repo-release:r
//
// CNB API: GET /{repo}/-/releases/latest
func (s *ReleasesService) GetLatestRelease(ctx context.Context, repo string) (*Release, *Response, error) {
	u := escapePath("/%s/-/releases/latest", repo)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out Release
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetReleaseByTag 根据标签获取版本。Get release by tag.
//
// 访问令牌权限: repo-release:r
//
// CNB API: GET /{repo}/-/releases/tags/{tag}
func (s *ReleasesService) GetReleaseByTag(ctx context.Context, repo string, tag string) (*Release, *Response, error) {
	u := escapePath("/%s/-/releases/tags/%s", repo, tag)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out Release
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetReleaseByID 获取版本。Get release.
//
// 访问令牌权限: repo-release:r
//
// CNB API: GET /{repo}/-/releases/{release_id}
func (s *ReleasesService) GetReleaseByID(ctx context.Context, repo string, releaseId string) (*Release, *Response, error) {
	u := escapePath("/%s/-/releases/%s", repo, releaseId)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out Release
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// DeleteRelease 删除版本。Delete release.
//
// 访问令牌权限: repo-release:rw
//
// CNB API: DELETE /{repo}/-/releases/{release_id}
func (s *ReleasesService) DeleteRelease(ctx context.Context, repo string, releaseId string) (*Response, error) {
	u := escapePath("/%s/-/releases/%s", repo, releaseId)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// PatchRelease 更新版本。Update release.
//
// 访问令牌权限: repo-release:rw
//
// CNB API: PATCH /{repo}/-/releases/{release_id}
func (s *ReleasesService) PatchRelease(ctx context.Context, repo string, releaseId string, body PatchReleaseForm) (*Response, error) {
	u := escapePath("/%s/-/releases/%s", repo, releaseId)
	req, err := s.client.NewRequest(http.MethodPatch, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// PostReleaseAssetUploadConfirmation 确认附件上传。Confirm asset upload.
//
// 访问令牌权限: repo-release:rw
//
// CNB API: POST /{repo}/-/releases/{release_id}/asset-upload-confirmation/{upload_token}/{asset_path}
func (s *ReleasesService) PostReleaseAssetUploadConfirmation(ctx context.Context, repo string, releaseId string, uploadToken string, assetPath string, opts *PostReleaseAssetUploadConfirmationOptions) (*Response, error) {
	u := escapePath("/%s/-/releases/%s/asset-upload-confirmation/%s/%s", repo, releaseId, uploadToken, assetPath)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodPost, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// PostReleaseAssetUploadURL 获取附件上传地址。Get asset upload URL.
//
// 访问令牌权限: repo-release:rw
//
// CNB API: POST /{repo}/-/releases/{release_id}/asset-upload-url
func (s *ReleasesService) PostReleaseAssetUploadURL(ctx context.Context, repo string, releaseId string, body PostReleaseAssetUploadURLForm) (*ReleaseAssetUploadURL, *Response, error) {
	u := escapePath("/%s/-/releases/%s/asset-upload-url", repo, releaseId)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out ReleaseAssetUploadURL
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetReleaseAsset 获取版本附件。Get release asset.
//
// 访问令牌权限: repo-release:r
//
// CNB API: GET /{repo}/-/releases/{release_id}/assets/{asset_id}
func (s *ReleasesService) GetReleaseAsset(ctx context.Context, repo string, releaseId string, assetId string) (*ReleaseAsset, *Response, error) {
	u := escapePath("/%s/-/releases/%s/assets/%s", repo, releaseId, assetId)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out ReleaseAsset
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// DeleteReleaseAsset 删除版本附件。Delete release asset.
//
// 访问令牌权限: repo-release:rw
//
// CNB API: DELETE /{repo}/-/releases/{release_id}/assets/{asset_id}
func (s *ReleasesService) DeleteReleaseAsset(ctx context.Context, repo string, releaseId string, assetId string) (*Response, error) {
	u := escapePath("/%s/-/releases/%s/assets/%s", repo, releaseId, assetId)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}
