// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// ListCodeIssueOpenAPI 查询代码扫描问题列表。List code scan issues.
//
// 访问令牌权限: repo-code:r
//
// CNB API: GET /{slug}/-/code/issues
func (s *RepoCodeIssueService) ListCodeIssueOpenAPI(ctx context.Context, slug string, opts *ListCodeIssueOpenAPIOptions) (*CodeIssueListData, *Response, error) {
	u := escapePath("/%s/-/code/issues", slug)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out CodeIssueListData
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetCodeIssueDetailOpenAPI 获取代码扫描问题详情。Get code scan issue details.
//
// 访问令牌权限: repo-code:r
//
// CNB API: GET /{slug}/-/code/issues/{record_id}
func (s *RepoCodeIssueService) GetCodeIssueDetailOpenAPI(ctx context.Context, slug string, recordId int) (*CodeIssueDetail, *Response, error) {
	u := escapePath("/%s/-/code/issues/%d", slug, recordId)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out CodeIssueDetail
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}
