// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// ListLabels 查询仓库标签列表。List repository labels.
//
// 访问令牌权限: repo-notes:r
//
// CNB API: GET /{repo}/-/labels
func (s *RepoLabelsService) ListLabels(ctx context.Context, repo string, opts *ListLabelsOptions) ([]*Label, *Response, error) {
	u := escapePath("/%s/-/labels", repo)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*Label
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// PostLabel 创建仓库标签。Create repository label.
//
// 访问令牌权限: repo-notes:rw
//
// CNB API: POST /{repo}/-/labels
func (s *RepoLabelsService) PostLabel(ctx context.Context, repo string, body PostLabelForm) (*Label, *Response, error) {
	u := escapePath("/%s/-/labels", repo)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out Label
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// DeleteLabel 删除仓库标签。Delete repository label.
//
// 访问令牌权限: repo-notes:rw
//
// CNB API: DELETE /{repo}/-/labels/{name}
func (s *RepoLabelsService) DeleteLabel(ctx context.Context, repo string, name string) (*Response, error) {
	u := escapePath("/%s/-/labels/%s", repo, name)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// PatchLabel 更新仓库标签。Update repository label.
//
// 访问令牌权限: repo-notes:rw
//
// CNB API: PATCH /{repo}/-/labels/{name}
func (s *RepoLabelsService) PatchLabel(ctx context.Context, repo string, name string, body PatchLabelForm) (*Label, *Response, error) {
	u := escapePath("/%s/-/labels/%s", repo, name)
	req, err := s.client.NewRequest(http.MethodPatch, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out Label
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}
