// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// GetRepoContributorTrend 查询贡献者趋势数据。Get contributor trend data.
//
// 访问令牌权限: repo-code:r
//
// CNB API: GET /{slug}/-/contributor/trend
func (s *RepoContributorService) GetRepoContributorTrend(ctx context.Context, slug string, opts *GetRepoContributorTrendOptions) (*RepoContribTrend, *Response, error) {
	u := escapePath("/%s/-/contributor/trend", slug)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out RepoContribTrend
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}
