// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// GetRepos 获取我的仓库。List my repositories.
//
// 访问令牌权限: account-engage:r
//
// CNB API: GET /user/repos
func (s *RepositoriesService) GetRepos(ctx context.Context, opts *GetReposOptions) ([]*Repos4User, *Response, error) {
	u := escapePath("/user/repos")
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*Repos4User
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// GetPinnedRepoByID 获取用户仓库墙。Get user pinned repositories.
//
// 访问令牌权限: account-engage:r
//
// CNB API: GET /users/{username}/pinned-repos
func (s *RepositoriesService) GetPinnedRepoByID(ctx context.Context, username string) ([]*Repos4User, *Response, error) {
	u := escapePath("/users/%s/pinned-repos", username)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*Repos4User
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// GetReposByUserName 获取用户可见仓库。List user visible repositories.
//
// 访问令牌权限: account-engage:r
//
// CNB API: GET /users/{username}/repos
func (s *RepositoriesService) GetReposByUserName(ctx context.Context, username string, opts *GetReposByUserNameOptions) ([]*Repos4User, *Response, error) {
	u := escapePath("/users/%s/repos", username)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*Repos4User
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// GetByID 获取仓库信息。Get repository info.
//
// 访问令牌权限: repo-basic-info:r
//
// CNB API: GET /{repo}
func (s *RepositoriesService) GetByID(ctx context.Context, repo string) (*Repos4User, *Response, error) {
	u := escapePath("/%s", repo)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out Repos4User
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// DeleteRepo 删除指定仓库。Delete the specified repository.
//
// 访问令牌权限: repo-delete:rw
//
// CNB API: DELETE /{repo}
func (s *RepositoriesService) DeleteRepo(ctx context.Context, repo string) (*Response, error) {
	u := escapePath("/%s", repo)
	req, err := s.client.NewRequest(http.MethodDelete, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// UpdateRepo 更新仓库信息。Update repository information.
//
// 访问令牌权限: repo-manage:rw
//
// CNB API: PATCH /{repo}
func (s *RepositoriesService) UpdateRepo(ctx context.Context, repo string, body RepoPatch) (*Response, error) {
	u := escapePath("/%s", repo)
	req, err := s.client.NewRequest(http.MethodPatch, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// ListForksRepos 获取仓库 Fork 列表。Get repository fork list.
//
// 访问令牌权限: repo-basic-info:r
//
// CNB API: GET /{repo}/-/forks
func (s *RepositoriesService) ListForksRepos(ctx context.Context, repo string, opts *ListForksReposOptions) (*ListForks, *Response, error) {
	u := escapePath("/%s/-/forks", repo)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out ListForks
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// TransferRepo 转移仓库。Transfer a repository.
//
// 访问令牌权限: repo-manage:rw, repo-code:rw
//
// CNB API: POST /{repo}/-/transfer
func (s *RepositoriesService) TransferRepo(ctx context.Context, repo string, body TransferSlugReq) (*Response, error) {
	u := escapePath("/%s/-/transfer", repo)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// GetPinnedRepoByGroup 获取仓库墙列表。Get pinned repositories.
//
// 访问令牌权限: group-manage:r
//
// CNB API: GET /{slug}/-/pinned-repos
func (s *RepositoriesService) GetPinnedRepoByGroup(ctx context.Context, slug string) ([]*Repos4UserBase, *Response, error) {
	u := escapePath("/%s/-/pinned-repos", slug)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*Repos4UserBase
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// SetPinnedRepoByGroup 更新组织仓库墙。Update pinned repos.
//
// 访问令牌权限: group-manage:rw
//
// CNB API: PUT /{slug}/-/pinned-repos
func (s *RepositoriesService) SetPinnedRepoByGroup(ctx context.Context, slug string, body SetPinnedRepoByGroupBody) ([]*Repos4UserBase, *Response, error) {
	u := escapePath("/%s/-/pinned-repos", slug)
	req, err := s.client.NewRequest(http.MethodPut, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out []*Repos4UserBase
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// GetGroupSubRepos 查询组织可见仓库。List visible repos.
//
// 访问令牌权限: group-resource:r
//
// CNB API: GET /{slug}/-/repos
func (s *RepositoriesService) GetGroupSubRepos(ctx context.Context, slug string, opts *GetGroupSubReposOptions) ([]*Repos4User, *Response, error) {
	u := escapePath("/%s/-/repos", slug)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*Repos4User
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// CreateRepo 创建仓库。Create repositories.
//
// 访问令牌权限: group-resource:rw
//
// CNB API: POST /{slug}/-/repos
func (s *RepositoriesService) CreateRepo(ctx context.Context, slug string, body CreateRepoReq) (*Response, error) {
	u := escapePath("/%s/-/repos", slug)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// ArchiveRepo 归档仓库。Archive repository.
//
// 访问令牌权限: repo-manage:rw, repo-code:rw
//
// CNB API: POST /{slug}/-/settings/archive
func (s *RepositoriesService) ArchiveRepo(ctx context.Context, slug string) (*Response, error) {
	u := escapePath("/%s/-/settings/archive", slug)
	req, err := s.client.NewRequest(http.MethodPost, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// UnArchiveRepo 解除归档。Unarchive repository.
//
// 访问令牌权限: repo-manage:rw, repo-code:rw
//
// CNB API: POST /{slug}/-/settings/unarchive
func (s *RepositoriesService) UnArchiveRepo(ctx context.Context, slug string) (*Response, error) {
	u := escapePath("/%s/-/settings/unarchive", slug)
	req, err := s.client.NewRequest(http.MethodPost, u, nil)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}
