// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// ListPublicRepos 搜索资源。Search resources.
//
// 访问令牌权限: repo-basic-info:r
//
// CNB API: GET /search/public-repos
func (s *SearchService) ListPublicRepos(ctx context.Context, opts *ListPublicReposOptions) ([]*Repos4UserBase, *Response, error) {
	u := escapePath("/search/public-repos")
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*Repos4UserBase
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
