// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// GetRepoSecurityOverview 查询仓库安全概览。Get repository security overview.
//
// 访问令牌权限: repo-security:r
//
// CNB API: GET /{repo}/-/security/overview
func (s *SecurityService) GetRepoSecurityOverview(ctx context.Context, repo string, opts *GetRepoSecurityOverviewOptions) (*RepoSecurityOverview, *Response, error) {
	u := escapePath("/%s/-/security/overview", repo)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out RepoSecurityOverview
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}
