// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// GetUserAllStaredRepos 获取 Star 仓库列表。List starred repositories.
//
// 访问令牌权限: account-engage:r
//
// CNB API: GET /user/stared-repos
func (s *StarringService) GetUserAllStaredRepos(ctx context.Context, opts *GetUserAllStaredReposOptions) ([]*Repos4User, *Response, error) {
	u := escapePath("/user/stared-repos")
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*Repos4User
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// GetUserStaredRepos 获取用户 Star 仓库。Get user starred repositories.
//
// 访问令牌权限: account-engage:r
//
// CNB API: GET /users/{username}/stared-repos
func (s *StarringService) GetUserStaredRepos(ctx context.Context, username string, opts *GetUserStaredReposOptions) ([]*Repos4User, *Response, error) {
	u := escapePath("/users/%s/stared-repos", username)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []*Repos4User
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// ListStarUsers 获取仓库 Star 用户列表。Get repository star users.
//
// 访问令牌权限: repo-basic-info:r
//
// CNB API: GET /{slug}/-/stars
func (s *StarringService) ListStarUsers(ctx context.Context, slug string, opts *ListStarUsersOptions) (*RepoStarUsers, *Response, error) {
	u := escapePath("/%s/-/stars", slug)
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out RepoStarUsers
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}
