// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// GetUserInfo 获取用户详情。Get user details.
//
// 访问令牌权限: account-profile:r
//
// CNB API: GET /user
func (s *UsersService) GetUserInfo(ctx context.Context) (*UsersResult, *Response, error) {
	u := escapePath("/user")
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out UsersResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// UpdateUserInfo 更新用户资料。Update user profile.
//
// 访问令牌权限: account-profile:rw
//
// CNB API: POST /user
func (s *UsersService) UpdateUserInfo(ctx context.Context, body UpdateUserInfoPayload) (*Response, error) {
	u := escapePath("/user")
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, err
	}
	return s.client.Do(ctx, req, nil)
}

// AutoCompleteSource 查询用户资源列表。List user resources.
//
// 访问令牌权限: account-engage:r
//
// CNB API: GET /user/autocomplete_source
func (s *UsersService) AutoCompleteSource(ctx context.Context, opts *AutoCompleteSourceOptions) ([]string, *Response, error) {
	u := escapePath("/user/autocomplete_source")
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out []string
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// ListEmail 获取邮箱列表。Get email list.
//
// 访问令牌权限: account-email:r
//
// CNB API: GET /user/emails
func (s *UsersService) ListEmail(ctx context.Context) (*UserEmails, *Response, error) {
	u := escapePath("/user/emails")
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out UserEmails
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// ListGPGKeys 查询用户 GPG 密钥列表。List user GPG keys.
//
// 访问令牌权限: account-profile:r
//
// CNB API: GET /user/gpg-keys
func (s *UsersService) ListGPGKeys(ctx context.Context, opts *ListGPGKeysOptions) (*GPGPublicKey, *Response, error) {
	u := escapePath("/user/gpg-keys")
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out GPGPublicKey
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetUserInfoByName 获取用户详情。Get user details.
//
// 访问令牌权限: account-profile:r
//
// CNB API: GET /users/{username}
func (s *UsersService) GetUserInfoByName(ctx context.Context, username string) (*UsersResult, *Response, error) {
	u := escapePath("/users/%s", username)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out UsersResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}
