// Code generated by internal/gen/generate.py from api.cnb.cool swagger.json. DO NOT EDIT.

package cnb

import (
	"context"
	"net/http"
)

// DeleteWorkspace 删除我的云原生开发环境。Delete my workspace.
//
// 访问令牌权限: account-engage:rw
//
// CNB API: POST /workspace/delete
func (s *WorkspaceService) DeleteWorkspace(ctx context.Context, body WorkspaceDeleteReq) (*WorkspaceDeleteResult, *Response, error) {
	u := escapePath("/workspace/delete")
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out WorkspaceDeleteResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// ListWorkspaces 获取我的云原生开发环境列表。List my workspaces.
//
// 访问令牌权限: account-engage:r
//
// CNB API: GET /workspace/list
func (s *WorkspaceService) ListWorkspaces(ctx context.Context, opts *ListWorkspacesOptions) (*WorkspaceListResult, *Response, error) {
	u := escapePath("/workspace/list")
	if opts != nil {
		var err error
		u, err = addQuery(u, opts)
		if err != nil {
			return nil, nil, err
		}
	}
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out WorkspaceListResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// WorkspaceStop 停止/关闭我的云原生开发环境。Stop/close my workspace.
//
// 访问令牌权限: account-engage:rw
//
// CNB API: POST /workspace/stop
func (s *WorkspaceService) WorkspaceStop(ctx context.Context, body WorkspaceStopReq) (*WorkspaceStopResult, *Response, error) {
	u := escapePath("/workspace/stop")
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out WorkspaceStopResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// GetWorkspaceDetail 获取云原生开发地址。Get workspace access URL.
//
// 访问令牌权限: repo-cnb-detail:r
//
// CNB API: GET /{repo}/-/workspace/detail/{sn}
func (s *WorkspaceService) GetWorkspaceDetail(ctx context.Context, repo string, sn string) (*WorkspaceDetailResult, *Response, error) {
	u := escapePath("/%s/-/workspace/detail/%s", repo, sn)
	req, err := s.client.NewRequest(http.MethodGet, u, nil)
	if err != nil {
		return nil, nil, err
	}
	var out WorkspaceDetailResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}

// StartWorkspace 启动云原生开发。Start cloud-native development.
//
// 访问令牌权限: repo-cnb-trigger:rw
//
// CNB API: POST /{repo}/-/workspace/start
func (s *WorkspaceService) StartWorkspace(ctx context.Context, repo string, body StartWorkspaceReq) (*StartWorkspaceResult, *Response, error) {
	u := escapePath("/%s/-/workspace/start", repo)
	req, err := s.client.NewRequest(http.MethodPost, u, body)
	if err != nil {
		return nil, nil, err
	}
	var out StartWorkspaceResult
	resp, err := s.client.Do(ctx, req, &out)
	if err != nil {
		return nil, resp, err
	}
	return &out, resp, nil
}
